---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Apéndice 1: Políticas y procedimientos relativos a la revisión, autoría y citas de las descripciones de especies de BOW {#sec-app1 .unnumbered}

Las fichas de especies de Birds of the World (BOW) son documentos "dinámicos" y versionados que se actualizan periódicamente para incorporar nueva información y corregir errores. BOW se esfuerza por promulgar revisiones de las fichas y asignar la autoría de la forma más justa y precisa posible. Este documento (Apéndice 1) pretende definir las políticas y procedimientos de generación de contenidos de BOW y las expectativas de los colaboradores de BOW. Para garantizar un reconocimiento justo y adecuado de los colaboradores y la coherencia a lo largo de los años, los colaboradores y el personal de BOW se atendrán en la mayor medida posible a las siguientes directrices:

## 1. Historial de versiones y revisiones {#sec-app1-versioning}

Para garantizar que el contenido de cada ficha pueda citarse con exactitud a lo largo del tiempo, las fichas de especies reciben un nuevo "número de versión" y un Identificador de Objeto Digital (DOI) único cada vez que cambia su contenido citable (es decir, texto y referencias).

Las fichas se versionan por número y proyecto fuente (BNA, BOW, HBW o NB), correspondiendo las versiones más antiguas a los números más bajos. Una revisión completa, es decir, una actualización de la mayoría de las secciones de una ficha, corresponde a un cambio de número "mayor" (por ejemplo, de la versión 1.0 a la 2.0 o de la versión 1.1 a la 2.0). Una actualización parcial (es decir, una actualización no exhaustiva que afecta a algunas secciones de una ficha, pero no a la mayoría) correspondería a un cambio de número "menor" (por ejemplo, de 2.0 a 2.1).

Otros cambios que corresponden a un cambio menor pueden incluir un cambio en el nombre de una especie (común o científico) o una clasificación superior o un cambio en el proyecto al que pertenece una ficha (por ejemplo, las fichas BOW son claramente citables en relación con las fichas creadas como parte de los proyectos BNA, HBW y NB), incluso si el contenido en sí no se ha modificado significativamente.

Los números de versión no cambian cuando el personal de BOW o los colaboradores corrigen erratas, actualizan enlaces o realizan otras pequeñas ediciones o cambios. Los mapas, los medios de comunicación y los cambios en los productos relacionados con eBird, como las visualizaciones de Estado y Tendencias o los mapas de ocurrencia de eBird ("mapas púrpura"), tampoco están sujetos al control de versiones.

Cada ficha de especies BOW tiene una página de **Historial de revisiones** que contiene un archivo estable de **cada versión de una ficha**. Cuando está disponible, cada versión tiene (1) una cita recomendada con un número de versión y DOI, (2) una breve descripción de los cambios con respecto a la versión anterior y (en su caso) los nombres de las personas que participaron en esa versión, y (3) un enlace para acceder a esa versión tal y como era en el momento de su publicación.

## 2. Políticas de autoría {#sec-app1-authorship}

La autoría de las fichas de BOW se determina por la **contribución acumulativa relativa de cada colaborador a una versión determinada**, a menos que el equipo de colaboradores y el personal de BOW acuerden conjuntamente un acuerdo alternativo. Esta política garantiza un reconocimiento justo del trabajo académico al tiempo que mantiene la flexibilidad para circunstancias especiales.

La "contribución acumulada" de un colaborador abarca tanto el nuevo contenido añadido a una versión como cualquier contenido conservado de versiones anteriores que se le atribuya. Los colaboradores con el contenido acumulado más importante aparecerán en primer lugar en la cita. Aquellos con contribuciones más modestas pueden aparecer más adelante en la lista de autores o, si sus contribuciones no alcanzan el nivel de autoría, pueden ser reconocidos en las Notas de Revisión de la ficha. Los autores anteriores y los fallecidos conservarán la autoría en las nuevas versiones siempre que conserven una parte suficiente de su contenido atribuido.

Todos los colaboradores de una nueva versión deben acordar un orden de autoría preliminar al principio del proceso de revisión, entendiendo que este orden puede requerir ajustes a medida que avance el trabajo para reflejar las contribuciones reales. En los casos en que los colaboradores no puedan llegar a un consenso sobre el orden de autoría, el personal de BOW mediará en la situación mediante consultas con todas las partes implicadas.

Al enviar una revisión editorial, los colaboradores deben revisar estas normas de autoría (Apéndice 1) e indicar la secuencia de autores propuesta en el formulario de cumplimentación del borrador ([inglés](https://forms.gle/e6uTR5E8Z5aXXc9n6), [español](https://forms.gle/4e3PifYqvKrbQ1tV8)). Aunque el personal de BOW tiene la última palabra a la hora de determinar la autoría y el orden de las citas, considerará cuidadosamente las sugerencias de los colaboradores y discutirá cualquier cambio propuesto con las partes afectadas. Los editores se esfuerzan por aplicar los criterios de autoría de forma coherente y justa en todos las fichas.

Cuando las contribuciones acumulativas no puedan diferenciarse claramente, el personal de BOW podrá secuenciar los nombres de los autores en la cita por orden alfabético o, en el caso de los colaboradores por secciones, en el orden en que su contenido aparezca en la ficha, a menos que se acuerden mutuamente disposiciones alternativas.

Una ficha puede incorporar texto de múltiples colaboradores a lo largo del tiempo. Los autores pueden ser eliminados de la lista de autores a petición suya o si los editores determinan que no queda suficiente contenido atribuido en la versión actual. No obstante, las versiones originales publicadas y su autoría se conservarán en el Historial de revisiones. Los colaboradores deben especificar en el Formulario de Información de autoras y autores de BOW ([inglés](https://forms.gle/C3MySs5DtQZ1NR6b8), [español](https://forms.gle/EZes93EWtmtrvtXi7)) si desean que se les notifiquen los cambios de autoría.

Cuando en las nuevas versiones se conserven datos u observaciones inéditos de autores anteriores, éstos deberán citarse adecuadamente haciendo referencia a la ficha anterior. Por ejemplo: "Anderson en Jones y Anderson (1998)". Tales contribuciones se conservarán en el Historial de la ficha y pueden anotarse en la sección de Agradecimientos.

Para mantener el estatus de autor, se anima a los autores a participar activamente en las actualizaciones de su trabajo a lo largo de varias versiones. Los colaboradores comprometidos y en regla pueden consultar con el personal de BOW el calendario y la aplicación de futuras actualizaciones de sus fichas.

## 3. Mantener el estatus de "autor activo" {#sec-app1-active}

A partir de 2025, los colaboradores deben revisar y renovar su Formulario de Información de autoras y autores de BOW ([inglés](https://forms.gle/C3MySs5DtQZ1NR6b8), [español](https://forms.gle/EZes93EWtmtrvtXi7)) y el [Acuerdo del Colaborador](https://drive.google.com/file/d/1Arz8mqAamqQFlIfV2zNJFQbbB5Y0D4Ug/view?usp=sharing)asociado cada dos años para mantener el estatus de colaborador "activo". Los colaboradores activos pueden consultar cómo y cuándo se actualiza su trabajo, y los editores de BOW harán todos los esfuerzos razonables para adaptarse a sus preferencias y facilitar su participación continuada en el proyecto. 

Este requisito garantiza que la información de contacto esté actualizada y que se mantenga el compromiso con el proyecto BOW. Los colaboradores que se vuelvan "inactivos" pueden perder su capacidad de influir en el calendario y la aplicación de las revisiones, y el personal de BOW ya no estará obligado a ponerse en contacto con ellos.

Los colaboradores deben indicar claramente sus métodos de contacto preferidos y el nivel de participación deseado en el Formulario deInformación de autoras y autores de BOW. Aunque el personal de BOW hará todos los esfuerzos razonables para adaptarse a estas preferencias, se reserva el derecho de anular las preferencias que impidan innecesariamente la actualización de la ficha o entren en conflicto con los objetivos y normas éticas de BOW.

Al ponerse en contacto con los autores que hayan solicitado notificación, el personal de BOW utilizará la información de contacto facilitada. Si no se recibe respuesta en el plazo de dos semanas, el personal procederá a identificar autores alternativos para una ficha de especies. Un simple acuse de recibo de la comunicación es suficiente para mantener el estado activo.

La condición de activo puede perderse si:

-   El formulario de información sobre los autores caduca sin renovación

-   Comunicaciones del personal de BOW sin respuesta durante más de dos semanas

-   Durante un año no se registran avances significativos en los borradores.

-   Se infringen las normas de conducta profesional

Aunque todos los colaboradores en regla son siempre bienvenidos a participar en su trabajo independientemente de su estado activo, aquellos que pasen a estar inactivos no serán consultados en relación con las revisiones y se espera que colaboren de forma constructiva con cualquier nueva actualización o colaborador nombrado durante su inactividad.

## 4. Política de revisión de fichas BOW {#sec-app1-revision}

Las descripciones de especies de BOW son documentos dinámicos que requieren actualizaciones periódicas para mantener su valor científico y su utilidad para la conservación. Aunque BOW respeta el esfuerzo sustancial que los colaboradores invierten en crear y revisar las fichas, debemos equilibrarlo con nuestra misión de proporcionar información actualizada y completa. Esta política describe el modo en que los editores de BOW abordarán las revisiones de las fichas, manteniendo la equidad con los colaboradores.

En general, las fichas se revisan cuando surge una necesidad (p. ej., la especie se ve afectada por la actualización taxonómica anual de eBird/Clements Checklist), cuando parte de la ficha está desfasada (p. ej., un cambio en el estado de conservación), cuando un problema requiere una corrección (p. ej., una ficha tiene una declaración de advertencia derivada de un problema con uno o más de sus proyectos fuente), o cuando colaboradores cualificados sugieren o se ofrecen voluntarios para realizar una actualización. 

Cuando se considere la posibilidad de que nuevos colaboradores revisen una ficha, los editores de BOW fomentarán la colaboración con los autores anteriores cuando sea factible, garantizarán la atribución justa de los contenidos nuevos y conservados, y mediarán en las discusiones sobre el orden de autoría.

Cuando se contemple una revisión típica, los editores de BOW se pondrán en contacto en primer lugar con todos los colaboradores activos asociados a esa ficha utilizando el método de comunicación que hayan indicado en el Formulario de Información de autoras y autores de BOW ([inglés](https://forms.gle/C3MySs5DtQZ1NR6b8), [español](https://forms.gle/EZes93EWtmtrvtXi7)). Este contacto inicial de los editores de BOW incluirá el motivo de la revisión propuesta, las opciones de participación y, si procede, información sobre posibles nuevos colaboradores y el plazo previsto y el alcance de la actualización propuesta.

Los colaboradores activos disponen entonces de dos semanas para decidir si desean dirigir o participar en la revisión propuesta. Si no se recibe ninguna respuesta en este plazo, el personal de BOW procederá a la revisión de forma independiente.

Para aquellos que decidan participar, el personal de BOW trabajará con diligencia para desarrollar un plan de revisión que intente acomodarse a los horarios y preferencias de todas las partes. Aunque comprendemos que las revisiones de calidad requieren tiempo y esfuerzo considerables, pedimos a los colaboradores activos que den prioridad a las actualizaciones cuando surjan necesidades u oportunidades. Los colaboradores activos mantienen el derecho a trabajar independientemente de los nuevos colaboradores, siempre que puedan atender las necesidades de revisión en un plazo comparable.

Aunque los editores de BOW harán todo lo posible para satisfacer los deseos de los colaboradores activos en cuanto a cómo y cuándo se revisan las fichas, hay algunas extremadamente prioritarias para la revisión que BOW desearía ver actualizadas lo antes posible. Entre ellas se incluyen las especies cuya conservación suscita especial preocupación, las fichas con problemas conocidos (por ejemplo, cobertura geográficamente desequilibrada o advertencias), las especies con grandes registros de publicación y las fichas que no han sido revisadas desde hace 10 años o más. Si una ficha determinada se considera de "alta prioridad" para su revisión, los colaboradores activos deben elaborar un plan de revisión que demuestre un progreso constante a intervalos mínimos de 3 meses. Si un colaborador no puede cumplir este calendario, el personal de BOW recurrirá a otros colaboradores cualificados para acelerar el calendario de la revisión. La autoría se adjudicará de acuerdo con las normas habituales.

El personal de BOW se esforzará por mantener una comunicación abierta con los colaboradores activos; no obstante, el personal de BOW podrá iniciar revisiones de fichas sin ponerse en contacto con los autores anteriores si (1) una ficha carece de colaboradores activos, (2) no se produce ningún progreso o comunicación significativa durante un año tras una actualización propuesta, o (3) el personal de BOW decide poner fin a la participación de un colaborador (normalmente debido a un rendimiento insatisfactorio, violaciones del acuerdo, retrasos excesivos u otra conducta inapropiada).

Este marco garantiza que BOW mantenga su integridad científica y puntualidad, al tiempo que respeta los esfuerzos de los colaboradores y fomenta las relaciones de colaboración dentro de la comunidad ornitológica.

## 5. Estándares de contenido BOW {#sec-app1-content}

BOW mantiene rigurosos estándares académicos y profesionales para todos los contenidos. No se permite el plagio, la violación de los derechos de autor ni el uso de contenidos generados mediante inteligencia artificial (IA) (véase también la [Política de IA de BOW](https://birdsoftheworld.org/bow/support/ai-policy)). El contenido debe ser objetivo e imparcial y debe basarse en información publicada siempre que sea posible.

BOW mantiene estrictas normas éticas y tiene tolerancia cero con:

-   contenidos o comportamientos discriminatorios por motivos de raza, etnia, sexo, edad, discapacidad, orientación sexual, etc. 

-   mala conducta científica, incluida la fabricación o manipulación de datos, el plagio o las violaciones de la propiedad intelectual

-   acoso, hostilidad o represalias contra los colaboradores o el personal

-   conflictos de intereses no declarados adecuadamente

-   infracciones éticas en los métodos de investigación o en la conducta personal

-   insensibilidad cultural al describir los conocimientos o prácticas indígenas 

Tenga en cuenta que el plagio se define aquí como el uso de contenido derivado no acreditado. Todo el texto debe estar redactado con sus propias palabras originales, y cualquier texto tomado directamente de otra fuente, incluido el texto que haya escrito en otros contextos citables, debe ir entre comillas. Toda la información procedente de otra fuente debe citarse (véase [Gramática y formato: Referencias/Citaciones](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#heading=h.35nkun2)y [Apéndice 5](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.1opuj5n)).

Al participar en el proyecto BOW, los colaboradores afirman que su contenido y comportamiento se atienen a estas normas y que su contenido es obra original de los colaboradores a los que se atribuye. Las infracciones pueden dar lugar al cese inmediato de la participación y a la eliminación de los contenidos. El personal de BOW investigará cualquier problema de forma rápida y exhaustiva.

### Cambios en el contenido {#sec-app1-content-changes}

Aunque el personal de BOW se esfuerza por preservar la integridad del trabajo original de los colaboradores, pueden ser necesarias modificaciones editoriales para asegurar la alineación con las normas y directrices establecidas por BOW. Cuando se requiera una revisión sustancial, los editores se esforzarán por proporcionar información detallada sobre los cambios significativos y las modificaciones necesarias. Los colaboradores que no cumplan adecuadamente estos requisitos pueden enfrentarse a una intervención editorial adicional, al rechazo del material enviado o a la eliminación del contenido. En caso de desacuerdo sobre el contenido o los cambios editoriales, el personal de BOW entablará un diálogo constructivo con las partes implicadas para alcanzar una solución. En los casos en los que no sea posible llegar a un consenso, el personal de BOW mantendrá la máxima autoridad editorial sobre el contenido de la plataforma, aunque los colaboradores conservarán el derecho a retirar sus propuestas y a interrumpir su participación en el proyecto.

Además de los cambios realizados en el transcurso de la revisión editorial de un borrador, los expertos en la materia pueden realizar cambios en las fichas de especies de BOW. Los editores de BOW se esfuerzan por mantener la coherencia de una ficha a otra. Por ello, se deben seguir ciertas convenciones y utilizar cierto lenguaje, especialmente en lo que se refiere a sistemática/taxonomía, mudas/plumajes y estructura/organización de las emisiones vocales. Para garantizar un tratamiento estándar de estas secciones, el personal de BOW puede asignar colaboradores expertos (incluidos miembros del personal) para revisar secciones específicas o ayudar en su revisión. La autoría de estas contribuciones sigue las políticas estándar, salvo acuerdo mutuo.

Los colaboradores tienen tres opciones en cuanto a contenidos especializados: 

-   Los colaboradores pueden solicitar (o dejar a discreción del editor) que un experto en la materia de BOW prepare el contenido especializado, que los colaboradores pueden revisar y editar, si es necesario, antes de su publicación. Este es el enfoque más común. El personal de BOW arbitrará cualquier disputa sobre el contenido.

-   Los colaboradores pueden optar por preparar el material ellos mismos tras informar al personal de BOW de su intención, normalmente a través del Formulario de cumplimentación de borradores ([inglés](https://forms.gle/e6uTR5E8Z5aXXc9n6), [español](https://forms.gle/4e3PifYqvKrbQ1tV8)). Los colaboradores expertos revisarán este contenido, garantizarán el cumplimiento de las convenciones de BOW y sugerirán los cambios necesarios. El personal de BOW mediará en cualquier desacuerdo sobre el contenido. 

-   Los colaboradores pueden colaborar con un experto en la materia durante la preparación del contenido. Los detalles de esta colaboración deben determinarse al principio del proceso de revisión.

En ocasiones, puede haber una necesidad inmediata de revisar ciertas partes de una ficha dentro de un plazo estricto (por ejemplo, durante la actualización taxonómica anual de BOW o si cambia el estado de conservación de una especie). Estos cambios pueden dar lugar a un cambio de versión. Normalmente, el personal de BOW realizará los cambios necesarios o pedirá a un colaborador que lo haga, pero los cambios más pequeños, como los cambios de nombre común, pueden producirse automáticamente. Aunque se notificará a los colaboradores activos cualquier cambio de contenido significativo que sea necesario o esté previsto, es posible que no se les informe de los alineamientos taxonómicos menores con la Lista eBird/Clements, como los cambios de subespecie o los cambios a nivel de género.

A discreción del personal de BOW, se podrá invitar a colaboradores adecuados y/o expertos en la materia que no participen en una revisión a priori a revisar las fichas antes de su publicación. Los colaboradores pueden solicitar una revisión externa, pero no pueden impedirla si los editores lo consideran necesario. Los revisores serán reconocidos en las notas de revisión y enviarán sus comentarios a través de un documento de Word o por correo electrónico, realizando ediciones directas sólo con el acuerdo mutuo del personal de BOW y los colaboradores pertinentes.