---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Apéndice 2: Páginas, secciones y subsecciones de la ficha normalizada {#sec-app2 .unnumbered}

A continuación se muestran las páginas (en morado), secciones (en azul) y subsecciones (en negro) que deberían aparecer en la mayoría o en todas las fichas, en el orden en que deberían aparecer. tenga en cuenta que, a medida que la ciencia ha evolucionado, hemos añadido nuevas secciones y subsecciones que nos gustaría que se incluyeran en todas las fichas. Los colaboradores deben utilizar la siguiente lista como guía sobre lo que deben incluir al completar una revisión, ya que la estructura de la ficha puede haber cambiado recientemente.

Como se explica en la sección @sec-content-structure los colaboradores tienen cierta flexibilidad para incluir, o a veces excluir, determinadas subsecciones y, más raramente, secciones, en función de la biología de sus especies y de la información disponible. No obstante, debe respetarse el orden en que aparece el material a continuación. [En el Apéndice 3](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.hjoo9cq14meu) se dan orientaciones sobre la información específica que debe figurar en las distintas páginas y secciones.

## [INTRODUCTION/INTRODUCCIÓN]{style="color:purple;"} {#sec-app2-intro}

## [FIELD IDENTIFICATION/IDENTIFICACIÓN EN EL CAMPO]{style="color:purple;"} {#sec-app2-id}

-   @sec-app3-id-intro
-   @sec-app3-id-id
-   @sec-app3-id-sssum
-   @sec-app3-id-ss

## [PLUMAGES, MOLTS, AND STRUCTURE/PLUMAJES, MUDAS Y ESTRUCTURA]{style="color:purple;"} {#sec-app2-plumages}

-   @sec-app3-plumages-plumages
    -   Natal Down/Plumaje natal
    -   Juvenile/Juvenil
    -   Adult/Adultos
-   @sec-app3-plumages-molts
-   @sec-app3-plumages-bare
    -   Bill and Gape/Pico y comisura
    -   Iris/Iris
    -   Facial Skin/Piel del rostro
    -   Tarsi and Toes/Tarsos y dedos
-   @sec-app3-plumages-measurements
    -   Linear Measurements/Medidas lineales
    -   Mass/Masa
    -   Wing Area, Wing Aspect Ratio, and Wing Loading/Superficie alar, relación de aspecto alar y carga alar

## [SYSTEMATICS/SISTEMÁTICA]{style="color:purple;"} {#sec-app2-systematics}

-   @sec-app3-systematics-history
-   @sec-app3-systematics-geographic
-   @sec-app3-systematics-subspecies
-   @sec-app3-systematics-related
-   @sec-app3-systematics-hybrid
-   @sec-app3-systematics-fossils

## [DISTIBUTION/DISTRIBUCIÓN]{style="color:purple;"} {#sec-app2-distribution}

-   @sec-app3-distribution-intro
    -   Breeding Range/Área de reproducción
    -   Nonbreeding Range/Área de distribución no reproductora
    -   Elevational Range/Rango de elevación
    -   Introduced Range/Rango donde está introducida
    -   Extralimital Records/Registros fuera del límite de distribución
-   @sec-app3-distribution-historical

## [HABITAT/HÁBITAT]{style="color:purple;"} {#sec-app2-habitat}

-   @sec-app3-habitat-intro
    -   Habitat Keywords/Palabras clave del habitat
-   @sec-app3-habitat-general
-   @sec-app3-habitat-breeding
-   @sec-app3-habitat-migration
-   @sec-app3-habitat-nonbreeding

## [MOVEMENTS AND MIGRATION/MOVIMIENTOS Y MIGRACIÓN]{style="color:purple;"} {#sec-app2-movements}

-   @sec-app3-movements-intro
-   @sec-app3-movements-dispersal
    -   Natal Philopatry and Dispersal/Filopatría natal y dispersión
    -   Adult Fidelity to Breeding Site and Dispersal/Fidelidad de los adultos al lugar de cría y dispersión
    -   Fidelity to Nonbreeding Home Range/Fidelidad al área de campeo no reproductora
-   @sec-app3-movements-nomigratory
-   @sec-app3-movements-overview
-   @sec-app3-movements-timing
    -   Postbreeding/Post-reproductivos
    -   Prebreeding/Pre-reproductivos
-   @sec-app3-movements-behavior
    -   Daily Timing of Migration/Momento diario de la migración
    -   Fidelity to Migratory Routes/Fidelidad a las rutas migratorias 
    -   Fidelity to Stopover Sites/Fidelidad a las escalas migratorias
    -   Movement During Stopover/Comportamiento durante la parada
    -   Duration of Stopover Period/Duración de la escala
    -   Duration of Migratory Period/Duración del periodo migratorio
-   @sec-app3-movements-control

## [DIET AND FORAGING/DIETA Y ALIMENTACIÓN]{style="color:purple;"} {#sec-app2-diet}

-   @sec-app3-diet-intro
-   @sec-app3-diet-feeding
    -   Microhabitat for Foraging/Microhábitat para la alimentación
    -   Food Capture and Consumption/Captación y consumo de alimentos
-   @sec-app3-diet-diet
    -   Major Food Items/Principales alimentos
    -   Quantitative Analysis/Análisis cuantitativo
-   @sec-app3-diet-storage
-   @sec-app3-diet-nutrition
-   @sec-app3-diet-metabolism
-   @sec-app3-diet-drinking

## [SOUNDS AND VOCAL BEHAVIOR/SONIDOS Y CONDUCTA VOCAL]{style="color:purple;"} {#sec-app2-sounds}

-   @sec-app3-sounds-intro
-   @sec-app3-sounds-vocalizations
    -   Vocal Development/Desarrollo vocal
    -   Vocal Array/Conjunto vocal
        -   Songs/Cantos
        -   Calls/Lllamadas
    -   Geographic Variation/Variación geográfica
    -   Phenology/Fenología
    -   Daily Pattern of Vocalizing/Patrón diario de vocalización
    -   Places of Vocalizing/Lugares de vocalización
    -   Sex Differences/Diferencias entre sexos
    -   Repertoire and Delivery of Songs/Repertorio y ejecución de canciones
    -   Social Context and Presumed Functions of Vocalizations/Contexto social y supuestas funciones de las vocalizaciones
-   @sec-app3-sounds-nonvocal

## [BEHAVIOR/CONDUCTA]{style="color:purple;"} {#sec-app2-behavior}

-   @sec-app3-behavior-intro
-   @sec-app3-behavior-locomotion
    -   Posture and Body Movements/Postura y movimientos corporales
    -   Walking, Running, Hopping, and Climbing/Caminar, correr, saltar y trepar
    -   Flight/Vuelo
    -   Swimming and Diving/Natación y buceo
-   @sec-app3-behavior-self
    -   Preening, Head Scratching, Stretching, Sunbathing, Bathing, and Anting/Acicalarse, rascarse la cabeza, estirarse, tomar el sol, bañarse y hormiguear
    -   Roosting and Sleeping/Descanso y sueño
    -   Daily Time Budget/Presupuesto diario
-   @sec-app3-behavior-agonistic
    -   Physical and Communicative Interactions/Interacciones físicas y comunicativas
    -   Territorial Behavior/Comportamiento territorial
-   @sec-app3-behavior-sexual
    -   Mating System and Operational Sex Ratio/Sistema de apareamiento y proporción de sexos operativos
    -   Courtship, Copulation, and Pair Bond/Cortejo, cópula y vínculo de pareja
    -   Extrapair Mating Behavior/Paternity/Comportamiento de apareamiento extrapareja/paternidad
-   @sec-app3-behavior-social
    -   Degree of Sociality/Grado de socialidad
    -   Play/Juego
    -   Nonpredatory Interspecific Interactions/Interacciones interespecíficas no depredadoras
-   @sec-app3-behavior-predation
    -   Types of Predators/Tipos de depredadores
    -   Manner of Depredation/Forma de depredación
    -   Response to Predators/Respuesta a los depredadores

## [BREEDING/REPRODUCCIÓN]{style="color:purple;"} {#sec-app2-breeding}

-   @sec-app3-breeding-intro
-   @sec-app3-breeding-phenology
    -   Pair Formation/Formación de parejas
    -   Nest Building/Construcción de nidos 
    -   First Brood/Primera nidada
    -   Second/Later Broods/Segunda nidada
-   @sec-app3-breeding-site
    -   Selection Process/Proceso de selección
    -   Site Characteristics/Características del sitio
-   @sec-app3-breeding-nest
    -   Construction Process/Proceso de construcción
    -   Structure and Composition/Estructura y composición 
    -   Dimensions/Dimensiones
    -   Microclimate/Microclima
    -   Maintenance or Reuse of Nests/Mantenimiento o reutilización de nidos
    -   Nonbreeding Nests/Nidos no reproductores
-   @sec-app3-breeding-eggs
    -   Shape/Forma
    -   Size/Tamaño
    -   Mass/Masa
    -   Eggshell Thickness/Espesor de la cáscara de huevo 
    -   Color and Surface Texture/Color y textura de la superficie
    -   Clutch Size/Tamaño de la nidada
    -   Egg Laying/Puesta de huevos
-   @sec-app3-breeding-incubation
    -   Onset of Broodiness and Incubation in Relation to Laying/Inicio de la cría e incubación en relación con la puesta
    -   Incubation Patches/Parches de incubación 
    -   Incubation Period/Periodo de incubación 
    -   Parental Behavior/Comportamiento de los padres 
    -   Hardiness of Eggs Against Temperature Stress/Resistencia de los huevos al estrés térmico
-   @sec-app3-breeding-hatching
    -   Preliminary Events and Vocalizations/Actos Preliminares y Vocalizaciones
    -   Shell Breaking and Emergence/Rotura y aparición del caparazón
    -   Hatching Synchrony/Sincronía de eclosión
    -   Parental Assistance and Disposal of Eggshells/Asistencia parental y eliminación de cáscaras de huevo
-   @sec-app3-breeding-young
    -   Condition at Hatching/Estado en el momento de la eclosión
    -   Growth and Development/Crecimiento y desarrollo
    -   Sex Ratios and Sex Allocation/Proporciones y asignación por sexo
-   @sec-app3-breeding-parental
    -   Brooding/Cría
    -   Feeding/Alimentación
    -   Nest Sanitation/Saneamiento de nidos
    -   Nest Defense/Defensa del nido
    -   Carrying of Eggs or Young/Transporte de huevos o crías
-   @sec-app3-breeding-cooperative
-   @sec-app3-breeding-parasitism
    -   Brood Parasitism of Conspecifics/Parasitismo de crías de congéneres
    -   Brood Parasitism of Other Species/Parasitismo de cría de otras especies
    -   Brood Parasitism by Other Species/Parasitismo de cría por otras especies
        -   Identity of the Parasitic Species/Identidad de la especie parasitaria
        -   Frequency of Occurrence/Frecuencia de aparición
        -   Seasonal or Geographic Variation/Variación estacional o geográfica
        -   Timing of Laying in Relation to Host's Laying/Momento de la colocación en relación con la colocación del anfitrión
        -   Response to Parasitic Female, Eggs, or Nestlings/Respuesta a hembras, huevos o polluelos parasitados
        -   Effects of Parasitism on Host/Efectos del parasitismo en el hospedador
        -   Success of Parasite with This Host/Éxito del parásito con este huésped
-   @sec-app3-breeding-fledgling
    -   Departure from the Nest/Salida del nido
    -   Growth/Crecimiento 
    -   Association with Parents or Other Young/Asociación con padres u otros jóvenes
    -   Ability to Get Around, Feed, and Care for Self/Capacidad para desplazarse, alimentarse y cuidar de sí mismo
    -   Behavior After Independence/Comportamiento tras la independencia

## [DEMOGRAPHY AND POPULATIONS/DEMOGRAFÍA Y POBLACIONES]{style="color:purple;"} {#sec-app2-demography}

-   @sec-app3-demography-intro
-   @sec-app3-demography-measures
    -   Age at First Breeding/Edad de la primera cría
    -   Intervals Between Breeding/Intervalos entre crías
    -   Clutch Size and Number of Clutches per Season/Tamaño de la puesta y número de puestas por temporada
    -   Annual and Lifetime Reproductive Success/Éxito reproductivo anual y vitalicio 
    -   Number of Broods Normally Reared per Season/Número de crías criadas normalmente por temporada 
    -   Proportion of Total Females That Rear at Least One Brood to Nest Leaving/Proporción del total de hembras que crían al menos una cría hasta la salida del nido
-   @sec-app3-demography-life
-   @sec-app3-demography-pathogens
    -   Pathogens/Patógenos
    -   Parasites/Parásitos
-   @sec-app3-demography-mortality
    -   Exposure/Exposición
    -   Predation/Depredación
    -   Disease/Enfermedad
    -   Direct Human Impacts/Impactos humanos directos
-   @sec-app3-demography-spatial
    -   Individual Distance/Distancia individual
    -   Territory Size/Tamaño del territorio
    -   Home Range Size/Tamaño del área de distribución
    -   Density/Densidad
-   @sec-app3-demography-status
    -   Numbers/Números
    -   Trends/Tendencias
-   @sec-app3-demography-regulation

## [CONSERVATION AND MANAGEMENT/CONSERVACIÓN Y MANEJO]{style="color:purple;"} {#sec-app2-conservation}

-   @sec-app3-conservation-status
    -   Global Assessment/Evaluación global
    -   Regional Assessments/Evaluaciones regionales
-   @sec-app3-conservation-effects
    -   Habitat Loss and Degradation/Pérdida y degradación del hábitat
    -   Climate Change/Cambio climático
    -   Noise and Light Pollution/Contaminación acústica y lumínica
    -   Effects of Invasive Species/Efectos de las especies invasoras
    -   Hunting, Trapping, and Bycatch/Caza, captura con trampas y capturas incidentales
    -   Pesticides and Other Contaminants/Toxics/Plaguicidas y otros contaminantes/tóxicos
    -   Collisions with Structures or Objects/Colisiones con estructuras u objetos
    -   Other Human or Research Impacts/Otros impactos humanos o de investigación
-   @sec-app3-conservation-management
    -   Conservation Areas/Áreas protegidas
    -   Conservation Measures and Habitat Management/Medidas de conservación y gestión de hábitats
    -   Effectiveness of Measures/Eficacia de las medidas

## [RELATIONSHIP WITH HUMANS/RELACIONES CON EL SER HUMANO]{style="color:purple;"} {#sec-app2-humans}

-   @sec-app3-humans-intro
-   @sec-app3-humans-vernacular
-   @sec-app3-humans-cultural
    -   Early History/Historia temprana
    -   Presence in Folklore, Religion, and Symbolism/Presencia en el folclore, la religión y el simbolismo
    -   Depictions in Media/Representaciones en los medios de comunicación
    -   Public Perception/Percepción pública
-   @sec-app3-humans-economic
    -   Use by Humans/Uso humano
    -   Harm Inflicted by Focal Species/Daños infligidos por especie focal
    -   Aviculture and Domestication/Avicultura y domesticación
    -   Use as a Research Model/Utilización como modelo de investigación

## [PRIORITIES FOR FUTURE RESEARCH/PRIORIDADES PARA LA INVESTIGACIÓN FUTURA]{style="color:purple;"} {#sec-app2-priorities}

## [OTHER/OTROS]{style="color:purple;"} {#sec-app2-other}

## [ACKNOWLEDGMENTS/AGRADECIMIENTOS]{style="color:purple;"} {#sec-app2-acknowledgments}

## [ABOUT THE AUTHOR(S)/SOBRE LOS/LAS AUTORES/AS]{style="color:purple;"} {#sec-app2-authors}