---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Apéndice 3: Descripción de las páginas, secciones y subsecciones de la ficha {#sec-app3 .unnumbered}

En general, cuando no pueda encontrar información sobre un tema determinado, rellene esa sección con "Information needed" o "Information is needed" (no con "No hay información", "No hay datos" o "No se sabe nada"). Si no buscó bibliografía para una sección o secciones, puede anotar "This section was not evaluated". Para secciones o subsecciones en las que puede que nunca haya información relevante para una especie porque el comportamiento no se aplica (por ejemplo, Nidos no reproductores, Cría cooperativa o Parasitismo de cría por otras especies), utilice "Not reported".

Por favor, evite utilizar las palabras "reciente" o "recientemente" en las fichas. Se trata de términos relativos, y algunas fichas se actualizan con más frecuencia que otras, lo que puede inducir a error en algunos casos. Siempre que sea posible, indique el año correspondiente (o un intervalo de años).

## [INTRODUCTION/INTRODUCCIÓN]{style="color:purple;"} {#sec-app3-intro}

Todos las fichas deben incluir una introducción concisa de 1 a 5 párrafos. Presente su especie al lector, haciendo hincapié en los aspectos que la hacen única, incluyendo (según proceda) la sistemática, el aspecto, la distribución, la migración, el hábitat, la alimentación, la reproducción, el tamaño de la población y la conservación. Las mejores introducciones no se limitan a resumir datos objetivos, sino que buscan la legibilidad sin dejar de reflejar los aspectos científicos de la ficha. Las descripciones del aspecto deben ser concisas y, por lo general, no constituyen el tema central de la introducción. Las descripciones del área de distribución deben ser generales (por ejemplo, "se da en los bosques montanos de Tanzania y Kenia, normalmente entre 2.600 y 3.400 m"). Por lo general, las introducciones no incluyen referencias citadas, a menos que se incluya una cita o se presente información que no esté citada en ninguna otra parte de la ficha. Algunas fichas han resumido aspectos de la especie que están bien estudiados, proporcionando citas, especialmente al final de la Introducción.

## [FIELD IDENTIFICATION/IDENTIFICACIÓN EN EL CAMPO]{style="color:purple;"} {#sec-app3-id}

### [Field Identification (introduction)/Identificación en el campo (introducción)]{style="color:blue;"} {#sec-app3-id-intro}

Si el artículo de identificación es especialmente largo, resuma los aspectos más importantes de la identificación de la especie, incluidas las marcas de campo esenciales. Una lista con viñetas puede ser adecuada en este caso. Evite las citas en esta sección.

### [Identification/Identificación]{style="color:blue;"} {#sec-app3-id-id}

Proporcione una descripción resumida general de los principales puntos de identificación de adultos y juveniles por sexo (cuando puedan determinarse la edad y el sexo). Los términos "adultos" o "aves de primer ciclo" pueden utilizarse aquí, pero asegúrese de incluir el plumaje o plumajes entre paréntesis a continuación de los términos, como se indica en Plumajes. Se puede utilizar "juveniles" para las aves de plumaje juvenil, sin necesidad del término adicional. Incluya descripciones separadas para los adultos en Plumaje básico definitivo y Plumaje alternativo definitivo si difieren (o indique que son similares si se da un plumaje alternativo y es similar en apariencia al plumaje básico). Una vez descritos los adultos de cada sexo y plumaje, describa brevemente los plumajes juvenil, formativo (normalmente) y todos los demás plumajes predefinidos en una frase cada uno. Cuando proceda, puede incluirse brevemente una discusión sobre subespecies, morfos notables o variantes de color, o poblaciones únicas.

El diagnóstico debe ser más científico que el de una guía de campo, pero también debe ser fácil de leer y digerir por los neófitos. Destaque las características de tamaño, forma, color o estructura que puedan reconocerse en las aves sobre el terreno. Indique la longitud total (general) y la masa de las aves vivas, acompañadas de una indicación del tamaño relativo en comparación con especies afines, si resulta útil para la identificación (por ejemplo, "un colibrí de tamaño mediano"). Indique las diferencias de longitud, masa o plumaje entre machos y hembras. Esta sección debe ser concisa. Las descripciones detalladas del tamaño, el color, etc., se pedirán en otras secciones. Esta sección no requiere subsecciones.

### [Similar Species Summary/Resumen sobre especies similares]{style="color:blue;"} {#sec-app3-id-sssum}

Si la sección de Especies Similares tiene una extensión considerable (más de 5 párrafos), utilice el Resumen de Especies Similares para resumir brevemente las cuestiones clave. No obstante, evite demasiadas repeticiones con Especies Similares.

### [Similar Species/Especies similares]{style="color:blue;"} {#sec-app3-id-ss}

Resuma los principales puntos de identificación que distinguen a su especie de otras especies estrechamente emparentadas o similares. Cite cualquier artículo reciente en el que se exponga detalladamente cómo distinguir su especie de especies similares sobre el terreno, pero en principio, no incluya referencias a guías de campo estándar. La identificación entre subespecies (o morfos, variantes, etc.) también puede incluirse brevemente aquí, aunque cualquier descripción detallada del aspecto de las subespecies debe incluirse en la sección Subespecies de la página Sistemática. Esta sección debe ser concisa. Las descripciones detalladas de tamaño, color, etc., se incluirán en otras secciones. No se necesitan subsecciones para esta sección.

## [PLUMAGES, MOLTS, AND STRUCTURE/PLUMAJES, MUDAS Y ESTRUCTURA]{style="color:purple;"} {#sec-app3-plumages}

### [Plumages/Plumajes]{style="color:blue;"} {#sec-app3-plumages-plumages}

Aquí se describen los detalles de cada plumaje por edad y estación. Base su descripción en una subespecie, normalmente la subespecie nominal, o la subespecie más extendida si no hay suficiente información para la nominal. La variación entre subespecies debe limitarse a la sección Variación geográfica de la página Sistemática. Indique si las descripciones del plumaje se aplican a todas las poblaciones (por ejemplo, para las especies monotípicas o aquellas en las que las subespecies no varían mucho en el aspecto del plumaje). Si procede, incluya un análisis de los distintos morfos. Incluya la frase siguiente en todos las fichas: "Véase Mudas para la terminología sobre mudas y plumaje".

Comience cada sección con cualquier información fundamental sobre la estructura, incluyendo el número de primarias, secundarias y rectrices en la especie; la numeración de las plumas de vuelo; si el ave es diastáxica; y cualquier forma especial en la que la morfología de un ave estándar esté modificada en esta especie (por ejemplo, "las alas son redondeadas, con p6 la primaria más larga"). Remítase a otras fichas BOW revisadas para la numeración de las plumas y cómo describirla. Incluya una frase sobre si los sexos difieren (dentro de cada plumaje, si procede) y en qué plumaje o plumajes se alcanza la apariencia definitiva.

La terminología de la muda y el plumaje suele seguir la de Humphrey y Parkes (1959), modificada por Howell et al. (2003). Describa cada uno de los plumajes que aparecen en el orden en que se producen en el desarrollo, es decir, desde el Plumaje Natal hasta el Plumaje Básico Definitivo (y los Plumajes Alternos, si los hay). Las subsecciones incluyen el plumaje natal, el plumaje juvenil (primer plumaje básico), el plumaje formativo (presente en muchas especies), el primer plumaje alternativo (si está presente), el plumaje básico definitivo y el plumaje alternativo definitivo (si está presente). El epígrafe "Primer plumaje y plumaje alternativo definitivo" puede utilizarse si son similares entre sí o a los plumajes básico formativo y definitivo; si se utiliza, indique que los criterios de envejecimiento figuran en los plumajes básico formativo y definitivo. Los subapartados que serán necesarios para algunas especies, pero no para todas, incluyen Segundo plumaje básico, Segundo plumaje alternativo, Tercer plumaje básico, etc., hasta Cuarto o Quinto plumajes básicos para algunas gaviotas y águilas y hasta Octavo o Noveno plumajes básicos para algunos albatros y fragatas. Pueden utilizarse encabezamientos como "Plumajes Básicos Segundo y Definitivo" o "Plumajes Básicos Cuarto a Sexto" cuando puedan identificarse algunas aves pero no todas o haya solapamiento en el plumaje en el que se alcanza la apariencia definitiva. Por favor, tenga en cuenta que el término "Primer Plumaje Básico" debe evitarse generalmente en el texto; en su lugar debe utilizarse "Plumaje Juvenil". El primer plumaje básico se utiliza en los títulos sólo para mayor claridad. Para otros plumajes poco utilizados, como los plumajes formativos suplementarios y auxiliares, véase Mudas (más abajo). Los títulos incluyen "**Hembra**" y "**Macho**" (en este orden) en negrita si estos plumajes difieren sustancialmente en apariencia. Si sólo difieren sutilmente o en promedio, la diferencia puede resumirse en una frase, sin necesidad de encabezamientos por sexo.

Enumere las referencias con descripciones detalladas (si las hay) en las que se basan los plumajes y la determinación de la edad. En general, pueden enumerarse una vez al principio de la ficha o a continuación de cada plumaje.

Deben evitarse términos como "plumaje de polluelo", "plumaje de volantón", "plumaje inmaduro" y "plumaje adulto". Reconocemos, sin embargo, que el uso de estos descriptores puede ser apropiado en algunas situaciones, especialmente cuando hay retraso en la maduración del plumaje. Del mismo modo, también debe evitarse el uso de términos/abreviaturas de anillamiento como "año de eclosión/HY", "después del año de eclosión/AHY" o "tercer año" para referirse a los plumajes. Ya no utilizamos el término "juvenil"; por favor, utilice "juvenil" como sustantivo y como adjetivo. 

Las descripciones más completas del plumaje deben ser las del Plumaje Básico Definitivo (macho y hembra por separado o una sola descripción si los sexos son similares). A continuación, compare los demás plumajes con el Plumaje Básico Definitivo. En algunos casos, basta con señalar unas pocas diferencias, mientras que en otros (a menudo el plumaje juvenil para las plumas del cuerpo), pueden ser necesarias descripciones más completas cuando el aspecto difiere sustancialmente del plumaje básico definitivo. Las diferencias en las plumas de las alas y de la cola suelen ser leves y a menudo pueden transmitirse de forma comparativa. Indique fechas representativas, si es posible, para cada plumaje en el texto. Pueden darse intervalos de meses para abarcar un plumaje desde fresco a desgastado, por ejemplo, "El Plumaje Básico Definitivo se da principalmente de septiembre a agosto".

Para cada plumaje, describa el color general y el diseño del plumaje y, a continuación, los detalles significativos de color, dibujo o textura de cada pluma. Proceda en el orden siguiente: partes superiores (cabeza, nuca, espalda, rabadilla y cola); rasgos faciales (lores, supercilio, línea ocular, auriculares y lado de la cabeza); alas superiores, generalmente en el orden de coberteras supra-alares (menores, medianas y mayores, según sea necesario), terciarias, secundarias y primarias; y partes inferiores (barbilla, garganta, pecho, abdomen, región ventral, coberteras infracaudales y coberteras infra-alares). Describa brevemente el patrón de la cabeza, incluidas las rayas subauriculares y malares, si están presentes. En algunos casos, puede seguirse un orden diferente, por ejemplo, si los lados de la cabeza, el cuello y la garganta son todos de un mismo color. Siga la terminología del Glosario ([Apéndice 6](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.1302m92)). Distinga entre regiones de la pluma si es necesario hablar de las plumas según el lugar del cuerpo donde nacen. Para los nombres de los tractos de plumas, en paseriformes y no paseriformes con pterilosis similar siga a Clench (1970); en otros no paseriformes siga a Lucas y Stettenheim (1972). 

Intente utilizar términos de color sencillos y de uso extendido, como "marrón grisáceo" (incluya un guión si se utiliza antes del sustantivo al que modifica, por ejemplo, "partes superiores marrón grisáceo" en lugar de "partes superiores marrón grisáceo"). Cuando sea posible, utilice los términos de color en sentido comparativo para describir las diferencias entre plumajes.

La Biblioteca Macaulay puede utilizarse ampliamente para describir plumajes, especialmente cuando no existen otras descripciones (por ejemplo, para muchas especies no norteamericanas). Se pueden establecer filtros para "Juvenil", "Inmaduro" y meses del año para describir plumajes básicos y alternativos, y para "volar" para buscar imágenes de las coberteras superiores e inferiores abiertas y de las plumas de vuelo. En general, es mejor ordenar las imágenes por "Mejor calidad" para encontrar las mejores imágenes en las que basar las descripciones.

### [Molts/Mudas]{style="color:blue;"} {#sec-app3-plumages-molts}

Debe resumir brevemente cualquier variación relevante en las estrategias de muda dentro de la especie. Comience cada sección con un párrafo que describa la estrategia de muda y la terminología utilizada. Incluya la frase: "La terminología de muda y plumaje sigue a Humphrey y Parkes (enlace de referencia), modificada por Howell et al. (enlace de referencia)"; véanse las referencias en las fichas de ejemplo. Luego indique qué estrategia de muda se sigue con una frase como "XXX exhibe una Estrategia Alternativa Compleja (cf. enlaces de referencia), incluyendo mudas prebásicas completas, una muda preformativa parcial a incompleta, y mudas prealternas ausentes a limitadas en ambos grupos de edad (enlaces a citas específicas sobre muda y al diagrama de la carta de muda)". De nuevo, véanse los ejemplos para una redacción diferente. Indique aquí si existe alguna variación geográfica en las estrategias de muda. Generalmente, las estrategias no diferirán, pero el momento y la extensión de las mudas pueden diferir, especialmente para especies con una amplia ocurrencia latitudinal (por ejemplo, poblaciones templadas del norte, tropicales y templadas del sur). Indique si hay alguna variación específica del sexo en las mudas; esto es raro pero ocurre en algunas especies, como las aves acuáticas con plumajes alternos.

Las subsecciones siguen las presentadas en Plumajes e incluyen (en el mismo orden de desarrollo) Muda Prejuvenil (Primera Prebásica), Muda Preformativa (presente en muchas especies), Mudas Prealternativas Primera y Definitiva (si están presentes) y Muda Prebásica Definitiva. Pueden utilizarse otras rúbricas siguiendo este formato para las especies con maduración retardada del plumaje o estrategias más complejas, como se describe en Plumajes. Generalmente, las Mudas Prebásicas Definitivas y Primeras son similares dentro de una especie y deben combinarse aquí, más que en Plumajes, que pueden diferir entre edades. Unas pocas especies tienen tres mudas y plumajes dentro de un ciclo y necesitarán encabezamientos para Primeras y/o Definitivas Mudas Presuplementarias o Muda Preformativa Auxiliar (que antes se denominaba primera muda presuplementaria). En algunos casos, se necesitarán rúbricas separadas bajo Plumajes para describir la apariencia después de estas mudas. El editor de plumajes/mudas puede ayudar a decidir cómo presentar dichas mudas y plumajes en las fichas BOW. A menudo, no está claro si ciertas mudas ocurren en una especie o no, y esta incertidumbre puede expresarse en el párrafo superior bajo mudas.

En cada epígrafe, describa el alcance de la muda como uno o más de los siguientes: "ausente" si ninguna pluma puede ser reemplazada en algunos individuos; "limitada" si algunas pero no todas las plumas del cuerpo son reemplazadas; "parcial" si la mayoría o todas las plumas del cuerpo, algunas o todas las coberteras supra-alares, y a menudo 1-3 terciarias y/o 1-2 rectrices centrales son reemplazadas; "incompleta" si algunas pero no todas las primarias, secundarias distintas de las terciarias, y/o rectrices distintas del par central son reemplazadas; o "completa" si todas las plumas son reemplazadas. A menudo se necesita más de una categoría para describir las mudas, por ejemplo, mudas prealternas que son "ausentes a limitadas", mudas preformativas que son "parciales a incompletas", o mudas prebásicas que son "incompletas a completas" (por ejemplo, para especies con patrones de Staffelmauser). A continuación, indique el momento (si se conoce) y dé detalles sobre la variación en la extensión, incluyendo cuántas coberteras alares o plumas de vuelo pueden ser reemplazadas (de nuevo, si se conoce). Para las especies fuera de Norteamérica o Europa, la referencia a las imágenes de la Macaulay Library a menudo puede ayudar a determinar esto cuando la extensión de la muda no se describe en la literatura. Bajo Muda Prebásica Definitiva, describa la secuencia en la cual las plumas de vuelo son reemplazadas, a menudo algo como "Las primarias son reemplazadas distalmente desde p1 hasta p10, las secundarias bilateralmente desde el segundo tercio y proximalmente desde s1, y las rectrices generalmente distalmente a cada lado de la cola, aunque pueden ocurrir excepciones". Estas secuencias tienden a ser muy fijas dentro de las familias de aves y se puede suponer que siguen para las especies en las que se desconocen. No utilice los términos "descendente", "ascendente", "centrífuga" o "centrípeta" para describir las secuencias de muda. Resuma el calendario y el alcance de las mudas en el diagrama del ciclo anual (comunique al personal de BOW si desea crear o introducir cambios en esta figura).

### [Bare Parts/Partes descubiertas]{style="color:blue;"} {#sec-app3-plumages-bare}

Describa la coloración, el tamaño y la forma de estas partes desde el nido hasta la edad adulta, relacionando los cambios con la edad. En general, es mejor describir la edad en términos de meses que de plumajes, ya que el cambio de plumaje es independiente del cambio de color de las partes desnudas. Describa el desarrollo progresivo o estacional de estructuras como las crestas oculares de algunos urogallos y las placas del pico de los procelariformes y frailecillos. Indique los colores de aves vivas o recién muertas, ya sea a partir de la observación directa o de notas en las etiquetas de los especímenes. No se fíe necesariamente de las pieles de museo o de las fotografías en color para conocer las sutilezas del color.

### [Measurements/Medidas]{style="color:blue;"} {#sec-app3-plumages-measurements}

Utiliza unidades métricas siempre que sea posible, y convierte los valores que no utilicen unidades métricas. Siga las instrucciones sobre estadísticas (véase [el Apéndice 4](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.39kk8xu)). En situaciones limitadas, pueden incluirse unidades imperiales junto con unidades métricas cuando resulte útil. Tanto para las medidas lineales como para las masas, enumere las medidas de las hembras antes que las de los machos. También puede presentarse la variación por edad, subespecie o región geográfica. Si es posible, comente la variación clinal o haga referencia a un artículo en el que se trate el tema.

\
Si realiza usted mismo las mediciones, asegúrese de hacerlo de acuerdo con las orientaciones normalizadas que figuran a continuación para que sean repetibles. Clasifique los datos por sexo, edad, población/subespecie o área geográfica cuando sea posible. Indique la media, la DE o SE y el intervalo cuando sea posible. Evite utilizar mediciones de guías de campo porque es probable que sean secundarias o inexactas. Si el método normal de medición de su especie difiere de los diagnósticos que figuran a continuación, siga el método utilizado normalmente, **pero especifique cuál es**. Si una fuente no especifica cómo se tomó una medida, indique que el método utilizado fue "no especificado".

**Linear Measurements/Medidadas lineales**

Agrupe las medidas (en mm) en los siguientes epígrafes. En la mayoría de los casos, utilice encabezamientos en negrita y en línea, como los que se muestran a continuación (por ejemplo, en el caso de [*Tyrannus vociferans*](https://birdsoftheworld.org/bow/species/caskin/cur/appearance#meas)). Sin embargo, si se necesitan varios párrafos bajo cada encabezamiento, utilice el estilo de texto Encabezamiento 2 (para un ejemplo, véase [*Geositta rufipennis*](https://birdsoftheworld.org/bow/species/rubmin1/cur/appearance#meas)).

**Longitud total.** Desde la punta del pico hasta la punta de la cola. Suele medirse a partir de un ejemplar de museo.

**Longitud del ala.** Desde la articulación carpal hasta la punta de la primaria más larga de un ala plegada en su posición natural. A partir de un espécimen de museo o de un ave viva. Especificar si se da la longitud del ala sin aplanar o aplanada.

**Longitud de la cola.** Desde el punto entre el par central de rectrices donde emergen de la piel hasta la punta de la rectriz más larga.

**Longitud del pico.** Se suelen utilizar varias medidas de pico, por lo que le rogamos que especifique qué medida se comunica (o indique que no se especifica en la fuente original). Si usted mismo toma las medidas, BOW prefiere el culmen expuesto (la cuerda desde el borde de las plumas de la frente hasta la punta de la mandíbula). Otras medidas comunes del pico incluyen la cuerda desde el borde anterior de la fosa nasal, desde la charnela naso-frontal del cráneo, o desde el borde de la cera hasta la punta de la mandíbula.

**Longitud del tarso.** Diagonal desde la mitad de la articulación del tobillo (detrás) hasta la mitad de la articulación entre el tarso y el dedo medio (delante).

Indique (o dé referencias de) otras medidas externas o internas de que pueda disponer, especialmente las que puedan ser útiles para la identificación de la especie, la edad o el sexo, por ejemplo, la envergadura, la anchura de las alas, la distancia entre la punta del ala plegada y la punta de la cola, la distancia entre la punta del ala plegada y la punta de las coberteras infracaudales o la distancia entre la punta del ala plegada y la punta de las rémiges secundarias. Inserte dichas medidas adicionales en un orden lógico entre los encabezamientos anteriores (por ejemplo, coloque "Longitud de la cabeza" antes de "Longitud del pico").

**Mass/Masa**

Indique la masa total (en g), clasificada cuando sea posible por sexo, edad, época del año, reproducción, migración, población, subespecie, etc. Indique la localidad y las estadísticas básicas (media, DE o SE y rango). Si esta información existe, puede añadir masas de órganos internos publicadas.

## [SYSTEMATICS/SISTEMÁTICA]{style="color:purple;"} {#sec-app3-systematics}

### [Systematics History/Historia de la sistemática]{style="color:blue;"} {#sec-app3-systematics-history}

Esta sección debe tratar de abarcar la historia taxonómica de la especie, centrándose principalmente en las publicaciones desde el volumen correspondiente de la Lista de Peters, incluyendo cualquier discusión relevante sobre sinonímias o debates sobre la validez de los nombres científicos. Esta es también la sección en la que discutir cualquier dato que pueda entrar en conflicto con la taxonomía actual de la especie o del género, por ejemplo, para destacar investigaciones genéticas o de otro tipo que puedan, en el futuro, llevar a disposiciones diferentes. Mencione, cuando proceda, las discrepancias taxonómicas a nivel de especie entre las cuatro principales listas mundiales (las diferencias en el enfoque subespecífico deben incluirse en Subespecies, más adelante). Si la especie ha sido recientemente dividida o agrupada, esta es también la sección en la que se debe discutir brevemente de qué taxón/taxa fue dividida, o con qué taxón/taxa fue agrupada, así como cualquier dato relevante que haya llevado al cambio.

**Para las especies monotípicas**, esta sección es el lugar para registrar la combinación original (es decir, el nombre original del género y de la especie cuando se describió el taxón por primera vez), el autor y el año de publicación, el lugar (libro/revista, incluidos los números de volumen y página) de publicación, la localidad tipo y la información relativa al espécimen o especímenes tipo (recolector, fecha de recolección, museo y referencia al catálogo tipo). (**Para las especies politípicas**, esta información irá en la sección Subespecies). En los casos en que la descripción original esté disponible en línea en una URL potencialmente estable (por ejemplo, Biodiversity Heritage Library), es útil enlazar con ella. Muchos catálogos tipo de museos están disponibles en Biodiversity Heritage Library, pero no todos, y algunas grandes instituciones aún carecen de tales obras, o sólo están parcialmente completas. A continuación encontrará ejemplos de formatos. Cuando sea posible/adecuado, presente también la misma información para cualquier sinónimo bien reconocido. También es útil enlazar con la página de Wikipedia (u otra fuente razonablemente permanente) del coleccionista. Incluya los años de vida de la persona si los conoce.

Peters [(](https://www.biodiversitylibrary.org/bibliography/14581)https://www.biodiversitylibrary.org/bibliography/14581) es un buen punto de partida para este tipo de datos. El Richmond Index [(](https://zoonomen.net/cit/RI/SP/RIspTotal.html)https://zoonomen.net/cit/RI/SP/RIspTotal.html) también puede ser útil para identificar detalles bibliográficos y, a veces, el paradero del material tipo.

Mencione los arreglos genéricos alternativos propuestos para su especie, pero céntrese en las modificaciones recientes promovidas por los datos de secuenciación molecular, en lugar de intentar proporcionar una historia genérica completa. Como resultado, puede ser inevitable cierto solapamiento con el contenido de Especies afines. Las historias genéricas están a menudo disponibles a través de catálogos clave como Peters, Sharpe's Catalogue of the Birds of the British Museum, y, sólo para el hemisferio occidental, Cory y Hellmayr, Ridgway, etc., por lo que es posible que desee proporcionar enlaces a una o más de estas obras.

**Nota:** Si desea incluir información sobre nombres científicos que no figure en La Clave de Nombres Científicos (disponible haciendo clic en el icono "i" situado junto al nombre de la especie en la parte superior de la página), añádala a la sección Historia de la sistemática.

**Ejemplos de cómo citar nombres y escribir datos:**

1.  **Caso sencillo (i)**

***Dicaeum formosum*** [Ogilvie-Grant, 1912, Bulletin of the British Ornithologists' Club](https://www.biodiversitylibrary.org/item/100931#page/139/mode/1up) 29:109.-Mt. Arizan, 7.000 pies, Taiwan.

El holotipo, un macho adulto recogido por Walter Goodfellow en marzo de 1912, se conserva en el Museo de Historia Natural de Tring (NHMUK 1913.1.29.55) ([20](https://birdsoftheworld.org/bow/species/fibflo1/cur/references#REF181256)).

2.  **Caso sencillo (ii) (cómo añadir información que no figura en la descripción original: enciérrela entre corchetes; en este ejemplo, para aclarar el paradero de la localidad tipo)**

***Dicaeum ignipectus dolichorhynchum*** [Deignan, 1938, Proceedings of the Biology Society of Washington](https://www.biodiversitylibrary.org/item/107374#page/119/mode/1up) 51:97.-suma de Khao Nom Plu \[07°35′ N, 99°50′ E\], 3.000 pies, provincia de Trang, Tailandia peninsular.

El holotipo, un macho adulto recogido por [el Dr. W. L. Abbott](https://en.wikipedia.org/wiki/William_Louis_Abbott) el 26 de febrero de 1897, se conserva en el Museo Nacional de Historia Natural, Smithsonian Institution, Washington, D.C. (USNM 160382) ([32](https://birdsoftheworld.org/bow/species/fibflo1/cur/references#REF15915)).

3.  **Posibles dudas sobre el tipo de material/fecha**

**(a) *Dryobates subcirris*** [Stejneger, 1886, Proceedings of the United States National Museum](https://www.biodiversitylibrary.org/item/32555#page/127/mode/1up) 9:113.-Sapporo, Hokkaido, Japón.

El holotipo, un macho adulto recolectado [por Thomas Wright Blakiston (1832-1891)](https://en.wikipedia.org/wiki/Thomas_Blakiston) en noviembre de 1881, se conserva en el Museo Nacional de Historia Natural, Smithsonian Institution, Washington, D.C. (USNM 96000) ([54](https://birdsoftheworld.org/bow/species/whbwoo1/cur/references#REF15915), [38](https://birdsoftheworld.org/bow/species/whbwoo1/cur/references#REF206875)). Kuroda ([30](https://birdsoftheworld.org/bow/species/whbwoo1/cur/references#REF201848)) se refirió a otro espécimen (hembra, USNM 96001) en el mismo museo, también recolectado por Blakiston en Sapporo, el 12 de octubre de 1882, como paratetipo, y tanto este último como otra hembra (considerada juvenil por Stejneger pero actualmente catalogada como adulta), recolectada por Pierre L. Jouy en el lago Chinsenji, el 31 de agosto de 1882, están de hecho específicamente referenciados en la descripción original y, por lo tanto, válidamente considerados como tales.

**(b) *Dryobates namiyei*** [Stejneger, 1886, Proceedings of the United States National Museum](https://www.biodiversitylibrary.org/item/32555#page/130/mode/1up) 9:116, [Lámina 2](https://www.biodiversitylibrary.org/item/32555#page/735/mode/1up).-Yamato \[= Prefectura de Nara\], suroeste de Osaka, Honshu, Japón \[34,57° N, 135,77° E\].

El holotipo, un macho adulto recolectado por [Henry James Stovin Pryer (1850-1888)](https://en.wikipedia.org/wiki/Henry_James_Stovin_Pryer) en septiembre de 1876, se conserva en el Museo Nacional de Historia Natural, Smithsonian Institution, Washington, D.C. (USNM 370446) ([54](https://birdsoftheworld.org/bow/species/whbwoo1/cur/references#REF15915), [65](https://birdsoftheworld.org/bow/species/whbwoo1/cur/references#REF200509), [38](https://birdsoftheworld.org/bow/species/whbwoo1/cur/references#REF206875)). El tipo se encontraba originalmente en un museo de Tokio (donde Motoyoshi Namiye, 1854-1918, trabajaba como zoólogo), pero al parecer se conservó en Washington por casualidad ([54](https://birdsoftheworld.org/bow/species/whbwoo1/cur/references#REF15915)). [C. W. Richmond](https://zoonomen.net/cit/RI/SP/Didu/didu00739b.JPG) creía que la lámina que representaba el nuevo taxón se había publicado ya el 8 de julio de 1885, lo que, dado que el nombre científico estaba disponible en la representación, significaría que namiyei debería datarse de un año antes, si esto pudiera confirmarse.

Sinónimos:\
*Dryobates leucotis \[sic\] intermedius* [Kuroda Sr., 1921, Auk](https://sora.unm.edu/sites/default/files/journals/auk/v038n04/p0575-p0582.pdf) 38:580.-Dorogawa, provincia de Yamato \[= prefectura de Nara, 36,33° N, 138,57° E\], Honshu. El holotipo era una hembra adulta recolectada por N. Teraoka el 4 de enero de 1913, pero casi con seguridad se perdió durante la Segunda Guerra Mundial, y de 16 paratipos, 10 de ellos de la colección de Matsudaira, 9 eran de la provincia de Yamashiro \[Prefectura de Kyoto\], pero no se dieron detalles que permitieran su identificación retrospectiva ([65](https://birdsoftheworld.org/bow/species/whbwoo1/cur/references#REF200509), [38](https://birdsoftheworld.org/bow/species/whbwoo1/cur/references#REF206875)). Algo intermedio entre las subespecies *subcirris* y *namiyei*. (Nombre originalmente ocupado por [*Dryobates villosus intermedius*](https://birdsoftheworld.org/bow/species/haiwoo/cur/systematics#subsp)Nelson, 1900).\
*Dryobates leucotos kurodae* Götz, 1925, Jahreshefte des Vereins für vaterländische Naturkunde in Württemberg 81:95. (Nuevo nombre para *D. I. intermedius* Kuroda, preocupado; véase la entrada anterior).\
*Dryobates leucotos uchidai* [Momiyama, 1927, Annotationes Ornithologiae Orientalis](https://books.google.de/books?redir_esc=y&hl=de&id=Bc1FAAAAYAAJ&focus=searchwithinvolume&q=uchidai) 1:3 (nomen nudum), 62 (texto en japonés), 96 (texto en inglés).-Nisimera-mura, Koyu-gun, provincia de Hiuga \[= prefectura de Miyazaki, 32,25° N, 131,48° E\], Kyushu. El holotipo es un macho adulto recolectado por Tomogorô Tanaka a mediados de marzo de 1927 (no de 1917 como se indica en la descripción original) y conservado en el Instituto Yamashina de Ornitología, Abiko [(YIO 00117](https://decochan.net/index.php?p=2&o=ssp&id=22512)) ([65](https://birdsoftheworld.org/bow/species/whbwoo1/cur/references#REF200509), [38](https://birdsoftheworld.org/bow/species/whbwoo1/cur/references#REF206875)).\
*Dryobates leucotos tookaidonis* [Momiyama, 1927, Annotationes Ornithologiae Orientalis](https://books.google.de/books?redir_esc=y&hl=de&id=Bc1FAAAAYAAJ&focus=searchwithinvolume&q=tookaidonis) 1:66. (Nuevo nombre para la forma septentrional del *D. I. intermedius* de Kuroda, y los detalles del tipo son los mismos que para este último; véase más arriba).

4.  **Material de tipo perdido**

**(a) *Myzanthe ignipectus*** [Blyth (ex Hodgson MS), 1843, Journal of the Asiatic Society of Bengal](https://www.biodiversitylibrary.org/item/123810#page/499/mode/1up) 12:983.-Nepal y Bután.

Blyth disponía evidentemente de al menos dos machos y una hembra, y uno de estos sintipos, un macho recogido por [Brian Houghton Hodgson (1800/01-1894)](https://en.wikipedia.org/wiki/Brian_Houghton_Hodgson) en Nepal en 1842, se encuentra en la colección del Zoological Survey of India, Kolkata (ZSI 35576) ([17](https://birdsoftheworld.org/bow/species/fibflo1/cur/references#REF185628); Gopinathan Maheswaran in litt. a G. M. Kirwan, abril 2022); se desconoce el paradero de los otros dos especímenes, si todavía existen, pero no se encuentran en el Natural History Museum, Tring ([18](https://birdsoftheworld.org/bow/species/fibflo1/cur/references#REF201546)).

Sinónimos:\
*Dicaeum ignipectus pulchellum* Koelz, 1954, Contribuciones del Instituto de Exploración Regional 1:21.-Sangau, Lushai Hills, Assam, India. El holotipo es una hembra recolectada el 24 de febrero de 1953 por Walter Norman Koelz y conservada en el Museo de Zoología de la Universidad de Michigan, Ann Arbor, Michigan, EE.UU. (UMMZ 147881) ([19](https://birdsoftheworld.org/bow/species/fibflo1/cur/references#REF106891)). Descrita aparentemente porque los machos son más oscuros, aunque Salomonsen ([11](https://birdsoftheworld.org/bow/species/fibflo1/cur/references#REF175742)) no pudo distinguir las diferencias.

*Dicaeum cyanonotum* [Styan, 1893, Ibis](https://www.biodiversitylibrary.org/item/85192#page/500/mode/1up) (6)5:470.-Ichang, valle superior del Yangtse, Hubei, China. Styan mencionó tener tres especímenes delante de él (dos machos y una hembra), y Salomonsen ([11](https://birdsoftheworld.org/bow/species/fibflo1/cur/references#REF175742)) informó haberlos examinado en el Museo de Historia Natural, Tring, Reino Unido (NHMUK), pero no figuran en el catálogo de tipos pertinente ([20](https://birdsoftheworld.org/bow/species/fibflo1/cur/references#REF181256)); sin embargo, una búsqueda realizada por H. van Grouw (in litt. a G. M. Kirwan, febrero de 2022) reveló la presencia de NHMUK 1914.8.15.56, un macho (que Styan evidentemente consideraba "el tipo") y la hembra, NHMUK 1914.8.15.58, ambos recolectados en junio de 1890. (El paradero del material de Styan no siempre está claro, pero la mayor parte parece estar en el NHMUK \[[21](https://birdsoftheworld.org/bow/species/fibflo1/cur/references#REF128324), [22](https://birdsoftheworld.org/bow/species/fibflo1/cur/references#REF121324)\] o en el Museo Americano de Historia Natural, Nueva York, NY, EE.UU. \[[23](https://birdsoftheworld.org/bow/species/fibflo1/cur/references#REF142159)\]). Descrito sobre la base de tener el brillo de las partes superiores del macho más azul, menos verde, con coberteras inferiores y grupa verdosas, y un color más anaranjado en el pecho, Salomonsen ([11](https://birdsoftheworld.org/bow/species/fibflo1/cur/references#REF175742)) consideró que estas supuestas diferencias reflejaban una variación individual, no geográfica, habiendo examinado especímenes con algunas o todas estas características de lugares tan distantes como Sichuan occidental y Vietnam meridional.

**(b) *Anas Fabalis*** [Latham, 1787, General Synopsis of Birds, Supplement](https://www.biodiversitylibrary.org/item/103199#page/335/mode/1up), p. 297.-Gran Bretaña.

Los especímenes originales de Latham son muy raros en las colecciones ([31](https://birdsoftheworld.org/bow/species/taibeg1/cur/references#REF200779)), y no se conoce la existencia del espécimen original de esta especie. Algunas fuentes han considerado que el nombre de Latham encajaba mejor con [*Anser brachyrhynchus*](https://birdsoftheworld.org/bow/species/pifgoo/cur/)) que con un ánsar careto (p. ej., [32](https://birdsoftheworld.org/bow/species/taibeg1/cur/references#REF6716), [33](https://birdsoftheworld.org/bow/species/taibeg1/cur/references#REF201590)), pero como señala Bourne ([34](https://birdsoftheworld.org/bow/species/taibeg1/cur/references#REF166350)) la ambigua descripción original de esta ave en Pennant va acompañada de una [figura](https://www.biodiversitylibrary.org/item/127014#page/234/mode/1up) inequívoca que representa un ánsar careto de Taiga.

### [Geographic Variation/Variación geográfica]{style="color:blue;"} {#sec-app3-systematics-geographic}

Resuma brevemente las tendencias en tamaño, color, vocalizaciones o cualquier otro rasgo que sea importante dentro de su especie. Esta sección debe ser sucinta, pero probablemente sea el mejor lugar para tratar cualquier componente geográfico del polimorfismo. Las descripciones detalladas del tamaño, el color, etc., se tratarán en otras secciones. Además de la variación en los rasgos físicos, la discusión de la variación genética intraespecífica, especialmente la variación no estrictamente relacionada con la divergencia entre subespecies, es apropiada para esta sección. Los ejemplos incluyen la discusión de estudios de flujo genético entre diferentes poblaciones a lo largo del área de distribución de una especie, la estructura genética no vinculada a las rupturas entre subespecies conocidas (por ejemplo, barreras biogeográficas importantes que podrían sugerir una diversidad críptica) y las metapoblaciones. Al resumir las tendencias en las características físicas y genéticas, mencione especialmente cualquier tendencia clinal notable en el área de distribución de una especie. Señale también las tendencias en la variación geográfica que no se correspondan con subespecies reconocidas, o los casos en los que las tendencias en un rasgo sean contrarias a las de otros rasgos. En los casos en que haya mucho material para discutir, puede ser útil subdividirlo mediante las subsecciones "Variación fenotípica" y "Variación genética".

### [Subspecies/Subespecies]{style="color:blue;"} {#sec-app3-systematics-subspecies}

Enumere las subespecies reconocidas actualmente. Incluya la misma información (combinación original, autoridad, especímenes tipo, etc.) que para las especies monotípicas (véase más arriba) en la subsección Historia Sistemática para cada subespecie. Incluya también los mismos datos para los sinónimos, cuando proceda. Describa las áreas de distribución y las características distintivas generales. La subsección Resumen de identificación debe centrarse en las diferencias con la subespecie nominal o con taxones geográficamente próximos, pero en algunos casos puede resultar apropiado una mezcla de estos enfoques, o incluso uno completamente distinto. En cualquier caso, el objetivo es dilucidar sucintamente los caracteres que hacen que el taxón sea único. En algunos casos, puede ser necesario consultar las descripciones originales para obtener información, pero tenga en cuenta que las descripciones más antiguas (especialmente de 1800 y principios de 1900) se basaban a menudo en muy pocos especímenes (incluso de taxones de comparación), y los autores eran más propensos a reconocer variaciones relativamente triviales, lo que podría hacer que los caracteres utilizados en tales casos merezcan una advertencia. Señale las discrepancias y ofrezca su opinión sobre la validez de las subespecies, en caso de que tratamientos alternativos puedan ser más apropiados. En tales casos, informe también a Pamela Rasmussen (pcr44\@cornell.edu) de sus conclusiones para que el equipo de eBird/Clements Checklist pueda considerar la revisión de nuestro tratamiento.

### [Related Species/Especies emparentadas]{style="color:blue;"} {#sec-app3-systematics-related}

Céntrese en los estudios basados en datos genéticos, dado que se han muestreado la mayoría de las especies ampliamente reconocidas, y sólo las especies más estrechamente relacionadas con su especie focal. Comente brevemente la solidez de las relaciones inferidas (por ejemplo, el número de muestras o loci analizados) y cualquier incertidumbre en los análisis sobre esas relaciones inferidas. En algunos casos, puede ser interesante contrastar brevemente los conocimientos actuales basados en la genética con las clasificaciones basadas en la morfología, cuando éstas difieran de forma especialmente dramática o cuando los datos genéticos no sean particularmente robustos. En general, sin embargo, la atención debe centrarse en estudios recientes que incorporen datos genéticos cuando estén disponibles. En general, no es necesario proporcionar una discusión más amplia de las relaciones a nivel de familia o incluso a nivel de género, especialmente para agrupaciones comparativamente grandes (más especiosas). Sin embargo, para los géneros o familias monoespecíficos, puede ser pertinente una breve exposición de los parientes conocidos más cercanos en otros géneros o familias, pero tenga en cuenta que nuestros textos a nivel de familia ya sirven para este propósito. En unos pocos casos, puede ser necesario discutir las relaciones sin el beneficio de los datos moleculares (por ejemplo, "12 especies de *Accipiter* permanecen sin analizar genéticamente"). Incluso en los casos en los que una especie concreta no ha sido muestreada genéticamente, puede suponerse que está muy estrechamente emparentada con una especie que sí lo ha sido; en este caso, conviene mencionar las relaciones genéticas de las especies que han sido muestreadas e indicar que se supone que la especie actual también forma parte de este grupo.

### [Hybridization/Hibridación]{style="color:blue;"} {#sec-app3-systematics-hybrid}

Comente el grado de hibridación con otras especies, si se conoce. Si la hibridación con otras especies es frecuente, o si la especie forma una zona híbrida con otra especie, cite cualquier estudio pertinente que hable de esta hibridación, así como las marcas de campo pertinentes que identifiquen los híbridos.

### [Fossils/Fósiles]{style="color:blue;"} {#sec-app3-systematics-fossils}

Aunque esta sección puede estar en blanco o ser breve para algunas especies, debe incluirse siempre que sea posible para mostrar que la mayoría de las aves tienen una historia fósil importante. En muchos casos, no hay historia fósil para una especie en particular, pero puede haber datos fósiles para taxones extintos estrechamente relacionados que pueden representar un antepasado extinto de la especie actual, o incluso taxones cuyas identidades son ambiguas debido a material incompleto; también está bien incluir esto en esta sección. Por favor, aclare si se refiere a un fósil de la especie actual o a una especie parecida a la actual. Cuando describa el fósil, indique dónde se descubrió y de qué época procede (incluya el nombre de la época y el intervalo de fechas aproximado).

## [DISTRIBUTION/DISTRIBUCIÓN]{style="color:purple;"} {#sec-app3-distribution}

No se limite a remitir al lector a su mapa de distribución, sino que describa la distribución geográfica actual de su especie en términos de límites estatales, provinciales y nacionales. Comente cualquier detalle significativo que no aparezca fácilmente en el mapa de distribución, en particular en relación con el área de reproducción (por ejemplo, "dentro del área de reproducción, la especie sólo se da en elevaciones superiores a..."). Consulte el [Apéndice 4](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.39kk8xu) para obtener orientación sobre el uso de mayúsculas en las regiones geográficas.

### [Distribution (introduction)/Distribución (introducción)]{style="color:blue;"} {#sec-app3-distribution-intro}

Utilice las subsecciones de área de reproducción y área de no reproducción si son relevantes para su especie. Si no, simplemente cubra la información relevante sin usar una subsección o añada diferentes subsecciones que sean útiles.

**Para todas las subsecciones**, puede ser útil la siguiente terminología sobre ocurrencia. **Asegúrese de indicar el intervalo de meses correspondiente si habla de estaciones (primavera, verano, otoño, invierno):**

-   **Residente.** Presencia durante todo el año en una zona, incluida la reproducción, aunque puede haber diferentes poblaciones de una estación a otra.

-   **(Estival) Reproductor.** Abandona la zona durante la época no reproductora; algunas aves en una zona de veraneo pueden ser en realidad aves en paso, que aún no se encuentran en sus propias zonas de cría.

-   **Visitante estival.** Visita la zona en primavera y verano, pero se reproduce en otros lugares.

-   **Visitante otoñal.** Visitas a finales de verano, otoño o principios de invierno; generalmente errantes postnupciales.

-   **Visitante invernal.** Reside en la zona durante la época no reproductora.

-   **Migrante.** Ave de paso que permanece brevemente en la ruta entre sus hogares estivales e invernales.

-   **Accidental.** La especie se ha registrado una o dos veces (raramente más) en una zona designada y, según una probabilidad razonable, es improbable que se dé allí con regularidad.

**Casual.** La especie se ha registrado unas pocas veces dentro de un área designada, no lo suficiente como para constituir una presencia regular, pero lo suficiente como para sugerir que los registros posteriores no son improbables.

**Breeding Range/Nonbreeding Range/Área de reproducción/Área de distribución no reproductora**

Estas secciones deben proporcionar la mejor aproximación a la distribución de la especie en toda su área de distribución y a lo largo de la estación pertinente (es decir, reproductora o no reproductora). Puede que desee proporcionar una lista de descripciones detalladas por condado o estado (u otra subdivisión pertinente), o puede que prefiera resumir esta información. Cualquiera de los dos enfoques es adecuado. 

Su texto irá acompañado de un mapa (morado) del área de distribución general de la especie a través de eBird. Si se dispone de productos de datos de eBird (por ejemplo, un mapa que muestre la abundancia a lo largo del año), también se incluirán. Si lo desea, puede incluir en el texto enlaces a las distribuciones de eBird para zonas o periodos de tiempo específicos.

Siempre que sea posible, consulte los atlas de aves reproductoras u otros proyectos de distribución normalizados. Estas referencias contienen excelente información sobre el estado actual de reproducción, así como sobre los cambios históricos en la distribución. Cuando proceda, el Conteo Navideño de Aves puede ser útil para las áreas de distribución no reproductoras y la abundancia. Si desea incluir un enlace a estos atlas, utilice texto con hipervínculos, en lugar de incluir una URL en el texto.

**Elevational Range/Rango de elevación**

Indique la altitud (en metros sobre el nivel del mar) a la que se encuentra la especie. Incluya la variación geográfica y/o estacional en el rango de elevación si procede.

**Introduced Range/Rango donde está introducida**

Discutir la historia y la distribución de las introducciones de especies en las que se han establecido poblaciones.

**Extralimital Records/Registros fuera del límite de distribución**

Notifique registros auténticos (con referencias) de presencia fuera del área de distribución normal. Se recomienda enlazar con la documentación a través de eBird o la Biblioteca Macaulay, siempre que sea posible.

### [Historical Changes to the Distribution/Cambios históricos en la distribución]{style="color:blue;"} {#sec-app3-distribution-historical}

Resuma cualquier ampliación o contracción significativa de la distribución y los factores causales de la misma.

## [HABITAT/HÁBITAT]{style="color:purple;"} {#sec-app3-habitat}

### [Habitat (introduction)/Hábitat (introducción)]{style="color:blue;"} {#sec-app3-habitat-intro}

Un resumen general del hábitat de la especie y una breve mención de cualquier punto de especial interés. Evite las citas en esta sección.

**Habitat Keywords/Palabras clave del habitat**

En la medida de lo posible, enumere las categorías y subcategorías de hábitat utilizadas por la especie, tal y como las definen Campbell et al. (2021) en el libro Habitats of the World u otros libros de esa serie (descritos en @sec-app3-habitat-categories más abajo), de más a menos importantes. Enumere la categoría seguida de dos puntos y cualquier subcategoría aplicable. No incluya ningún otro texto en esta sección. El uso de estas categorías servirá de base para un próximo producto de datos BOW que contendrá información clave sobre todas las especies de aves y que será útil para análisis a gran escala. Por ejemplo:

Conifer forests: taiga (boreal forest), temperate conifer forest

Temperate deciduous forests: temperate deciduous forest, temperate moist mixed forest

### [General Habitat/Hábitat general]{style="color:blue;"} {#sec-app3-habitat-general}

**Para las especies residentes**, comience con una descripción general de su hábitat, y luego cubra detalles más específicos según sea necesario. Puede utilizar las categorías y subcategorías de hábitats definidas por Campbell et al. (2021) en el libro Habitats of the World (descritas en @sec-app3-habitat-categories más adelante). Si tiene acceso a una copia de este libro o de cualquiera de sus libros complementarios para continentes específicos, las categorías de hábitat a escala más fina que se discuten también podrían ser útiles, pero tenga en cuenta que la consulta de estos libros no es en absoluto obligatoria. Caracterice el hábitat en términos de su rango latitudinal y elevacional y sus límites climáticos, y describa la topografía, el sustrato y la vegetación (incluyendo las etapas de crecimiento y/o sucesión vegetal, las especies dominantes y su estado, y el espaciado). Si lo desea, puede ampliar la información más allá de las categorías indicadas a continuación.

Señale las diferencias de hábitat en las distintas partes del área de distribución geográfica. Distinga entre los hábitats en los que la especie está presente habitualmente y aquellos en los que es poco común. No utilice las expresiones "selección de hábitat" o "preferencia de hábitat" a menos que existan estudios directos de esos fenómenos específicos. Compare los hábitats de su especie con los de sus parientes cercanos, sobre todo si son simpátricos.

Los detalles de los microhábitats funcionales, es decir, los lugares utilizados para actividades concretas, deben indicarse en las páginas siguientes cuando se hable de búsqueda de comida, descanso, nidificación, etc.

**Deje esta sección en blanco para las especies migratorias** (a menos que existan poblaciones no migratorias, que podrían tratarse aquí).

### [Habitat in Breeding Range/Hábitat en rango reproductivo]{style="color:blue;"} {#sec-app3-habitat-breeding}

**En el caso de las especies migratorias**, trate el hábitat o los hábitats como se indica más arriba en Hábitat general, en función de la zona de distribución estacional de la especie. Deje estas secciones en blanco para las especies residentes.

### [Habitat in Migration/Hábitat en migración]{style="color:blue;"} {#sec-app3-habitat-migration}

**En el caso de las especies migratorias**, trate el hábitat o los hábitats como se indica más arriba en Hábitat general, en función de la zona de distribución estacional de la especie. Deje estas secciones en blanco para las especies residentes.

### [Habitat in Nonbreeding Range/Hábitat en rango no reproductivo]{style="color:blue;"} {#sec-app3-habitat-nonbreeding}

**En el caso de las especies migratorias**, trate el hábitat o los hábitats como se indica más arriba en Hábitat general, en función de la zona de distribución estacional de la especie. Deje estas secciones en blanco para las especies residentes.

### [Categorías de hábitats]{style="color:blue;"} {#sec-app3-habitat-categories}

Categorías y subcategorías de hábitats definidas por Campbell et al. (2021) en el libro Habitats of the World, con definiciones adaptadas del libro:

-   **Conifer forests:** bosques dominados por coníferas (que normalmente no pierden las hojas).
    -   **Taiga (boreal forest):** spruce and fir forest in the Far North
    -   **Temperate conifer forest:** humid coniferous forest in temperate areas (including mountains)
    -   **Dry conifer forest:** conifer-dominated forest/woodland in dry temperate and tropical areas
-   **Deserts and arid scrubs:** arid habitats characterized by little plant growth
    -   **Barren desolate desert:** harsh desert with rock, sand dunes, and very little plant growth
    -   **Hot desert:** tropical or subtropical desert with hot summers and cool/warm winters
    -   **Cold desert:** temperate desert with hot/warm summers and cold winters
    -   **Desert and semidesert shrubland:** open arid area characterized by small shrubs (typically with small leaves); may contain cacti or euphorbias
    -   **Desert steppe:** very arid area with sparse and ephemeral grass growth
    -   **Desert and semidesert thornscrub:** arid area characterized by thickets of tall thorn bushes and little grass
    -   **Arctic polar desert:** extremely cold and dry area with virtually no plant growth
-   **Temperate deciduous forests:** forest with either entirely broadleaf deciduous trees or a mix of deciduous trees and evergreen trees
    -   **Temperate deciduous forest:** temperate broadleaf deciduous forest in which most trees lose their leaves in winter
    -   **Temperate moist mixed forest:** temperate forest with a mix of broadleaf deciduous trees and evergreen trees (broadleaf trees and/or conifers)
-   **Tropical humid forests:** warm and wet rainforest-type habitats
    -   **Lowland rainforest:** tall, wet evergreen forest with a thick canopy and open understory
    -   **Semievergreen forest:** generally humid forest with a nearly complete canopy; only some trees lose their leaves
    -   **Montane/subtropical evergreen forest:** warm, wet forest with a nearly complete canopy composed of evergreen or partially deciduous trees
-   **Dry deciduous forests:** warm forests characterized by trees that lose most of their leaves during dry periods
    -   **Closed deciduous forest:** fire-intolerant, dry deciduous forest with a closed canopy; trees are lush in summer, but most lose their leaves in winter
    -   **Open deciduous forest:** fire-intolerant deciduous forest with an open canopy and an understory of small-leaved shrubs, cacti, and/or euphorbias; trees can lose their leaves during dry periods
-   **Savannas and seasonally moist shrublands:** habitats with an open canopy and an abundance of grass and/or shrubs; strongly seasonal, typically with wet summers and dry winters, and heavily affected by fire
    -   **Open broadleaf woodland:** fire-tolerant woodland characterized by tall, broadleaf trees and an open canopy; many deciduous trees may be present
    -   **Thorn savanna:** open woodland with abundant grass cover and tall or short trees (often acacias), many of which have spines
    -   **Broadleaf sclerophyllous savanna:** fire-tolerant low shrubland or forest that can be thickly vegetated and that has less grass than other savannas; plants have thick, leathery leaves and thick bark
    -   **Mixed shrub savanna:** fire-tolerant thicket or dry forest with a low canopy; characterized by grass cover and a mix of coniferous, sclerophyllous, and broadleaf shrubs or trees
-   **Grasslands and steppes:** fire-dependent habitats dominated by grasses; may or may not contain shrubs and flowers and have few to no trees
    -   **Temperate grassland:** fire-tolerant grassland with moderate or warm summers and cold winters; growth is restricted to the warmer spring and summer months; precipitation can include snow in winter and rain in summer
    -   **Tropical grassland:** fire-tolerant grassland with hot summers and moderate winters; growth of grasses can occur throughout the year with sufficient rainfall
    -   **Montane grassland:** fire-tolerant, highland grassland that often receives orographic rainfall (i.e., caused by proximity to a mountain range)
    -   **Flooded grassland:** grassland that becomes a huge wetland during the wet season
-   **Mediterranean forests, woodlands, and shrublands:** habitats characterized by thick scrub and with dry, hot summers and wet, cold winters
    -   **Maquis, chaparral, and matorral:** low shrubland that is either closed or open and is dominated by fire and grazing; the plants present are often similar to those in nearby forests
    -   **Mediterranean heathland:** fire-dependent low heathland with nearly complete ground cover consisting of sclerophyllous bushes and forbs
-   **Sclerophyllous forests and woodlands:** forests and woodlands in which most canopy trees are eucalypts and/or have small, leathery leaves
    -   **Wet sclerophyll forest:** forest with tall, straight-trunked trees whose canopy branches touch each other and a lush, wet understory; canopy trees are fire tolerant, but the understory is fire intolerant
    -   **Dry sclerophyll forest:** fire-tolerant forest with tall, straight-trunked trees that are too widely spaced to form a closed canopy (although trees may sometimes touch each other) and an understory dominated by grass and shrubs not found in nearby rainforests
    -   **Eucalypt woodland:** open woodland with a thin canopy; characterized by eucalypts with short, crooked trunks
    -   **Australasian acacia woodlands:** open woodland or shrubland, often with a thick canopy; characterized by short acacias
-   **Tundras:** habitats characterized by very low vegetation dominated by mosses and lichens; at extreme latitudes or elevations where tree growth is prohibited due to temperature, snow cover, and/or exposure to wind
-   **Freshwater habitats:** habitats inundated with freshwater
    -   **Swamp forest:** seasonally or permanently inundated forest
    -   **Freshwater wetland:** seasonally or permanently flooded nonforested habitat
-   **Salt-dominated habitats:** habitats with high salt levels in the water or soil
    -   **Saltpan:** habitat in which evaporation or volcanic activity has produced extremely high salt levels in the soil; mostly unvegetated, but algae grows quickly after floods
    -   **Mangrove:** a specialized forest of mangroves in tidally flooded coastal areas
    -   **Saltmarsh:** habitat characterized by salt-tolerant marsh vegetation and found in sheltered coastal areas that are periodically flooded with seawater
    -   **Tidal mudflat:** a nutrient-rich area of mud that is frequently flooded with seawater; usually occurs in estuaries
    -   **Rocky coastline and sandy beach:** nutrient-poor rocky or sandy beach, cliff, or other coastline habitat
    -   **Pelagic waters:** marine habitat with deep water
    -   **Offshore islands:** small islands that are well offshore and support low grass and/or shrubs
-   **Anthropogenic habitats:** habitats shaped primarily by human presence
    -   **Grazing lands:** areas heavily grazed by domestic animals
    -   **Cultivated lands:** areas in which humans produce crops
    -   **Human habitation:** areas directly inhabited by humans

## [MOVEMENTS AND MIGRATION/MOVIMIENTOS Y MIGRACIÓN]{style="color:purple;"} {#sec-app3-movements}

### [Movements and Migration (introduction)/Movimientos y migraciones (introducción)]{style="color:blue;"} {#sec-app3-movements-intro}

Breve descripción general de los movimientos anuales de la especie (o de la ausencia de ellos) y de cualquier aspecto que destaque. Evite las citas en esta sección.

### [Disperal and Site Fidelity/Dispersión y fidelidad al sitio]{style="color:blue;"} {#sec-app3-movements-dispersal}

Comunique todos los datos disponibles sobre la tendencia de un ave a ser fiel a un lugar o dispersiva. Las subsecciones se explican por sí mismas (véase [el Apéndice 2](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.3as4poj)). Cualquier discusión sobre el tamaño del territorio o del área de distribución debe incluirse en la sección de métricas espaciales de la población.

### [Nonmigratory Movements/Movimientos no migratorios]{style="color:blue;"} {#sec-app3-movements-nomigratory}

Comente los desplazamientos de la especie que no se consideren migración o dispersión fuera de las zonas de cría (por ejemplo, desplazamientos nómadas o desplazamientos diarios para buscar alimento o posarse).  Pueden incluirse subapartados especialmente relevantes para la especie (por ejemplo, "Desplazamientos hacia y desde un dormidero comunitario").

### [Migration Overview/Visión general de la migración]{style="color:blue;"} {#sec-app3-movements-overview}

Caracterice los movimientos estacionales de los individuos entre zonas geográficas y hábitats. Proporcione una visión general del comportamiento migratorio diferencial de las clases de edad y sexo en el tiempo y el espacio (debe proporcionar detalles en Calendario y rutas de migración, más abajo). Señale cualquier variación entre las poblaciones de su especie.

### [Timing and Routes of Migration/Calendario y rutas de migración]{style="color:blue;"} {#sec-app3-movements-timing}

Describa el calendario y las rutas de migración a una escala geográfica amplia, pero señale las diferencias conocidas entre las poblaciones. Remitir a obras regionales para obtener detalles y fechas representativas.

### [Migratory Behavior/Conducta migratoria]{style="color:blue;"} {#sec-app3-movements-behavior}

La sección anterior trataba del "dónde" y el "cuándo" de la migración; esta sección y la siguiente se refieren al "cómo" de la migración. Estas secciones variarán mucho de una ficha a otra, reflejando las diferencias en el conocimiento del comportamiento migratorio de las especies. Incluya información y referencias sobre temas como la hora habitual del día, la altitud y la velocidad de la migración; el método o métodos de orientación; las respuestas a las condiciones meteorológicas; y el grado de bandadas y formaciones de vuelo. Si alguno de estos temas se ha estudiado de forma intensiva en su especie, resuma los principales resultados y facilite referencias bibliográficas.

### [Control and Physiology of Migration/Control y fisiología de la migración]{style="color:blue;"} {#sec-app3-movements-control}

Si se han estudiado en su especie, los temas a tratar incluyen la inquietud migratoria, la hiperfagia y la deposición de grasa, la respuesta al fotoperiodo y el papel de las hormonas. Mencione las variaciones conocidas entre poblaciones, sexos o clases de edad, pero consulte la bibliografía para más detalles. Incluya cualquier información que indique que el comportamiento migratorio es aprendido, por ejemplo, de los padres, o en gran medida innato.

## [DIET AND FORAGING/DIETA Y ALIMENTACIÓN]{style="color:purple;"} {#sec-app3-diet}

Por lo general, trate una especie como un todo, pero señale las variaciones conocidas en función del sexo, la edad, la estación o la localidad. En el caso de las especies migratorias, haga un esfuerzo especial por facilitar información sobre los hábitos alimentarios en el área de distribución no reproductora, así como sobre los hábitos más conocidos en el área reproductora. Si las poblaciones o subespecies están muy separadas u ocupan entornos muy diferentes, puede ser mejor tratarlas por separado. Céntrese en esta sección en los hábitos alimentarios de los adultos, dejando los de las aves jóvenes (incluidos los elementos suministrados a las aves jóvenes por los adultos) para las secciones pertinentes de Breeding.

### [Diet and Foraging (introduction)/Dieta y alimentación (introducción)]{style="color:blue;"} {#sec-app3-diet-intro}

Un resumen general de la biología de la especie en relación con la alimentación y una breve mención de cualquier punto especial. Evite las citas en esta sección.

### [Feeding/Alimentación]{style="color:blue;"} {#sec-app3-diet-feeding}

**Microhabitat for Foraging/Microhábitat para la alimentación**

Esta subsección abarca el lugar donde se produce la búsqueda de alimento, incluidos los sustratos de los que se obtiene (por ejemplo, especies vegetales específicas o tipos de plantas y posición dentro de la vegetación, altura de búsqueda de alimento, tipo de sustrato, tipos de humedales, distancia de la orilla o profundidad del agua).

**Food Capture and Consumption/Captación y consumo de alimentos**

Esta subsección trata de cómo se obtiene y consume el alimento. Además del comportamiento en sí, indique lo siguiente si se conoce y es apropiado: momento del día para buscar alimento, porcentaje de tiempo dedicado a cada táctica de búsqueda durante la alimentación, cualquier adaptación anatómica o fisiológica específica para la alimentación, interacciones relacionadas con la alimentación (por ejemplo, caza cooperativa por parejas o bandadas, comensalismo o piratería) y capacidad para aprovechar oportunidades inusuales para alimentarse.

### [Diet/Dieta]{style="color:blue;"} {#sec-app3-diet-diet}

**Major Food Items/Principales alimentos**

Incluya un resumen de los tipos generales de alimentos ingeridos (añada el orden, la familia o el nombre científico, según proceda). Por ejemplo: "Dieta principalmente de insectos, especialmente saltamontes y grillos (Orthoptera), hormigas (Hymenoptera: Formicidae), saltahojas (Homoptera), chinches (Hemiptera), escarabajos (Coleoptera), así como arañas (Araneae)". Si la información está tomada de la bibliografía, cite los nombres tal como se publicaron originalmente y ponga entre corchetes las correcciones o revisiones necesarias. Indique el intervalo de tamaño (longitud o masa) de los artículos.

**Quantitative Analysis/Análisis cuantitativo**

Resuma los estudios cuantitativos detallados para mostrar las proporciones de los diferentes tipos de alimentos en la dieta. Indique la naturaleza de los datos analizados (por ejemplo, observaciones de la alimentación, contenido del esófago o la molleja o egagrópilas) y el tamaño de la muestra. Prevenga el sesgo causado por la digestibilidad diferencial de los alimentos o la digestión postmortem y la acción bacteriana. Identifique el método o métodos utilizados para expresar las cantidades de alimentos (por ejemplo, porcentaje de volumen, frecuencia de aparición o masa \[húmeda o seca\] del total de alimentos ingeridos). Teniendo en ficha estas variables de metodología, informe de las diferencias publicadas en la composición de la dieta, pero sea prudente al compararlas.

### [Food Selection and Storage/Selección y almacenamiento de alimentos]{style="color:blue;"} {#sec-app3-diet-storage}

Comunique brevemente cualquier información sobre los sentidos del gusto y el olfato, el reconocimiento y la elección de alimentos, o el almacenamiento y la recuperación. Cite las referencias para más detalles. Puede colocar este material en la subsección Captación y consumo de alimentos (en Alimentación) si eso facilita la redacción.

### [Nutrition and Energetics/Nutrición y energética]{style="color:blue;"} {#sec-app3-diet-nutrition}

Las necesidades nutricionales de las aves silvestres sólo se han estudiado en unas pocas especies, pero se incluye esta sección como recordatorio de un tema que merece atención. Indique, cuando sea posible, la ingesta alimentaria diaria y los valores nutricionales y calóricos de los alimentos. Exprese la importancia relativa de los distintos alimentos en función de la energía metabólica que proporcionan.

### [Metabolism and Temperature Regulation/Metabolismo y regulación de la temperatura]{style="color:blue;"} {#sec-app3-diet-metabolism}

Resumir la bibliografía relativa a la tasa metabólica y la regulación de la temperatura por sexo, estación, edad y población cuando sea posible.

### [Driking, Pellet Casting, and Defecation/Ingesta, egagrópilas y defecación]{style="color:blue;"} {#sec-app3-diet-drinking}

Incluya una descripción de los aspectos inusuales o estudios cuantitativos de estos hábitos.

## [SOUNDS AND VOCAL BEHAVIOR/SONIDOS Y CONDUCTA VOCAL]{style="color:purple;"} {#sec-app3-sounds}

Utilice los términos bioacústicos tal y como se definen en el Glosario ([Apéndice 6](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.1302m92)) para evitar confusiones y errores. No utilice términos como "teléfono", "frase" o "sílaba" a menos que sea absolutamente necesario, en cuyo caso defínalos. La forma más sencilla de explicar lo que quiere decir es etiquetar las características en un espectrograma.

### [Sounds and Vocal Behavior (introduction)/Sonidos y conducta vocal (introducción)]{style="color:blue;"} {#sec-app3-sounds-intro}

Un resumen general de la biología de la especie en relación con los sonidos y una breve mención de cualquier punto de especial interés. Evite las citas en esta sección.

### [Vocalizations/Vocalización]{style="color:blue;"} {#sec-app3-sounds-vocalizations}

**Vocal Development/Desarrollo vocal**

Proporcione mediciones, espectrogramas sonoros y referencias para documentar los cambios relacionados con la edad y el aprendizaje vocal, si es posible.

**Vocal Array/Conjunto vocal**

Describa verbalmente los tipos de vocalización importantes (interpretación fonética en inglés) y proporcione mediciones (duración, tasas de repetición y cadencia) y espectrogramas si es posible. Si su especie tiene un gran repertorio vocal, no lo presente todo, pero elija los sonidos más frecuentes y significativos desde el punto de vista del comportamiento y cite las referencias. 

Esta sección variará considerablemente entre especies, reflejando las diferencias en las señales acústicas de las aves y nuestro conocimiento de las mismas. Con respecto a su especie en particular, mantenga esta sección breve si se sabe poco, pero amplíela, incluyendo referencias, en relación con la información disponible.

Si no existen distinciones entre cantos y llamadas en su especie, mencione cualquier ambigüedad en el uso de "canto" al hablar de las vocalizaciones.

**Geographic Variation/Variación geográfica**

Describa la variación (o la falta de ella) en las vocalizaciones y/o en la respuesta a las vocalizaciones según la zona geográfica. 

**Phenology/Fenología**

Identifique las temporadas de mayor y menor vocalización, incluyendo cualquier actividad durante la migración y en las zonas no reproductivas. Si es posible, mencione cualquier variación en el patrón según la estación (incluyendo el rango de meses) o el contexto social. Si es posible, mencione cualquier variación en el número de tipos de canto por individuo según la edad, el individuo, la estación o la zona geográfica.

**Daily Pattern of Vocalizing/Patrón diario de vocalización**

Resuma el patrón de vocalización de la mañana a la noche.

**Places of Vocalizing/Lugares de vocalización**

Caracterice el lugar o lugares de vocalización (por ejemplo, en el suelo, desde una percha elevada o en vuelo) y compárelos con los lugares utilizados para alimentarse o anidar. Resuma el patrón diario de actividad vocal.

**Sex Differences/Diferencias entre sexos**

Describe las diferencias entre las vocalizaciones de los machos y las hembras de tu especie. En una lista de cantos y llamadas, considere la posibilidad de clasificarlos por sexos. Anote el sexo de los cantantes (si se conoce) en los espectrogramas que presente.

**Repertoire and Delivery of Songs/Repertorio y ejecución de canciones**

Discuta el tamaño del repertorio de canto de cada ave. Discuta el patrón o patrones con los que se emiten los elementos de la canción. Por ejemplo, ¿el ave emite una serie de diferentes tipos de canto sin repetición, o el mismo tipo de canto se repite varias veces antes de que el ave cambie a un nuevo tipo de canto?

**Social Context and Presumed Functions of Vocalizations/Contexto social y supuestas funciones de las vocalizaciones**

Para cada canto/llamada, indique su contexto social (presencia, estatus y actividad de otros individuos del mismo sexo, del sexo opuesto o de otra especie) y sus presuntas funciones, además de cualquier otra prueba de esa función. El hábitat, el comportamiento y el contexto social de un ave proporcionan a menudo pistas sobre las funciones de sus señales sonoras. Por lo tanto, conviene hacer breves generalizaciones sobre estas condiciones cuando sea razonable. Se puede encontrar mucha información de este tipo en las notas de campo que acompañan a las grabaciones sonoras.

Evite la interpretación funcional y los nombres (por ejemplo, "llamada de cortejo") para los sonidos sin tener en ficha la calidad de las pruebas, y cite dichas pruebas. En particular, no asuma sin pruebas que un sonido determinado está implicado en la atracción de la pareja, la defensa territorial o ambas. Señale cualquier problema interesante para la investigación sobre las señales acústicas de su especie.

### [Nonvocal Sounds/Sonidos no vocales]{style="color:blue;"} {#sec-app3-sounds-nonvocal}

Los sonidos producidos por el pico, las patas, las alas o la cola deben tratarse de la misma manera general que las vocalizaciones, según proceda y exista información.

## [BEHAVIOR/CONDUCTA]{style="color:purple;"} {#sec-app3-behavior}

Esta página está organizada como un compromiso entre la serie tradicional de subsecciones separadas y el tratamiento exhaustivo que preferiría un conductista. Abarca la forma en que un ave se desplaza, cuida de sí misma e interactúa con otros individuos de la misma especie o de especies diferentes. Otros aspectos del comportamiento se tratan en las páginas sobre Migración, Alimentación y búsqueda de alimento, Sonidos, Reproducción y Demografía y poblaciones. En todas las secciones, procure progresar desde los patrones de acción hasta los niveles superiores de los patrones de comportamiento.

### [Behavior (introduction)/Conducta (introducción)]{style="color:blue;"} {#sec-app3-behavior-intro}

Un resumen general de la biología de la especie en relación con el comportamiento y una breve mención de cualquier punto destacable. Evite las citas en esta sección.

### [Locomotion/Locomoción]{style="color:blue;"} {#sec-app3-behavior-locomotion}

Describa los movimientos físicos, incluida la postura y los movimientos frecuentes como el balanceo de la cola. Mencione cualquier adaptación anatómica o fisiológica específica para la locomoción e indique cualquier medida de rendimiento (por ejemplo, velocidad de desplazamiento, número de aleteos por segundo, altitud de vuelo o profundidad y duración de la inmersión). Intente relacionar estas acciones con su contexto o factores de control y presuntas funciones. Señale las formas conocidas de variación, ya sean relacionadas con la edad, sexuales, estacionales o geográficas.

### [Self-Maintenance/Auto-mantenimiento]{style="color:blue;"} {#sec-app3-behavior-self}

Describa lo que se sabe sobre cómo la especie mantiene su estado. Véase la lista de subsecciones en [el Apéndice 2](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.3as4poj). Utilice la terminología definida en el Glosario ([Apéndice 6](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.1302m92)). Si la situación de su especie no se ajusta a ninguna de estas categorías, descríbala en lugar de basarse en etiquetas.

### [Agonistic Behavior/Conducta agonística]{style="color:blue;"} {#sec-app3-behavior-agonistic}

Describa los comportamientos antagónicos de una especie hacia sus congéneres en el contexto de interacciones físicas, interacciones comunicativas o interacciones territoriales. El texto relativo a las interacciones territoriales debe hacer hincapié en el uso estacional y espacial del territorio, así como en la forma en que se anuncian los territorios (los detalles del canto, el tamborileo, etc., se tratan en Sonidos y comportamiento vocal). En la medida de lo posible, los autores deben incluir subsecciones en las que se describan los comportamientos tanto en el periodo reproductor como en el no reproductor.

### [Sexual Behavior/Conducta sexual]{style="color:blue;"} {#sec-app3-behavior-sexual}

Para todas las subsecciones enumeradas en [el Apéndice](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.3as4poj)2, utilice la terminología de los sistemas de apareamiento definida en el Glosario ([Apéndice 6](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.1302m92)). Si la situación de su especie no se ajusta a ninguna de estas categorías, descríbala en lugar de basarse en etiquetas. Evite los términos "polygamy" y "promiscuous" -porque es ambiguo-. Señala si el sistema de apareamiento está influido por el hábitat en determinadas poblaciones.

### [Social and Interspecific Behavior/Comportamiento social e interespecífico]{style="color:blue;"} {#sec-app3-behavior-social}

Repase todas las subsecciones enumeradas en [el Apéndice 2](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.3as4poj). Sitúe su especie en un continuo que vaya de solitaria a muy gregaria, anotando las fluctuaciones estacionales, el tamaño aproximado de las agregaciones y la actividad de dichos grupos o bandadas.

### [Predation/Depredación]{style="color:blue;"} {#sec-app3-behavior-predation}

Escriba esta sección desde el punto de vista de su especie como presa, no como depredador. Este último tema se habrá tratado en la página Dieta y alimentación

## [BREEDING/REPRODUCCIÓN]{style="color:purple;"} {#sec-app3-breeding}

Para cada subsección, describa primero la condición típica, es decir, la que muestran aves experimentadas en la población mejor conocida. A continuación, informe de cualquier variación entre individuos, en reproductores más jóvenes o en otras poblaciones. Sin embargo, si las subespecies de su especie difieren en al menos varios aspectos importantes de su cría, puede ser más sensato tratarlas en secciones separadas y exhaustivas.

### [Breeding (introduction)/Reproducción (introducción)]{style="color:blue;"} {#sec-app3-breeding-intro}

Un resumen general de la biología reproductora de la especie y una breve mención de cualquier punto de especial interés. Evite las citas en esta sección.

### [Phenology/Fenología]{style="color:blue;"} {#sec-app3-breeding-phenology}

Utilice las subsecciones sugeridas sólo si dispone de información suficiente para cada etapa del ciclo reproductor. En este apartado deben indicarse fechas representativas y otros datos, siempre que sea posible, mientras que el diagrama del ciclo anual muestra el patrón estacional de la reproducción en relación con la migración y la muda. El momento de la formación de la pareja y de la construcción del nido debe indicarse en el texto, pero suele omitirse en el diagrama porque no puede registrarse con tanta precisión como el de los sucesivos episodios reproductivos. Para algunas especies, incluso estos últimos son tan poco conocidos que sería inútil intentar incluirlos en el diagrama.

Mencione lo que se sabe sobre los factores que controlan el momento de la reproducción en su especie. Indique cómo afectan las condiciones meteorológicas al crecimiento de la vegetación y a la disponibilidad de alimento y lugares de nidificación. No obstante, evite establecer correlaciones a partir de estudios que abarquen sólo unos pocos años, ya que la situación puede ser más compleja de lo que parece a primera vista.

### [Nest Site/Sitios de nidificación]{style="color:blue;"} {#sec-app3-breeding-site}

Las subsecciones incluyen el Proceso de selección (sólo conocido en raras ocasiones) y las Características del lugar. En este último caso, defina el entorno utilizado para la nidificación, incluidas las especies vegetales dominantes presentes, su tamaño (altura o diámetro y altura del pecho) y espaciado. Incluya detalles sobre la ubicación específica del nido en sí (por ejemplo, altura del nido, especies vegetales para la colocación del nido y ubicación específica), e indique las ubicaciones de los nidos que sean atípicas.

### [Nest/Nidos]{style="color:blue;"} {#sec-app3-breeding-nest}

Comience describiendo el tipo y la forma del nido. Describa cómo se construye el nido, cuánto tiempo lleva, de dónde se recoge el material para el nido y quién construye el nido. Si se trata de una especie que anida en cavidades, describa tanto el tamaño como la forma del orificio de entrada y/o del túnel y si se construye un nido adicional en la cavidad. Al hablar de los materiales utilizados para la construcción del nido, incluya los diferentes materiales utilizados para las diferentes partes del nido, así como los tamaños de los materiales si es relevante/conocido. Las dimensiones pueden incluir (pero no se limitan necesariamente a) las dimensiones exteriores e interiores del nido, la altura y la masa.

### [Eggs/Huevos]{style="color:blue;"} {#sec-app3-breeding-eggs}

Comente cualquier adaptación o variación en la forma de los huevos. Si incluye datos sobre el tamaño/masa de los huevos o las puestas, indique los extremos de la variación normal, así como la(s) moda(s), si es posible. Mencione cualquier patrón conocido de variación asociado con la edad de la hembra, el momento estacional de la puesta o la posición del huevo en la puesta. Al igual que en el caso anterior, deben señalarse las variaciones geográficas o subespecíficas. Si puede dar mediciones del grosor de la cáscara de los huevos, incluya, si es posible, los años en que se pusieron los huevos, por si se adelgazaron por contaminantes ambientales. Para el tamaño de la puesta, indique la media, la DE o SE y el rango, recordando que el tamaño de la puesta se tratará con más detalle en Demografía y Poblaciones.

### [Incubation/Incubación]{style="color:blue;"} {#sec-app3-breeding-incubation}

El periodo de incubación suele medirse como el tiempo en días (o en horas, cuando es posible) desde la puesta del último huevo hasta la eclosión del último huevo de la nidada. Indique si sus datos se miden de forma diferente. Indique el intervalo normal y señale cualquier patrón de variación.

### [Hatching/Eclosión]{style="color:blue;"} {#sec-app3-breeding-hatching}

Esta sección abarca el periodo que va desde justo antes hasta justo después de la eclosión de los huevos. Comente cualquier comportamiento o vocalización (de los polluelos o de los padres) que se produzca antes de la eclosión, el proceso de romper la cáscara y salir del huevo, si los huevos tienden a eclosionar de forma sincrónica o asincrónica (y durante cuánto tiempo), y si los padres prestan algún tipo de ayuda para la eclosión o se deshacen de las cáscaras de los huevos.

### [Young Birds/Aves jóvenes]{style="color:blue;"} {#sec-app3-breeding-young}

Esta sección abarca la historia de las aves jóvenes desde la eclosión hasta que las plumas de vuelo juveniles están completamente desarrolladas ("volantón"; véase [el Apéndice 6](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#heading=h.m4ljq1hoco40)), fase en la que las aves son capaces de volar. El tratamiento variará necesariamente porque las especies difieren en tres aspectos principales: cantidad de plumaje velloso al nacer (psilopédico/ptilopédico), duración de la estancia en el nido (nidícolo/nidífugo) y capacidad para desplazarse y encontrar su alimento poco después de nacer (altricial/precocial). Las condiciones a lo largo de estos ejes coinciden aproximadamente, pero existen numerosas excepciones entre los no paseriformes. Debido a estas discrepancias, no se base en los términos; en su lugar, describa las condiciones en su especie. En el caso de los pollos nidífugos, añada la subsección Salida del nido (enumerada en el [Apéndice 2](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.3as4poj)bajo Etapa de volantón) en esta sección directamente después de Condición en el momento de la eclosión. Al describir el aspecto de las aves jóvenes, utilice la misma terminología para los plumajes, las partes del cuerpo y la pterilosis que para las aves de más edad. ¿Es críptico el patrón de coloración del plumón natal o del plumaje juvenil?

### [Parental Care/Cuidado parental]{style="color:blue;"} {#sec-app3-breeding-parental}

Adapte esta sección en función de si las aves jóvenes son nidícolas o nidífugas. Anote cualquier variación diaria o estacional, así como la variación geográfica de las actividades.

### [Cooperative Breeding/Cría cooperativa]{style="color:blue;"} {#sec-app3-breeding-cooperative}

Si la especie se reproduce de forma cooperativa (es decir, más de dos individuos participan en el cuidado parental), aborde este comportamiento aquí. Describa a los miembros del grupo que ayudan con el cuidado de las crías, incluyendo su parentesco con los padres de las crías que se están criando (por ejemplo, crías anteriores de uno o ambos padres, otros parientes de los padres o no parientes), sus edades y los tipos de cuidados que proporcionan (por ejemplo, construcción del nido, incubación o alimentación de los polluelos). Indique la frecuencia de cría cooperativa en varias poblaciones (por ejemplo, porcentaje de parejas que tienen ayudantes) si se conoce. La nidificación en común (en la que más de una pareja se reproduce utilizando el mismo nido) debe considerarse un tipo de reproducción cooperativa.

### [Brood Parasitism/Parasitismo de cría]{style="color:blue;"} {#sec-app3-breeding-parasitism}

Muchas especies de aves son objeto de parasitismo de cría, y algunas son ellas mismas parásitas de cría. Si procede, analice el parasitismo de las especies focales sobre sus congéneres y otras especies en las subsecciones pertinentes. La subsección Parasitismo de cría por otras especies debe tratar de las especies que parasitan a la especie focal (es decir, tratar de las situaciones en las que la especie focal es el huésped). ¿Cuáles son los principales parásitos de este hospedador, cómo reacciona el hospedador ante el parásito y cómo se ve afectado el hospedador por el parasitismo de cría? Para la subsección Éxito del parásito con este hospedador, intente dar el porcentaje de crías parasitadas que abandonan el nido.

### [Fledgling Stage/Etapa de volantones]{style="color:blue;"} {#sec-app3-breeding-fledgling}

Esta sección cubre el periodo desde la adquisición de las plumas de vuelo y la capacidad de volar hasta la independencia de los padres (y hasta el primer intento de cría si se dispone de dicha información). El tratamiento variará en función de si las aves jóvenes de su especie son nidífugas o nidícolas (por ejemplo, la subsección Salida del nido deberá indicarse en Aves jóvenes, y no aquí, para las especies nidífugas). Omita los siguientes temas porque han sido o serán incluidos en otra parte: plumajes y mudas, hábitos alimenticios, vocalizaciones y dispersión desde el lugar de nacimiento. La última subsección, Comportamiento después de la independencia, abarca el comportamiento de las aves en ese período descuidado pero crítico que va desde la obtención de la independencia hasta el primer intento de cría. Indique, si es posible, los hábitos diarios y el presupuesto de tiempo durante este periodo. Las descripciones del aspecto inmaduro deben ir en Plumajes. La supervivencia de estas aves debe tratarse en la página Demografía y poblaciones, en el apartado Duración de la vida y supervivencia.

## [DEMOGRAPHY AND POPULATIONS/DEMOGRAFÍA Y POBLACIONES]{style="color:purple;"} {#sec-app3-demography}

### [Demography and Populations (introduction)/Demografía y poblaciones (introducción)]{style="color:blue;"} {#sec-app3-demography-intro}

Un resumen general de la información demográfica sobre la especie y una breve mención de cualquier punto de especial interés. Evite las citas en esta sección.

### [Measures of Breeding Activity/Medidas de la actividad reproductiva]{style="color:blue;"} {#sec-app3-demography-measures}

Muchas medidas de éxito reproductor están mal definidas en la bibliografía. Por lo tanto, si presenta estos datos, le rogamos que utilice los términos del Glosario ([Apéndice 6](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.1302m92)): éxito de eclosión, éxito de vuelo, éxito de nidificación y éxito reproductor anual. Si desea utilizar otros términos, en particular "éxito reproductor" y "éxito de nidificación", defínalos. Una medida del éxito reproductor que parece ser importante, pero de la que rara vez se informa, es la probabilidad de que una hembra críe una o más nidadas hasta la independencia o abandone el nido durante una temporada de cría. Este valor puede calcularse dividiendo el número de hembras con éxito (según la definición anterior) de una muestra de población por el número total de hembras reproductoras de la muestra. Si puede calcular este valor, proporcione, si es posible, una estimación de la varianza.

### [Life Span and Survivorship/Tiempo de vida y supervivencia]{style="color:blue;"} {#sec-app3-demography-life}

Asegúrese de que sólo comunica medidas sólidas de supervivencia (por ejemplo, marcaje-recaptura o recaptura por anillamiento, reavistamiento o recuperación). Salvo raras excepciones, las estimaciones de supervivencia basadas en cualquier método que no incorpore estos procedimientos estadísticos no son válidas porque no diferencian las probabilidades de avistamiento de las probabilidades de mortalidad y no tienen en ficha la variación anual de la supervivencia.

Como mínimo, el colaborador debe indicar cómo se han calculado las tasas de supervivencia, pero sería mejor excluir los datos no válidos; ningún dato es siempre mejor que un dato erróneo. Incluso con estadísticas sólidas, algunas estimaciones tienen sus limitaciones. Por ejemplo, los datos de marcado y recaptura siempre confunden la emigración con la mortalidad. Por ello, siempre es necesario indicar cómo se han calculado las tasas.

### [Pathogens and Parasites/Patógenos y parásitos]{style="color:blue;"} {#sec-app3-demography-pathogens}

**Pathogens/Patógenos**

Describa y comente los patógenos (es decir, los agentes causantes de enfermedades) que se sabe que afectan a la especie. Describa tanto el agente patógeno en sí como la enfermedad asociada a él. Si es posible, facilite datos sobre la incidencia de la infección. Incluya los parásitos patógenos en esta subsección y no en la subsección Parásitos. Si procede, hable también de los vectores de la enfermedad.

**Parasites/Parásitos**

Describa y comente los parásitos internos y externos de la especie, incluidos sus efectos sobre el hospedador, si se conocen. Si es posible, facilite datos sobre la incidencia de los parásitos.

### [Causes of Mortality/Causas de mortalidad]{style="color:blue;"} {#sec-app3-demography-mortality}

Hable de las causas naturales de mortalidad en adultos y jóvenes, pero no repita la información de otras secciones, simplemente remita al lector a esas secciones.

### [Population Spatial Metrics/Métricas espaciales poblaciones]{style="color:blue;"} {#sec-app3-demography-spatial}

En esta sección se deben discutir las métricas del espaciamiento, incluyendo la distancia individual, el tamaño del territorio, el tamaño del área de campeo y la densidad de población. La distancia individual puede incluir el espacio entre nidos, la distancia entre territorios, la distancia entre aves posadas o dentro de bandadas de forrajeo, etc. Véanse las definiciones en [el Apéndice 6](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.1302m92)para las diferencias entre territorio y homerange. Los comportamientos territoriales deben incluirse en la página Comportamiento bajo Comportamiento agonístico. La densidad puede incluir medidas como el número de aves por hectárea, el número de aves por hora por red, etc.

### [Population Status/Estado de las poblaciones]{style="color:blue;"} {#sec-app3-demography-status}

A excepción de las especies poco conocidas que carecen de datos sobre el tamaño y las tendencias de la población, esta sección debe incluir las subsecciones Números y Tendencias. Para las cifras, facilite en la primera frase la estimación de población global publicada más reciente (con intervalo de confianza y años de estimación), seguida de las estimaciones para países, regiones o ecorregiones con poblaciones significativas (se prefieren las regiones ecológicas a las áreas más pequeñas definidas por fronteras políticas). Para las especies norteamericanas, consulte las [estimaciones de población del Observatorio de Aves de las Montañas Rocosas (Partners in Flight)](https://pif.birdconservancy.org/population-estimates-database/). A continuación, añada información sobre densidades o abundancia relativa dentro de los hábitats, recordando indicar la medida de densidad utilizada (por ejemplo, número de machos cantores o número de individuos). Presente los datos de los estudios del periodo reproductor antes que los de los periodos no reproductores. En la subsección Tendencias, facilite las estimaciones publicadas de los cambios de la población a lo largo del tiempo, incluyendo la estimación de la tendencia, el marco temporal (años) y el intervalo de confianza (si está disponible). Concentre los resultados de las tendencias en las zonas con poblaciones más numerosas y los datos más fiables.

### [Population Regulation/Regulación poblacional]{style="color:blue;"} {#sec-app3-demography-regulation}

Discuta aquí el impacto de los factores físicos, la competencia o la depredación en las poblaciones, señalando la variación geográfica cuando se conozca.

## [CONSERVATION AND MANAGEMENT/CONSERVACIÓN Y MANEJO]{style="color:purple;"} {#sec-app3-conservation}

### [Conservation Status/Estado de conservación]{style="color:blue;"} {#sec-app3-conservation-status}

Divida la información de esta sección en Evaluación Global (es decir, por la Lista Roja de la UICN) y Evaluaciones Regionales (es decir, por países, estados, provincias, etc.). Incluya el estado de conservación de la especie y un resumen del estado y las tendencias de la población de la especie (remita al lector a la sección Estado de la población de la página Demografía y poblaciones para más detalles). Cuando sea posible, incluya una justificación del estado de conservación de la especie. Escriba los estados de conservación oficiales (por ejemplo, de la Lista Roja de la UICN) con cada palabra en mayúscula (por ejemplo, En Peligro Crítico, Preocupación Menor), y no utilice comillas.

### [Effects of Human Activity/Efectos de la actividad humana]{style="color:blue;"} {#sec-app3-conservation-effects}

La mayoría de las subsecciones de esta sección (véase [el Apéndice 2](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.3as4poj)) se explican por sí mismas. Si la presión de la caza humana tiene efectos sobre la población, hay que tratarlos en Caza, trampeo y capturas accesorias. Los aspectos económicos e impulsores de la caza humana, así como la caza a una escala lo suficientemente pequeña como para que no afecte a las poblaciones, deben tratarse en el apartado Importancia económica y utilitaria de la página Relación con los humanos. Las "colisiones" incluyen los choques contra faros y otros edificios altos, cables eléctricos, torres de televisión y ventanas, así como los atropellos por coches, aviones, barcos, etc. 

Para cada subsección de la que se disponga de información, describa los lugares y épocas del año y la forma en que se produce la mortalidad, así como el número de individuos muertos, si se conoce. Si una subsección se ha tratado en otra sección, remita al lector allí y resuma brevemente, pero no repita, toda la información aquí.

### [Management/Manejo]{style="color:blue;"} {#sec-app3-conservation-management}

La mayoría de las subsecciones (véase [el Apéndice 2](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.3as4poj)) de esta sección se explican por sí mismas. Para las zonas de conservación, enumere y comente las zonas protegidas utilizadas por la especie. Si hay demasiadas zonas para enumerarlas todas, céntrese en las más grandes, importantes o relevantes. También puede comentar las zonas habitadas por la especie que aún no han sido protegidas pero que se beneficiarían de la protección.

## [RELATIONSHIP WITH HUMANS/RELACIONES CON EL SER HUMANO]{style="color:purple;"} {#sec-app3-humans}

### [Relationship with Humans (introduction)/Relaciones con el ser humano (introducción)]{style="color:blue;"} {#sec-app3-humans-intro}

Resumen general de la relación de la especie con el ser humano y breve mención de cualquier punto destacable. Evite las citas en esta sección.

### [Vernacular Names/Nombres vernaculares]{style="color:blue;"} {#sec-app3-humans-vernacular}

Enumere los nombres vernaculares de una especie determinada que se utilizan en su área de distribución, ordenados alfabéticamente por idioma, y comente su etimología y uso. [Avibase](https://avibase.bsc-eoc.org/avibase.jsp?lang=EN)es un excelente punto de partida para buscar estos nombres. Mencione también otros nombres comunes utilizados con regularidad/ampliamente para la misma disposición taxonómica u otras disposiciones ampliamente reconocidas, por ejemplo, en guías de campo regionales y otras listas de control importantes. Uno de los principales objetivos debe ser eliminar la confusión en la mente de los lectores que se fomenta con el uso de diferentes nombres vernáculos. No es necesario proporcionar información relativa a la etimología de los nombres científicos, ya que la información del Dictionary of Scientific Bird Names de James Jobling está disponible haciendo clic en el icono "i" situado junto al nombre de la especie en la parte superior de la página.

Nota: No es necesario proveer información sobre la etimología del nombre científico, pues la información sobre el diccionario de James Jobling de nombres científicos ya está disponible cliqueando el ícono  “i” al lado del nombre de la especie en la parte superior de la página. Si le gustaría incluir información que no esté en Jobling, por favor añadir a la sección “Systematics History”.

Tenga en cuenta que en la ficha se proporciona una lista genérica de nombres comunes en otros idiomas en forma de ventana emergente en la página de Introducción (en "Nombres" junto al estado de conservación de la especie); sin embargo, no es exhaustiva ni necesariamente representativa de todos los nombres e idiomas relevantes dentro del área de distribución de la especie. El mantenimiento de esta lista corre a cargo del grupo local de eBird, por lo que cualquier propuesta de adición o modificación debe remitirse a dicho proyecto.

### [Cultural, Symbolic, and Aesthetic Significance/Significado cultural, simbólico y estético]{style="color:blue;"} {#sec-app3-humans-cultural}

**Early History/Historia temprana**

Describa cómo se ha registrado la especie en la historia de la humanidad, incluidas las pruebas arqueológicas de la interacción de la especie con los humanos antes de la historia registrada.

**Presence in Folklore, Religion, and Symbolism/Presencia en el folclore, la religión y el simbolismo**

Hable de las apariciones de la especie en las religiones y el folclore de diferentes culturas y de los usos simbólicos de la especie (como su designación como ave nacional o su uso en una bandera).

**Depictions in Media/Representaciones en los medios de comunicación**

Menciona las representaciones de la especie en los medios de comunicación, el arte, la literatura, estampas, etc., y el impacto social de esas representaciones.

**Public Perception/Percepción pública**

Discutir la percepción pública general de la especie por parte de las comunidades en las que se da.

### [Economic and Utilitarian Significance/Significado económico y utilitario]{style="color:blue;"} {#sec-app3-humans-economic}

**Use by Humans/Uso humano**

Ejemplos de uso por parte de los seres humanos, incluidos tanto los que generalmente tienen un impacto negativo sobre la especie focal (por ejemplo, la captura, la puesta de huevos o el comercio de plumas) como los que pueden tener un impacto mixto o más positivo (por ejemplo, el turismo o, los comederos de aves). Céntrese en breves descripciones sobre la naturaleza y la historia del uso, incluida la normativa pertinente, el valor económico de ese uso y el contexto social y la percepción de ese uso. Discuta los impactos positivos o negativos relativos de ese uso sobre la especie focal. Los impactos sustanciales del uso a nivel poblacional pueden discutirse aquí pero, si son negativos, es mejor discutirlos en la página de Conservación y Gestión bajo Efectos de la Actividad Humana.

**Harm Inflicted by Focal Species/Daños infligidos por especie focal**

Discuta cualquier impacto social, medioambiental o económico negativo causado por la especie focal, por ejemplo, como plaga de cultivos, por colisiones con aeronaves o como especie invasora. Comente las medidas preventivas adoptadas contra tales efectos y sus repercusiones ecológicas y económicas.

**Aviculture and Domestication/Avicultura y domesticación**

Comente la presencia de esta especie en la avicultura, incluyendo su historia, el número de ejemplares que se crían, las regiones donde se crían, las poblaciones de origen y si está establecida la cría en cautividad. Si se trata de una especie domesticada, exponga brevemente el origen y el momento de la domesticación y los usos de las aves domésticas. No se deben incluir detalles sobre la cría.

**Use as a Research Model/Utilización como modelo de investigación**

Discuta la importancia de esta especie para la investigación científica más allá del estudio de la propia especie focal.

## [PRIORITIES FOR FUTURE RESEARCH/PRIORIDADES PARA LA INVESTIGACIÓN FUTURA]{style="color:purple;"} {#sec-app3-priorities}

Teniendo en ficha lo que sabe sobre su especie, resuma los aspectos de su biología que necesitan más estudio. Intente adoptar una perspectiva amplia en lugar de limitarse a las áreas en las que se ha centrado su propia investigación. Desde el punto de vista geográfico, ¿hay poblaciones de esta especie que se hayan descuidado? Ecológicamente, ¿hay datos que ayudarían a gestionarla mejor? ¿Qué aspectos clave de la biología de esta especie se han ignorado? Trate de limitar su discusión a 2 ó 3 párrafos, teniendo en ficha que las secciones anteriores pueden haber señalado áreas en las que faltan datos. Esta sección le da la oportunidad de resumir y discutir esas lagunas, señalando las áreas en las que los futuros investigadores deberían concentrar sus esfuerzos.

## [OTHER/OTROS]{style="color:purple;"} {#sec-app3-other}

Comente aquí cualquier aspecto de su especie que no encaje convenientemente en otro lugar y que, sin embargo, contribuya al conocimiento total de la especie.

## [ACKNOWLEDGMENTS/AGRADECIMIENTOS]{style="color:purple;"} {#sec-app3-acknowledgments}

Mencione en un párrafo a las personas o instituciones que le hayan proporcionado datos inéditos, préstamo de especímenes, referencias, ayuda de campo o de laboratorio, instalaciones especiales o apoyo financiero. Si ha tomado prestados especímenes o ha recibido servicios de una institución, mencione a la institución y a la persona que se los ha prestado.

**Nota:** Si es necesario, añada un párrafo separado para cada versión de la ficha y etiquételo como "**ficha revisada (año)**"**.**

## [ABOUT THE AUTHOR(S)/SOBRE LOS/LAS AUTORES/AS]{style="color:purple;"} {#sec-app3-authors}

Escriba una breve biografía (de un párrafo) de cada autor mencionado en la cita. La biografía debe escribirse en tercera persona. Si es posible, incluya al final una dirección de correo electrónico. Las direcciones postales no son necesarias, pero pueden utilizarse si no se dispone de correo electrónico. Procure actualizar las biografías de TODOS los autores que figuran en la cita, incluso de aquellos que no hayan contribuido a la versión más reciente de la ficha o hayan fallecido. Es posible que tenga que ponerse en contacto con los autores originales o con el personal de BOW para actualizar algunas biografías. Consulte ejemplos de fechas BOW publicados recientemente.