---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Apéndice 5: Formato de las referencias {#sec-app5 .unnumbered}

Los formatios de referencias usualmente siguen a los seguidos por *Ornithology*, *Ornithological Applications*, and *Studies in Avian Biology*.

**Nota:** Por favor, use un guión largo (–) en vez de un guión común para un rango de números de páginas (e.g., “71:296–308”). Para insertar, usar la opción guión largo en un Mac o las teclas de guión largo + ctrl en un PC.

## Artículo de revista {#sec-app5-journal}

-   Sillett, T. S., and R. T. Holmes (2002). Variation in survivorship of a migratory songbird throughout its annual cycle. Journal of Animal Ecology 71:296–308.
-   Sandercock, B. K., D. B. Lank, R. B. Lanctot, B. Kempenaers, and F. Cooke (2000). Ecological correlates of mate fidelity in two Arctic-breeding sandpipers. Canadian Journal of Zoology 78(11):1948–1958.
-   Bird, K. L., C. L. Aldridge, J. E. Carpenter, C. A. Paszkowski , M. S. Boyce, and D. W. Coltman (2013). The secret sex lives of sage-grouse: Multiple paternity and intraspecific nest parasitism revealed through genetic analysis. Behavioral Ecology 24:29–38.
-   Adreani, N. M., M. Valcu, Citizen Scientists, and L. Mentesana (2022). Asymmetric architecture is non-random and repeatable in bird’s nests. Current Biology 32:R412–R413.
-   Note que los números de volumen son opcionales.

## Libro {#sec-app5-book}

-   Marks, J. S., P. Hendricks, and D. Casey (2016). The Birds of Montana. Buteo Books, Arrington, VA, USA.
-   Peck, G. K., and R. D. James (1983). Breeding Birds of Ontario: Nidiology and Distribution. Volume 1: Nonpasserines. Royal Ontario Museum, Toronto, ON, Canada.
-   Dickinson, E. C., and J. V. Remsen Jr. (2013). The Howard and Moore Complete Checklist of the Birds of the World. 4th edition. Aves Press, Eastbourne, UK.
-   Pyle, P. (2022). Identification Guide to North American Birds. Part I. 2nd edition. Slate Creek Press, Forest Knolls, CA, USA.

## Capítulo del libro {#sec-app5-chapter}

-   Rogers, C. A., R. J. Robertson, and B. J. Stutchbury (1991). Patterns and effects of parasitism by *Protocalliphora sialia* on Tree Swallow nestlings. In Bird–Parasite Interactions: Ecology, Evolution and Behaviour (J. E. Loye and M. Zuk, Editors). Oxford University Press, Oxford, UK. pp. 123–139.
-   James, R. D. (2007). Blue-headed Vireo (*Vireo solitarius*). In The Atlas of the Breeding Birds of Ontario, 2001–2005 (M. D. Cadman, D. A. Sutherland, G. G. Beck, D. Lepage, and A. R. Couturier, Editors). Bird Studies Canada, Environment Canada, Ontario Field Ornithologists, Ontario Ministry of Natural Resources, and Ontario Nature, Toronto, ON, Canada. pp. 368–369.
-   If a volume/part and/or edition for the book is needed, place this after the book title and before the list of editors (as a new “sentence,” as it would be in the book examples above). Example:
    -   Kemp, A. C. (2001). Family Bucerotidae (hornbills). In Handbook of the Birds of the World. Volume 6: Mousebirds to Hornbills (J. del Hoyo, A. Elliott, and J. Sargatal, Editors). Lynx Edicions, Barcelona, Spain. pp. 436–523.

## Reportes técnicos del gobierno {#sec-app5-government}

-   Matthews, S. N., R. J. O’Connor, L. R. Iverson, and A. M. Prasad (2004). Atlas of climate change effects in 150 bird species of the eastern United States. USDA Forest Service General Technical Report NE-GTR-318. 
-   Balda, R. P., and N. Masters (1980). Avian communities in the pinyon-juniper woodland: A descriptive analysis. In Workshop Proceedings: Management of Western Forests and Grasslands for Nongame Birds (R. M. DeGraaf and K. E. Evans, Editors). U.S. Department of Agriculture Forest Service Intermountain Forest and Range Experiment Station General Technical Report INT-86. pp. 146–149.

## Tesis o disertación {#sec-app5-thesis}

-   Robbins, C. S. (1950). Ecological distribution of the breeding Parulidae of Maryland. M.S. thesis, George Washington University, Washington, DC, USA. 
-   Brown, C. R. (1985). The costs and benefits of coloniality in the Cliff Swallow. Ph.D. dissertation, Princeton University, Princeton, NJ, USA.

## Recurso en línea {#sec-app5-online}

-   BirdLife International (2018). Species factsheet: Red-winged Blackbird Agelaius phoeniceus. <https://datazone.birdlife.org/species/factsheet/red-winged-blackbird-agelaius-phoeniceus>
-   NatureServe (2017). NatureServe Explorer: An Online Encyclopedia of Life. Version 7.1. NatureServe, Arlington, VA, USA. <http://explorer.natureserve.org/>
-   **Note that the URL/DOI should not be included in the “Full reference” field**, only in the URL or DOI field at the bottom of the form for creating a new reference (see @sec-edit-five).

## Ficha *Birds of North America* o *Birds of the World* {#sec-app5-BNA}

-   Power, H. W., and M. P. Lombardo (1996). Mountain Bluebird (*Sialia currucoides*). In The Birds of North America, No. 222 (A. Poole and F. Gill, Editors). The Academy of Natural Sciences, Philadelphia, PA, USA, and The American Ornithologists’ Union, Washington, DC, USA. <https://doi.org/10.2173/tbna.222.p>
-   Greenlaw, J. S., C. S. Elphick, W. Post, and J. D. Rising (2018). Saltmarsh Sparrow (*Ammospiza caudacuta*), version 2.0. In The Birds of North America (P. G. Rodewald, Editor). Cornell Lab of Ornithology, Ithaca, NY, USA. <https://doi.org/10.2173/bna.sstspa.02>
-   Pantoja-Maggi, V., and C. E. Muñoz-Varela (2024). Magellanic Tapaculo (*Scytalopus magellanicus*), version 2.1. In Birds of the World (S. M. Billerman, Editor). Cornell Lab of Ornithology, Ithaca, NY, USA. <https://doi.org/10.2173/bow.magtap1.02.1>

## Recurso con los editores en lugar de con los autores {#sec-app5-editor}

-   Use “, Editor” or “, Editors” between the list of names and the year:
    -   Davidson, P. J. A., R. J. Cannings, A. R. Couturier, D. Lepage, and C. M. Di Corrado, Editors (2015). The Atlas of the Breeding Birds of British Columbia, 2008–2012. Bird Studies Canada, Delta, BC, Canada.

## Autor con sufijo {#sec-app5-suffix}

-   Buckelew, A. R., Jr. and G. A. Hall (1994). The West Virginia Breeding Bird Atlas. University of Pittsburgh Press, Pittsburgh, PA, USA.
-   Dunning, J. B., Jr., R. K. Bowers Jr., S. J. Suter, and C. E. Bock (2020). Cassin's Sparrow (*Peucaea cassinii*), version 1.0. In Birds of the World (P. G. Rodewald, Editor). Cornell Lab of Ornithology, Ithaca, NY, USA. <https://doi.org/10.2173/bow.casspa.01>
-   Kinsella, J. M., L. T. Hon, and P. B. Reed Jr. (1973). A comparison of the helminth parasites of the Common Gallinule (*Gallinula chloropus cachinnans*) and the Purple Gallinule (*Porphyrula martinica*) in Florida. American Midland Naturalist 89:467–473.
-   Telfair, R. C., II (2024). Western Cattle-Egret (*Ardea ibis*), version 1.1. In Birds of the World (P. G. Rodewald, B. K. Keeney, S. M. Billerman, and M. A. Bridwell, Editors). Cornell Lab of Ornithology, Ithaca, NY, USA. <https://doi.org/10.2173/bow.categr1.01.1>

## Notas {#sec-app5-notes}

-   Mayúsculas de los títulos en inglés:
    -   Para títulos de los artículos de revistas o reportes técnicos, colocar en mayúsculas solamente la primera palabra del título, la primera palabra después de dos puntos o un guión corto, de los nombres propios o los nombres comunes de aves (excepto palabras después de un guión largo) (incluyendo nombres no reconocidos por el eBird/Clements checklist).
    -   Notar que todas las partes de un nombre común debiese ser con mayúsculas, cuando se enlisten múltiples especies de aves (e.g., usar “Magnolia and Black-throated Blue Warblers” en vez de “Magnolia and Black-throated Blue warblers”).
    -   Para títulos de libros, las mayúsculas siguen las reglas usadas en @sec-app4-headings.
-   Al contrario del texto principal de las fichas BOW, la lista de referencias abrevia los nombres de estado de los U.S., usando las abreviaciones postales de dos letras, usando “USA” en vez de “U.S.,” y usando “Washington, DC” en vez de “Washington, D.C.”
    -   Para estados, provincias o territorios fuera de los U.S., por favor utilizar la abreviación análoga si está disponible (e.g., “Vancouver, BC, Canada,” “Sydney, NSW, Australia”).
-   Asegúrese que se utilizan los nombres completos de las revistas (e.g., use “The Auk” and not “Auk”).
-   Enlistar hasta 12 authors; si hay más de 12 autores, enlistar los primeros 11 autores seguido de un “et al.”