---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Apéndice 6: Glosario {#sec-app6 .unnumbered}

-   **Abdomen // Abdomen:** La región posterior aplanada en la parte inferior del tronco, aproximadamente desde el extremo posterior del esternón hasta el respiradero.

-   **Adult // Adulto:** Ave cuyo plumaje no cambia de aspecto en los siguientes ciclos de plumaje (es decir, definitivo). Normalmente, un individuo de este tipo es capaz de criar, pero a menudo no ocurre lo mismo; aves de muchas especies crían, algunas incluso más de una vez, antes de alcanzar el plumaje definitivo. En otros casos, las aves pueden no criar en el primer año tras adquirir el plumaje definitivo. Por lo tanto, el estado de cría en sí no es un criterio practicable para la edad adulta. En caso de posible ambigüedad, defina lo que quiere decir.

-   **Afro-Eurasia // Afroeurasia:** La masa continental que comprende África, Asia y Europa. Este término es preferible a "Viejo Mundo".

-   **Alar tract // Tracto alar:** conjunto de plumas del ala, incluidas las rémiges y sus coberteras en las caras superiores e inferiores, pero no el tracto escapulohumeral, del que está separado por el apterio humeral.

-   **Allopatric // Alopátrico:** Describe taxones que se encuentran en diferentes lugares y cuyas áreas de distribución no se superponen.

-   **Alternate plumage // Plumaje alterno:** Nombre del segundo plumaje cuando hay dos plumajes por ciclo de plumaje. El primer plumaje (es decir, el plumaje básico) suele ser una muda más completa y suele dar lugar a un plumaje de color menos brillante/conspicuo que el plumaje alternativo. Puede ser numerado como primero, segundo, etc., para designar los cambios de color y de patrón de muda hasta alcanzar el estadio definitivo. Adquirido por una muda prealterna que generalmente reemplaza sólo las plumas del cuerpo, no las remiges ni las rectrices.

-   **Altricial // Altricial:** Carácter de un ave joven que está indefensa cuando nace y requiere una crianza considerable antes de poder abandonar el nido. Al nacer, el polluelo está desnudo o tiene poco vello y los ojos cerrados.

-   **Alular digit // Dedo alular:** Dedo anterior del ala, representado por un solo hueso corto en el borde anterior del carpometacarpo. Antiguamente llamado pollex.

-   **Alular quills // Plumas alulares**: Pequeñas plumas de contorno, estrechas y rígidas, unidas al dígito alular en la parte superior de la muñeca. Colectivamente conocidas como alula o ala bastarda.

-   **Amplitude // Amplitud:** Desviación máxima de la presión atmosférica con respecto a la presión ambiente en un ciclo de una onda sonora. Es una medida objetiva del sonido, pero no es equivalente a la "sonoridad" (q.v.).

-   **Anisodactyl // Anisodáctilo:** Disposición de los dedos de los pies en la que el hallux está detrás y los otros tres dedos delante, como en los paseriformes.

-   **Annual reproductive success // Éxito reproductor anual:** Medida de la producción reproductora de una muestra de población en una temporada, calculada como el número de crías criadas dividido por el número de hembras reproductoras de la población, o como el número de crías criadas hasta la salida del nido dividido por el número de hembras de la muestra (especificar). Esto debe distinguirse claramente del éxito reproductor a lo largo de la vida, es decir, el número de crías de un individuo que sobreviven en un momento dado.

-   **Apterium (plural: apteria) // Apterium (plural: apteria):** Zona del cuerpo sin plumas de contorno, desnuda o escasamente provista de plumas de plumón o semiplumas.

-   **Attenuation // Atenuación:** Disminución de la amplitud de una señal durante su transmisión de un lugar a otro.

-   **Auriculars // Auriculares:** Parche de plumas que rodea la abertura de la oreja y a menudo la apantalla. Pueden ser de textura más gruesa que las plumas adyacentes del contorno. Sinónimo: coberteras auriculares.

-   **Back // Espalda:** Los dos tercios anteriores de la región situada en la parte superior del tronco, entre la base del cuello y la base de la cola.

-   **Basic plumage // Plumaje básico:** Nombre del plumaje adquirido generalmente por una muda completa en los adultos (generalmente cerca o después de la reproducción), y por una muda incompleta en los jóvenes, en un plumaje "no reproductor", pero hay algunas excepciones. Pueden numerarse como primero, segundo, etc., para designar los cambios de color y de dibujo hasta alcanzar el estado definitivo. Adquirido por una muda prebásica. Si el ciclo del plumaje consta de una sola generación, siempre es básico.

-   **Booted // Enraizado:** Carácter de la cubierta córnea del tarso en el que es lisa, sin escamas ni placas.

-   **Boreal // Boreal:** Perteneciente a las regiones templadas frías o frescas del hemisferio norte, la zona septentrional de coníferas y la taiga.

-   **Breast // Pecho:** Región anterior y redondeada situada en la parte inferior del tronco, entre el borde inferior del yugulum y el extremo posterior aproximado del esternón.

-   **Breeding site fidelity // Fidelidad al lugar de cría:** Tendencia de un ave a reproducirse consecutivamente en el mismo lugar.

-   **Bristle // Cerda:** Pluma con un raquis rígido y cónico y púas sólo a lo largo de la porción proximal. Las "semicerdas" son intermedias entre las cerdas y las plumas de contorno, tienen un raquis conspicuo, barbas a lo largo de todo el raquis pero muy espaciadas cerca de la punta, y bárbulas muy pequeñas o ausentes en la mayoría de las barbas.

-   **Calls // Llamadas:** Manifestaciones vocales; sonidos estereotipados utilizados en la comunicación. Generalmente, las llamadas son cortas y simples, mientras que los cantos son largos y complejos, pero la distinción no es exacta. Además, las llamadas pueden producirse en cualquier momento, mientras que los cantos suelen emitirse principalmente en la época de cría. Una especie suele tener entre 5 y 20 llamadas.

-   **Canopy // Dosel:** estrato superior del follaje en la vegetación forestal; formado por las copas de los árboles y subdividido en dos o tres niveles en las selvas tropicales.

-   **Capital tract // Tracto capital:** La pteryla que se extiende sobre la parte superior de la cabeza desde la base de la mandíbula superior posteriormente hasta el punto donde la cabeza y el cuello se unen. Está delimitada a cada lado por una línea imaginaria que va desde la rama mandibular hasta el ángulo de la mandíbula. Puede subdividirse en tractos subordinados.

-   **Caudal tract // Tracto caudal:** Todas las plumas de la cola, incluidas las rectrices, las coberteras supracaudales y subcaudales, y cualquier plumaje de la glándula uropigial.

-   **Chick // Polluelo**: Etapa de la vida de un ave joven precoz, es decir, bien cubierta de plumón, que abandona el nido y es capaz de alimentarse por sí misma.

-   **Chin // Barbilla:** Zona, generalmente emplumada, en la horquilla de la parte inferior del pico. Sinónimo: región interramal.

-   **Commissure // Comisura:** Línea que une las mandíbulas. El lugar a cada lado de la boca donde se juntan las mandíbulas es el "punto comisural" (sinónimo: ángulo de la boca).

-   **Communal singing // Canto comunal:** Canto interactivo de los miembros de un grupo social.

-   **Complete body molt // Muda completa del cuerpo:** Sustitución de todas las plumas del contorno (cuerpo) pero ninguna pluma de vuelo (remiges o rectrices).

-   **Complete molt // Muda completa:** Sustitución de todas las plumas del cuerpo y del vuelo. 

-   **Continental shelf // Plataforma continental:** Lecho marino poco profundo, de pendiente gradual, que rodea un margen continental, no suele tener más de 200 m de profundidad y está formado por la inmersión de parte del continente. Más allá de ella, el talud continental cae abruptamente hacia el fondo del océano.

-   **Contour feather // Pluma de contorno:** Pluma con alas planas, estrechamente tejidas, que forma la cubierta exterior del cuerpo; no incluye las plumas de vuelo (remiges y rectrices).

-   **Cooperative polyandry // Poliandria cooperativa:** Sistema de apareamiento en el que una sola hembra y un grupo de machos forman una unidad reproductora comunal en la que todos los machos tienen la oportunidad de aparearse.

-   **Countersinging // Contrarréplica:** "Contrarréplicas", a veces alternadas y a veces solapadas, del canto de dos o más individuos que se responden mutuamente.

-   **Coverts // Coberteras:** Plumas de contorno que recubren o subyacen a las bases de las rémiges y rectrices y cubren el resto del ala o la cola; suelen ser más pequeñas que las plumas de vuelo.

-   **Crown // Corona:** Región posterior y superior de la cabeza, detrás de una línea imaginaria que une los ángulos anteriores de los ojos. Adjetivo: coronal.

<!-- -->

-   **Crural tract // Tracto** **crural**: La pluma de la pierna por debajo de la rodilla, separada del tracto femoral por un estrecho apterio.

-   **Culmen // Culmen:** Cresta de la mandíbula superior, desde la frente hasta la punta del pico.

-   **Cycle // Ciclo:** Sonido: Repetición completa de una forma de onda. Reproducción: Periodo que va desde el cortejo hasta la cría de las crías independientes (o fracaso reproductivo).

-   **Decibel // Decibelio (dB):** Unidad utilizada para comparar la intensidad de dos sonidos. La escala de decibelios es logarítmica. Un decibelio corresponde a una relación de intensidad de 1,26 aproximadamente, 3 decibelios a una relación de 2 aproximadamente y 10 decibelios a una relación de 10 exactamente. Las mediciones en decibelios deben referirse a la base sobre la que se calculan. En la mayoría de los casos, la unidad de referencia es 20 micropascales (o equivalentes), pero puede calcularse de otra forma.

-   **Definitive // Definitivo:** Típicamente, plumaje "adulto". Estado de un plumaje tal que no cambia más con la edad, es decir, los plumajes en la misma fase de los ciclos de plumaje posteriores son idénticos. Puede aplicarse a plumajes básicos, alternos o suplementarios.

-   **Degradation // Degradación:** Cambio en la forma de un sonido a medida que viaja desde su fuente. Está causada por la atenuación diferencial de las distintas frecuencias del sonido, la refracción del sonido que atraviesa volúmenes de aire de distintas densidades, la reflexión del sonido en las superficies y la difracción del sonido que atraviesa huecos y rodea barreras.

-   **Dialect // Dialecto:** Variación microgeográfica de una señal sonora resultante de la imitación por parte de los miembros de una población local. A menudo pueden identificarse fronteras nítidas entre los dialectos locales, aunque los límites pueden diferir en función de las características que se tengan en ficha para trazar dichas fronteras.

-   **Dispersal // Dispersión:** Acto o proceso por el que los individuos se desplazan desde su lugar de nacimiento hasta un lugar de reproducción (potencial).

-   **Dispersion // Dispersión:** Ecología: Patrón de distribución de los individuos dentro de una población, como agrupados o agregados, uniformes o aleatorios. Estadística: Distribución o dispersión de observaciones en torno a la media o valor central.

-   **Dorsal tract // Tracto dorsal:** Pterola que se extiende posteriormente desde el tracto capital hasta las coberteras supracaudales. A lo largo del cuello, está bordeado a cada lado por un apterio cervical; a lo largo del tronco, está bordeado a cada lado por un gran apterio lateral. El tracto dorsal se divide en cuatro regiones: la "región cervical", desde la cabeza hasta el tronco; la estrecha "región interescapular", que se extiende posteriormente entre los omóplatos; la "región dorsal", en forma de silla de montar, desde los omóplatos hasta un punto situado aproximadamente a medio camino de la cola; y la amplia "región pélvica", entre las caderas, desde la región dorsal hasta las coberteras de la cola.

-   **Down feather // Pluma de plumón:** Término general para designar una pluma esponjosa o laxa en la que el raquis suele ser corto o inexistente, al menos más corto que la púa más larga. Existen dos categorías principales. (1) "Plumones natales": en aves recién nacidas de muchas especies (sinónimo: plumones de polluelos); incluyen el neosóptilo (primer plumón natal) y el mesóptilo (segundo plumón natal). (2) "Plumones definitivos": en aves inmaduras y adultas, bajo las plumas de contorno (sinónimo: plumones adultos). El "plumón" puede aplicarse tanto a las plumas individuales como al plumaje compuesto por ellas.

-   **Duetting // Duetos:** Sonidos superpuestos, vocales o no, emitidos por los miembros de una pareja o de un grupo familiar. El grado de precisión de las contribuciones de los participantes varía.

-   **Egg dumping // Puesta de huevos:** Puesta de huevos en el nido de otra hembra (normalmente de la misma especie) sin ocuparse de ellos ni de las crías resultantes. Sinónimo: vertedero.

-   **Eurasia // Eurasia:** Área continental que comprende Europa y Asia.

-   **Eyering // Ojera:** Anillo de plumas alrededor del ojo, a menudo coloreado. Se distingue del "anillo orbital" (q.v.).

-   **Feather coat // Plumaje:** El complemento total de plumas de un ave en un momento dado, independientemente de cuántas generaciones de plumas (plumajes) se combinen para producir esa apariencia. Por ejemplo, el plumaje de muchas aves durante la época de cría comprende plumajes básicos y alternativos.

-   **Female access polyandry // Poliandria de acceso de las hembras:** Sistema de apareamiento en el que las hembras no defienden los recursos esenciales para los machos, sino que a través de interacciones entre ellas pueden limitar el acceso a los machos. El sistema se asemeja más a un ensamblaje reproductivo explosivo (Emlen y Oring 1977) en el que la proporción operativa de sexos puede sesgarse con un exceso de hembras.

-   **Female (or harem) defense polygyny // Poliginia de defensa de la hembra (o harén):** Sistema de apareamiento en el que machos individuales controlan directamente el acceso a varias hembras, normalmente en virtud del gregarismo femenino.

-   **Femoral tract // Tracto femoral**: Tracto situado en la superficie externa de cada muslo, desde la rodilla (y la cadera) casi hasta el ventrículo.

-   **Filoplume // Filopluma:** Pluma delgada, parecida a un pelo, con un pequeño penacho de púas o bárbulas en la punta.

-   **Flank // Flanco:** Región situada a ambos lados del tronco, dorsolateral al abdomen.

-   **Fledge // Primer vuelo:** Proceso de adquisición de las plumas necesarias para el vuelo y la capacidad de volar. Una vez completado, el ave es volantona. No es sinónimo de salida del nido. No se aplica el término al proceso parental de crianza de las crías hasta que pueden volar.

-   **Fledging success // Éxito de vuelo:** Medida de la producción reproductora en una muestra de población, calculada como la fracción o porcentaje del total de huevos puestos que produjeron crías que abandonaron el nido, incluidas las nidadas adicionales, si las hubiera.

-   **Fledgling // Volantón:** Etapa de la vida de un ave altricial desde que abandona el nido hasta que se independiza de sus padres. El término se limita a las especies en las que las crías no abandonan el nido hasta que están completamente emplumadas y listas para volar.

-   **Forehead // Frente:** Región anterior y superior de la cabeza, por encima de los lores, que se extiende hacia arriba y hacia atrás desde el pico hasta una línea imaginaria que une los ángulos anteriores de los ojos. Adjetivo: frontal.

-   **Forest // Bosque:** Zona relativamente extensa de árboles con copas estrechas, principalmente de más de 5 m de altura. Una pequeña masa de árboles puede denominarse arboleda.

-   **Formative Plumage // Plumaje Formativo:** Plumaje nuevo en el primer ciclo entre el plumaje juvenil (primer básico) y el siguiente plumaje alternativo o básico.

-   **Fourier analysis // Análisis de Fourier:** Técnica de análisis de sonidos en la que se muestrea una onda a una frecuencia relativamente alta (al menos 2,5× la frecuencia más alta que se puede resolver) y se asigna un valor digital específico al valor de la onda en cada uno de esos puntos. A continuación, la información digitalizada se somete a un análisis de Fourier que proporciona un espectro sonoro que aparece como frecuencia en el eje x y amplitud en el eje r. Por lo tanto, cada espectrograma sonoro representa un corte temporal del sonido que ofrece una representación razonablemente precisa de la frecuencia y la amplitud en un instante determinado. La duración de ese instante varía en función de la gama de frecuencias a muestrear.

-   **Frequency // Frecuencia:** Número de ciclos completos de un proceso periódico que se producen por unidad de tiempo. Parámetro de una onda sonora, es una medida objetiva y, por tanto, no equivalente al "tono" (q.v.). Suele medirse en número de ciclos/segundo = hercios (Hz). La fundamental es la frecuencia más baja de una serie armónica.

-   **Gonys // Gonis:** La cresta formada por la unión de las dos ramas de la mandíbula inferior cerca de su punta.

-   **Grassland // Pastizal:** Comunidad biótica principal de las regiones templadas, formada por terrenos llanos a ondulados, desarbolados y cubiertos de hierba. El clima está sujeto a cambios estacionales bruscos, con inviernos de fríos a muy fríos y precipitaciones de moderadas a escasas.

-   **Gular region // Región gular:** Región de la parte inferior de la cabeza que continúa desde el mentón hasta una línea imaginaria entre los ángulos de la mandíbula.

-   **Habituation // Habituación:** Disminución de la respuesta a un estímulo con el paso del tiempo.

-   **Hallux // Hallux:** El primer dedo del pie, generalmente dirigido hacia atrás y reducido, a veces ausente.

-   **Harmonics // Armónicos:** Componentes de una onda periódica que son múltiplos integrales de la frecuencia más baja (o fundamental), que es el primer armónico; el componente cuya frecuencia es el doble de la fundamental es el segundo armónico, y así sucesivamente. Los armónicos pueden ser sobretonos, pero los sobretonos no son armónicos. La frecuencia del sobretono se deriva de la fundamental, pero la relación matemática con ésta no es sencilla.

-   **Hatching success // Éxito de eclosión:** Medida de la producción reproductora en una muestra de población, calculada como la fracción o el porcentaje del número total de huevos puestos que eclosionaron, incluidas las nidadas adicionales, si las hubiera. Debe distinguirse de la tasa de eclosión, que es la fracción o porcentaje de nidos de una muestra observada en los que eclosionó al menos un huevo.

-   **Heterodactyl // Heterodáctilo:** Disposición de los dedos en la que el tercero y el cuarto están delante y el primero (hallux) y el segundo detrás, como en los trogones.

-   **Home range // Homerange:** Área total que ocupa un ave durante la estación reproductora o durante la no reproductora, pero excluyendo el área recorrida durante la migración o la dispersión. Puede (1) ser lo mismo que "territorio" (q.v.), (2) ser el territorio más un área exterior que el ave freficha para alimentarse u otras necesidades, o (3) no contener territorio.

-   **Immature // Inmaduro:** Término general para cualquier ave joven desde el momento en que adquiere el plumaje juvenil hasta que adquiere el plumaje completamente adulto (es decir, definitivo). No significa inmadurez sexual a menos que se especifique lo contrario, ya que los inmaduros de algunas especies pueden ser capaces de reproducirse. Inmaduro es sinónimo de juvenil, salvo que este último connota inmadurez sexual.

-   **Inshore // Costera:** Zona costera definida arbitrariamente a 5 km de la línea de bajamar. Cuando hay islas o islotes a la vista de la costa, todas las aguas intermedias y la zona hasta 5 km más allá de ellas deben incluirse como costeras, al igual que los mares de una profundidad inferior a 15 cm.

-   **Intensity // Intensidad:** Potencia suministrada por unidad de superficie en una onda sonora. La intensidad suele expresarse en decibelios (q.v.) en relación con 1.012 W/m2, que es aproximadamente el umbral de audición humana.

-   **Interspecific territoriality // Territorialidad interespecífica:** Comportamiento agresivo persistente mostrado por el poseedor de un territorio de una especie hacia miembros de otra especie. Implica algunos, si no todos, los comportamientos que suelen darse en los encuentros intraespecíficos.

-   **Iris (plural: irises or irides) // Iris (plural: iris o irides):** Membrana delgada situada en la parte anterior del ojo que, por su estado de contracción, determina el tamaño de la abertura (pupila) en su centro.

-   **Jugulum // Jugulum:** Región situada en la parte inferior del cuello, desde el margen posterior de la región gular hasta el tronco.

-   **Juvenile Plumage // Plumaje juvenil:** La primera generación de plumas de contorno verdaderas (pennáceas). Las plumas suelen estar menos entretejidas y tener un color diferente al de las siguientes. Adquirido por la muda prejuvenil (es decir, sustitución del plumón natal en las especies que tienen un plumaje velloso). Equivale al primer plumaje básico.

-   **Kilohertz (kHz) // Kilohercio (kHz):** Unidad de medida de la frecuencia de las ondas sonoras; equivalente a 1.000 Hz, o 1.000 ciclos por segundo.

-   **Lek // Lek:** Terreno de exhibición comunal en el que se reúnen los machos con el único fin de atraer y cortejar a las hembras y al que éstas acuden para aparearse. Sinónimo: arena. El término también puede aplicarse a una exhibición prenupcial comunal en una zona de este tipo, concretamente una que implique competiciones ritualizadas entre competidores, a menudo para la subida de lugares simbólicos.

-   **Littoral: // Litoral:** (1) La orilla de un lago hasta una profundidad de unos 10 m. (2) La zona intermareal de la orilla del mar, ampliada o empleada alternativamente para aguas no mareales, para incluir el límite submarino hasta el que pueden crecer las plantas adheridas más abundantes, a veces hasta una profundidad de 3 m o más, correspondiente a la penetración de la luz. Puede, por tanto, solaparse con la zona costera a niveles subsuperficiales.

-   **Lobate // Lobulado:** Carácter de un pie nadador con una serie de lóbulos laterales en los dedos, como en los somormujos. A veces el pie puede ser palmeado, pero el hallux puede llevar un lóbulo, como en los patos buceadores.

-   **Lore // Lore:** La zona entre el párpado y el eyering y la base de la parte superior del pico.

-   **Loudness // Sonoridad:** Percepción de la intensidad de un sonido. Para los sonidos que sólo difieren en amplitud, la sonoridad relativa está directamente relacionada con la intensidad relativa, pero para los sonidos que difieren en frecuencia y caracteres temporales, la sonoridad es un fenómeno psicofísico complicado. No sólo depende de las características de la forma de onda estimulante, sino también de las propiedades de reacción del sistema mecánico receptor (oído) y de los análisis neurológicos. La sonoridad relativa de los distintos sonidos puede ser diferente para los seres humanos y las distintas especies de aves.

-   **Macrogeographic variation // Variación macrogeográfica:** Variación a lo largo de distancias geográficas lo suficientemente grandes como para que las aves de esos lugares tengan un contacto mínimo entre sí, generalmente del orden de cientos o miles de kilómetros. Puede referirse a características del cuerpo, huevos, hábitos o sonidos.

-   **Major digit // Dígito mayor:** Dedo principal del ala, representado por las dos falanges en línea con el carpometacarpo.

-   **Malar region // Región malar:** Región lateral de la cabeza que va desde la base de la parte inferior del pico hasta el ángulo de la mandíbula; está limitada por encima por el lore, la región orbitaria y la región auricular y por debajo por el borde de la mandíbula inferior.

-   **Male dominance polygyny // Poliginia de dominación masculina:** Sistema de apareamiento en el que las parejas o los recursos críticos no pueden ser monopolizados económicamente. Los machos compiten por las hembras repartiéndose las posiciones de dominio y/o demostrando directamente su calidad mediante exhibiciones.

-   **Mantle // Manto:** Se utiliza cuando el dorso, los escapularios y las coberteras alares presentan en conjunto una zona de color distintivo.

-   **Mate // Pareja:** Individuo con el que otro individuo comparte gametos. (Una pareja puede estar emparejada o no).

-   **Mean // Media:** Media; igual a la suma de las observaciones dividida por el número de observaciones (denotado como estadístico de una muestra por x, y como parámetro de una población por µ; media aritmética).

-   **Mesoptile // Mesóptilo:** Plumas del segundo plumaje velloso en las especies que lo tienen.

-   **Microgeographic variation // Variación microgeográfica:** Variación a una escala geográfica lo suficientemente pequeña como para que pueda esperarse que las aves jóvenes se dispersen de un lugar a otro, generalmente del orden de unos pocos kilómetros. Suele utilizarse en referencia a las vocalizaciones.

-   **Migration // Migración:** Desplazamiento regular de un individuo o grupo entre áreas de distribución estacionales separadas geográficamente. Dentro de una especie, las poblaciones pueden variar en el alcance de su migración, y dentro de una población, los individuos pueden variar del mismo modo.

-   **Migratory restlessness // Inquietud migratoria:** Comportamiento inquieto de las aves inmediatamente antes de partir en migración, también llamado inquietud premigratoria o el término original en alemán, "Zugunruhe".

-   **Mimicry // Mimetismo:** Gran parecido de un organismo (el imitador) con otro (o con un objeto natural, el modelo) para engañar a un tercero (el operador). Puede aplicarse a la apariencia interespecífica o al aprendizaje del sonido (q.v.).

-   **Minor digit // Dedo menor:** Dedo posterior del ala, representado por una única falange pequeña situada detrás del extremo proximal de la falange basal del dedo principal.

-   **Modulation // Modulación:** Cualquier cambio periódico en la frecuencia, amplitud o fase de una onda sonora.

-   **Molt // Muda:** Pérdida periódica de una parte o de la totalidad del plumaje y sustitución de éste por una generación de plumas u otros derivados tegumentarios, ya se trate de la totalidad o sólo de una parte del ave. Las mudas se denominan en relación con el plumaje entrante, es decir, prebásica, prealterna, etc. Una muda puede ser limitada en el tiempo, prolongada o incluso interrumpida. También puede ser completa (es decir, renovar todos los tractos) o parcial (es decir, renovar sólo algunos tractos).

-   **Molt migration // Migración de muda:** Desplazamiento regular de ciertas especies desde las zonas de cría a zonas protegidas donde mudan.

-   **Monogamy // Monogamia:** Relación de apareamiento en la que un macho o una hembra se aparean con un solo individuo durante el periodo de un ciclo reproductivo.

-   **Nape // Nuca:** Región de la parte superior del cuello, desde el margen posterior de la coronilla hasta el tronco.

-   **Natal Down // Plumón natal:** Plumaje de plumón, escaso o abundante, que viste por primera vez a un polluelo y que está presente en el momento de la eclosión o aparece a los pocos días. Las aves de algunos órdenes tienen dos generaciones sucesivas de plumones natales. Pérdida por muda prejuvenil.

-   **Natal philopatry // Filopatría natal:** Tendencia de un ave madura a regresar al lugar de eclosión para su primer esfuerzo reproductor.

-   **Neossoptile (neoptile) // Neosóptilo (neoptile):** Plumas del primer (generalmente único) plumaje velloso.

-   **Nest success // Éxito de nidificación:** Medida de la producción reproductora en una muestra de población, calculada como la fracción o porcentaje del total de nidos que produjeron crías que abandonaron el nido, incluidas las nidadas adicionales, si las hubiera. En contraste con "éxito de volantones" (q.v.).

-   **Nestling // Anidamiento:** Etapa de la vida de un ave joven mientras permanece en el nido.

-   **Nomadic // Nómada**: Característica de los individuos que se desplazan irregularmente de un lugar a otro en respuesta a las lluvias, la sequía o la aparición de alimentos.

-   **Non-native species // Especie alóctona:** Especie que vive fuera de su área de distribución nativa y que ha llegado allí por la actividad humana, ya sea deliberada o accidental.

-   **Nonvocal sounds // Sonidos no vocales:** Sonidos producidos por el pico, las patas o las plumas, tal vez utilizados para la comunicación. Sinónimo: sonidos mecánicos.

-   **Notched // Muesca:** Carácter de un remex primario en el que uno o ambos álabes están incisos hacia la punta. Sinónimo: emarginado.

-   **Note // Nota:** Tono único de tono definido. El término suele utilizarse de forma más amplia en referencia a un único trazo continuo en un espectrograma sonoro. Sinónimos: teléfono, figura y elemento. Si utiliza estos sinónimos, defínalos sin ambigüedad.

-   **Occiput // Occipucio:** Porción posterior de la corona (q.v.), que no suele distinguirse a menos que el plumaje difiera del de las regiones adyacentes. Adjetivo: occipital.

-   **Offshore // Mar adentro:** La zona costera que se extiende desde los límites de las aguas costeras hasta el borde de la plataforma continental o el talud continental.

-   **Operculum // Opérculo:** Colgajo córneo que cubre la fosa nasal.

-   **Orbital ring // Anillo orbital:** Anillo de piel desnuda alrededor del ojo. Se distingue del "eyering" (q.v.).

-   **Palmate // Palmado:** Carácter de los dedos de los pies en el que los tres anteriores están unidos por extensas membranas, como en los patos y las gaviotas. Sinónimo: palmeado.

-   **Pamprodactyl // Pamprodáctilo:** Disposición de los dedos de los pies en la que los cuatro se encuentran delante, estando el hallux girado hacia delante, como en los vencejos.

-   **Parapatric // Parapátrico:** Describe taxones cuyas áreas de distribución son adyacentes, pero no se superponen significativamente.

-   **Pelagic // Pelágico:** Zona del océano profundo, más allá del talud continental.

-   **Pennaceous // Penáceas:** Plumas en las que las barbas de cada aspa son paralelas y están entrelazadas entre sí mediante bárbulas en barbas adyacentes, es decir, las típicas plumas del cuerpo.

-   **Phrase // Frase:** Segmento aparentemente natural de una canción, como una secuencia de sílabas similares o un grupo de notas disímiles delimitadas por sílabas repetidas o por el principio o el final de una canción. Alternativamente, el término puede referirse a la unidad repetida ("sílaba") en una canción. Defina sin ambigüedades el uso que hace de este término.

-   **Pitch // Tono:** Percepción de la frecuencia relativa de un sonido, que depende de la frecuencia, el volumen y la intensidad. Para los sonidos con una frecuencia fundamental y una serie armónica, el tono corresponde a una frecuencia (al menos en los humanos), pero para otros sonidos la percepción del tono es un proceso psicofísico complicado. A diferencia de la frecuencia, el tono puede modificarse en función de las características del sistema receptor. El tono de los sonidos puede ser percibido de forma diferente por los seres humanos y las distintas especies de aves, e incluso por los distintos individuos de una misma especie.

-   **Plumage // Plumaje:** Una sola generación de plumas, resultado de una sola muda. Los plumajes se denominan plumón natal, juvenil, formativo, básico, alterno y suplementario. El plumaje total que luce un ave (lo que se suele considerar su "plumaje") suele estar compuesto por varios plumajes y se denomina plumaje.

-   **Plumage cycle // Ciclo del plumaje:** Periodo en un ave "adulta" que se extiende desde un determinado plumaje o muda hasta la siguiente aparición del mismo plumaje o muda. Dura un año en la mayoría de las especies de zonas templadas, pero es más corto en algunas especies tropicales y oceánicas y más largo en unas pocas especies de diversas latitudes.

-   **Polyandry // Poliandria:** Relación de apareamiento en la que una hembra se aparea con dos o más machos monógamos durante un ciclo reproductivo.

-   **Polygyny // Poliginia:** Relación de apareamiento en la que un macho se aparea con dos o más hembras monógamas cuyos ciclos reproductivos se solapan.

-   **Polygynandry // Poliginandria:** Relación de apareamiento en la que tanto machos como hembras se aparean con dos o más miembros del sexo opuesto durante un mismo ciclo reproductivo.

-   **Powder-down feather // Pluma de plumón:** Pluma modificada, normalmente con la estructura de un plumón, que produce un polvo fino parecido al talco por la proliferación y queratinización de las células que rodean las barbas en el germen de la pluma. En las distintas especies, este tipo de plumas se encuentran dispersas entre los plumones ordinarios y las plumas de contorno o agrupadas en zonas específicas denominadas "manchas de plumón".

-   **Precocial // Precoz:** Lo contrario de altricial (q.v.). Nace con una gruesa capa de plumón, se desplaza poco después de nacer y requiere pocos cuidados parentales directos.

-   **Prealternate molt // Muda prealterna:** La muda que trae el plumaje alternativo, si lo hay.

-   **Prebasic molt // Muda prebásica:** La muda que trae el plumaje básico, comúnmente tomada como el punto de partida de un ciclo de plumaje.

-   **Preformative Molt // Muda preformativa:** La muda que trae el Plumaje Formativo, si lo hay.

-   **Prejuvenile Molt // Muda prejuvenil: La muda que trae el Plumaje Juvenil. Equivale a la primera muda prebásica.**

-   **Presupplemental Molt // Muda suplementaria:** La muda que trae el Plumaje Suplementario, si lo hay; puede seguir a un plumaje básico o a un plumaje alternativo.

-   **Psilopaedic // Psilopaédica:** eclosiona desnuda (con poco o ningún plumón).

-   **Pteryla (plural: pterylae) // Pterola (plural: pterylae):** Zona del cuerpo que presenta hileras de plumas de contorno. Sinónimo: tracto.

-   **Ptilopaedic // Ptilopédico:** Nace con una densa capa de plumón.

-   **Rachis // Raquis: Eje central de una pluma al que se unen las púas.**

-   **Rami (mandibular) (singular: ramus) // Rama (mandibular) (singular: ramus):** Las dos mitades de la mandíbula inferior, separadas por tejido blando cerca de la base (comisura) pero uniéndose anteriormente en la gónada.

-   **Rapid double-clutch monogamy // Monogamia rápida de doble puesta:** Relación de apareamiento en la que una hembra pone dos nidadas seguidas, una incubada por su pareja y la otra por ella misma.

-   **Rapid multiple-clutch polygamy // Poligamia rápida de puestas múltiples:** Relación de apareamiento en la que una hembra pone al menos dos nidadas con diferentes compañeros y el macho fecunda al menos dos nidadas para diferentes compañeros en rápida sucesión. Machos y hembras incuban nidadas separadas.

-   **Raptorial // Rapaz:** Carácter de los dedos de los pies, profundamente hendidos, con uñas grandes, fuertes y muy curvadas, como en los halcones.

-   **Rectrices (singular: rectrix) // Rectrices (singular: rectrix)**: Plumas de vuelo de la cola.

-   **Remiges (singular: remex) // Remiges (singular: remex)**: Las plumas largas y rígidas que sobresalen posteriormente de las alas, ancladas a los huesos de la extremidad anterior. Dos series principales: las rémiges primarias ("primarias") se fijan a los huesos de la mano, y las rémiges secundarias ("secundarias") se fijan al cúbito. Las terciarias verdaderas (no las secundarias internas), si las hay, se fijan al húmero.

-   **Repertoire // Repertorio:** variedad de sonidos que utiliza un individuo para comunicarse. A menudo se refiere en un sentido más restringido a la diversidad de tipos de canto que utiliza un ave individual.

-   **Resident // Residente:** Característica de una especie o población que es básicamente no migratoria.

-   **Resource defense polyandry // Poliandria de defensa de recursos:** Sistema de apareamiento en el que las hembras controlan el acceso a los machos de forma indirecta, monopolizando los recursos críticos.

-   **Resource defense polygyny // Poliginia de defensa de recursos:** Sistema de apareamiento en el que los machos controlan el acceso a varias hembras de forma indirecta, monopolizando los recursos críticos.

-   **Reticulate // Reticulado:** Carácter de la cubierta córnea del tarso en el que se forma en pequeñas placas irregulares.

-   **Rictus // Rictus:** Porción posterior blanda y carnosa del tomium, cerca del punto comisural.

<!-- -->

-   **Riparian woodland // Bosque ribereño:** Comunidad biótica, principalmente de árboles caducifolios, cerca de arroyos o tierras bajas donde hay un suministro adecuado de agua subsuperficial; especialmente prominente en las secciones más áridas del suroeste de Estados Unidos.

-   **Rump // Rabadilla:** Tercio posterior de la región situada en la parte superior del tronco, entre la base del cuello y la base de la cola. Sinónimo: región pélvica.

-   **Savanna // Sabana**: Comunidad biótica de pastizales tropicales y subtropicales, de transición entre los pastizales o el desierto y la selva tropical, típicamente con vegetación resistente a la sequía dominada por gramíneas con árboles altos dispersos; tiende a ser semiárida con pocos o ningún humedal y debe ser al menos seminatural y en extensiones considerables.

-   **Scapulohumeral tract // Tracto escapulohumeral:** Pterola estrecha en la cara superior de cada hombro, a través de la articulación o justo distal a ella.

-   **Sclerophyll // Esclerófilo: Tipo de vegetación adaptada a condiciones cálidas y secas. Las plantas esclerófilas suelen tener hojas pequeñas y resistentes.**

-   **Scutellate // Escutelado:** Carácter de la cubierta córnea del tarso en el que se forma en escamas más o menos superpuestas.

-   **Scutellate-booted // Escutelado:** Carácter de la cubierta córnea del tarso en la que presenta escamas superpuestas por delante pero lisas por detrás.

-   **Scutellate-reticulate // Escutelado-reticulado:** Carácter de la cubierta córnea del tarso en la que presenta escamas superpuestas delante y pequeñas placas irregulares detrás.

-   **Semialtricial // Semialtricial:** Carácter de un ave joven que se cubre de plumón al nacer, no puede abandonar el nido durante unas semanas y es alimentada por sus padres.

-   **Semipalmate // Semipalmado:** Carácter de los dedos en el que los tres anteriores están unidos parcialmente por pequeñas membranas.

-   **Semiplume // Semipluma:** Pluma vellosa con un raquis grande, es decir, más largo que la barba más larga. Estructuralmente intermedia entre una pluma de contorno y una pluma de plumón.

-   **Semiprecocial // Semiprecocial:** Carácter de un ave joven que se cubre de plumón al nacer, abandona el nido poco después y se aleja a corta distancia mientras sigue siendo alimentada por sus padres.

-   **Serrate // Serrado:** La propiedad de tener un borde en forma de sierra, ya sea en la tomia del pico o en la cubierta córnea del tarso.

-   **Song // Canto:** Vocalización en la que uno o más sonidos se repiten sistemáticamente siguiendo un patrón específico y a menudo complejo. Suele emitirse desde perchas llamativas, con mayor frecuencia por los machos (al menos en regiones templadas) durante la época de cría. La definición anterior está sujeta a excepciones. Se cree que el canto sirve para atraer/estimular a la pareja y para defender el territorio, pero estas funciones no deben asumirse sin pruebas sólidas.

-   **Sonogram // Sonograma:** Término general para un gráfico de la frecuencia del sonido frente al tiempo, con la intensidad indicada por la oscuridad del gráfico. No confundir con "sonagrama", un gráfico de este tipo producido específicamente en el instrumento Sona-graph (Kay Elemetrics Co.). Asimismo, evite aplicar este término a espectrogramas sonoros de otras variables, como los realizados mediante análisis rápido de Fourier.

-   **Sound learning (sound imitation) // Aprendizaje del sonido (imitación del sonido):** Cambio adaptativo en el comportamiento de producción de sonidos que resulta de la experiencia. Suele ser un proceso de dos etapas en el que un animal primero memoriza un sonido y después produce buenas copias de ese original. Un ave puede aprender a reconocer las vocalizaciones de un vecino y, sin embargo, no vocalizar esos sonidos; esto no es "aprendizaje de sonidos". Asegúrese de utilizar "aprendizaje de sonidos" o "aprendizaje vocal" de forma inequívoca.

-   **Sound spectrogram // Espectrograma sonoro:** Gráfico producido por cualquier proceso que resuelva el sonido de forma que muestre en qué frecuencias se distribuye la energía. Con la frecuencia en el eje x, el eje y puede ser el tiempo, como en un sonograma, o la amplitud, como en una transformación de Fourier. Sinónimo: espectrograma de audio.

-   **Sparse vegetation // Vegetación dispersa:** Las plantas están separadas más del doble de su diámetro. Se distingue de la "vegetación abierta", que describe las plantas que, por término medio, están separadas menos que su diámetro, y de la "vegetación cerrada", en la que están en contacto o se superponen. Estos términos se refieren a la capa de vegetación que presenta la cobertura más completa.

-   **Subsong // Subcanto:** Etapa "motora" más temprana del desarrollo del canto, durante la cual un pájaro joven empieza a emitir sonidos que acabarán convirtiéndose en cantos adultos.

-   **Supercilium // Supercilium:** Una raya horizontal de plumaje de color distintivo en el lado de la cabeza por encima del ojo.

-   **Supplemental Plumage // Plumaje suplementario:** Nombre de cualquier plumaje que aparece en un ciclo de plumaje además de los plumajes básico y alternativo (es decir, no es homólogo ni al plumaje básico ni al alternativo). Puede preceder o seguir al plumaje alternativo. Adquirido por una muda suplementaria.

-   **Syllable // Sílaba:** Unidad repetida en una canción. Si utiliza este término, defínalo sin ambigüedades.

-   **Sympatric // Simpátrico:** Describe taxones que se encuentran en la misma ubicación.

-   **Syndactyl // Sindáctilo:** Disposición de los dedos en la que el tercero (medio) y el cuarto (externo) están parcialmente unidos con una sola suela ancha, como en el martín pescador.

-   **Syntopic // Sintópico:** Describe taxones que se encuentran en el mismo hábitat al mismo tiempo; este término se utiliza a menudo para especies estrechamente relacionadas.

-   **Taiga // Taiga:** Bosque septentrional, denso, predominantemente de coníferas, poco alterado o disectado y que a menudo contiene zonas pantanosas. Ocupa el amplio cinturón al sur de la tundra en latitudes medias altas.

-   **Territory // Territorio:** Espacio dentro del cual un individuo es agresivo hacia ciertas categorías de intrusos y, por lo general, dominante sobre ellos. Puede clasificarse a grandes rasgos como territorio reproductor o no reproductor, con varios tipos en cada uno (Pettingill 1985: 259). No confundir con "zona de campeo" (q.v.).

-   **Tibiotarsal joint // Articulación tibiotarsiana:** La articulación que apunta hacia atrás en la pierna entre el tibiotarsus (tibia) y el tarsometatarsus (tarso). No es la rodilla, la articulación entre el fémur y el tibiotarso, que suele quedar oculta por el plumaje y la musculatura del muslo. Sinónimos: articulación intertarsal, tobillo.

-   **Tomium (plural: tomia) // Tomio (plural: tomia)**: El borde cortante de la mandíbula superior o inferior. 

-   **Tonal quality // Cualidad tonal:** Lo que distingue un sonido de otro de la misma frecuencia. Físicamente, la calidad tonal viene determinada por la presencia o ausencia de armónicos y su intensidad y distribución relativas, por los transitorios y por la velocidad y el alcance de la modulación de frecuencia y/o amplitud. Sinónimo: timbre.

-   **Totipalmate // Totipalmado:** Carácter de los dedos de los pies en el que los cuatro están unidos por grandes telarañas, como en los cormoranes.

-   **Tundra // Tundra**: importante comunidad biótica caracterizada por la ausencia de árboles y veranos cortos y frescos; el permafrost bajo una capa superficial está sujeto al deshielo estival. Las plantas dominantes son líquenes, musgos, juncias, hierbas y arbustos bajos. "Tundra ártica" ocupa la región ártica, es decir, al norte de la isoterma de 10° C, donde la temperatura media del mes más cálido cae por debajo de ese valor y no es posible el crecimiento de árboles. La "tundra alpina" se sitúa por encima del límite arbóreo de las altas montañas (por ejemplo,\~ 3.050 m en las Montañas Rocosas y el sistema Sierra Nevada-Cascade).

-   **Variety // Variedad:** La presentación secuencial de tipos de canto en un repertorio. Si las canciones sucesivas en una actuación son de diferentes tipos, se dice que un pájaro canta con "variedad inmediata"; si un pájaro repite un tipo de canción muchas veces antes de cambiar a otro tipo de canción, se dice que el pájaro canta con "variedad eventual".

<!-- -->

-   **Ventral tract // Tracto ventral:** La pteryla en la parte inferior del cuerpo, desde la unión de las ramas mandibulares hasta el anillo de plumas alrededor del respiradero. En diferentes especies, puede incluir un apterio medioventral o ser más o menos divisible en tractos como el cervical, el pectoral, el esternal y el abdominal.

<!-- -->

-   **Vertical displacement // Desplazamiento vertical:** Característica de una especie o población cuyos individuos cambian regularmente su rango de elevación en las montañas. Sinónimo: migración altitudinal.

<!-- -->

-   **Vocal convergence // Convergencia vocal:** Tendencia de dos o más aves a converger en señales vocales similares, generalmente como resultado del aprendizaje vocal.

<!-- -->

-   **Vocalization // Vocalización:** Término que engloba todos los sonidos aviares producidos por la siringe, en contraste con los "sonidos no vocales" (q.v.).

<!-- -->

-   **Western Palearctic // Paleártico occidental:** Uno de los ocho reinos biogeográficos, que incluye principalmente ecorregiones de clima boreal y templado. Comprende el norte de África, el norte y centro de la Península Arábiga, parte de Asia templada y Europa. Sus límites exactos pueden variar según la fuente.

-   **Whistle // Silbido:** Sonido que se aproxima lo más posible a un tono puro, es decir, con una fundamental y sin sobretonos.

<!-- -->

-   **Woodland // Bosque:** Conjunto abierto de árboles, por lo general de menos de 15 m de altura, demasiado espaciados para formar un dosel continuo, y con un crecimiento intermedio de hierbas o arbustos.

-   **Zygodactyl // Zigodáctilo:** Disposición de los dedos en la que el segundo y el tercero están delante y el primero (hallux) y el cuarto detrás, como en los pájaros carpinteros.