---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Apéndice 7: Políticas y procedimientos relativos a los medios de comunicación {#sec-app7 .unnumbered}

Las galerías multimedia serán añadidas a su revisión por el personal de Birds of the World (BOW). Le sugerimos que consulte algunos ejemplos de fichas BOW publicados recientemente para hacerse una idea de cómo suelen componerse las galerías multimedia, los títulos y los pies de foto.

Puede revisar la multimedia antiguos de su ficha en la versión "en vivo" de la misma (es decir, **no en** la versión "borrador" de su ficha). La versión borrador de su ficha puede tener galerías de "marcadores de posición" en las páginas donde aparecerán imágenes y figuras. Una vez que su ficha pase a la fase de Revisión por el Editor, el personal de BOW rellenará la ficha con la multimedia semifinal y los pies de foto asociados, que usted podrá revisar durante el periodo de Revisión por el Autor.

**A continuación encontrará instrucciones para determinados tipos de soportes. Se supone que ha leído y acepta cumplir estas normas antes de iniciar la revisión de BOW.**

## Cifras {#sec-intro-figures}

Le sugerimos que revise todas las figuras de la ficha antes de enviar su revisión para la revisión editorial. Si tiene figuras nuevas (o actualizadas) que añadir a la ficha, por favor, cárguelas con el mayor tamaño/calidad posible en el Formulario de finalización del primer borrador de ficha BOW ([inglés](https://forms.gle/e6uTR5E8Z5aXXc9n6), [español](https://forms.gle/4e3PifYqvKrbQ1tV8)) o envíelas a María Smith ([mgs248\@cornell.edu](mailto:mgs248@cornell.edu)).

Si desea incluir una figura que ha sido publicada en otro sitio en una ficha de BOW, póngase en contacto con el editor de la otra fuente para confirmar quién tiene los derechos de reproducción de la figura. Si usted es el único titular de los derechos, BOW podrá publicar la figura. Si el editor comparte los derechos de propiedad con usted, necesitaremos que un representante del editor firme el [Acuerdo de Colaborador de](https://drive.google.com/file/d/1Arz8mqAamqQFlIfV2zNJFQbbB5Y0D4Ug/view?usp=sharing)[ BOW](https://drive.google.com/file/d/1Arz8mqAamqQFlIfV2zNJFQbbB5Y0D4Ug/view?usp=sharing) antes de poder publicar la figura en BOW. Si tiene alguna duda sobre este proceso, póngase en contacto con Brooke Keeney ([bkk37\@cornell.edu](mailto:bkk37@cornell.edu)) o Maria Smith ([mgs248\@cornell.edu](mailto:mgs248@cornell.edu)).

El personal de BOW y eBird evaluará procedimentalmente el mapa de distribución y la parte de muda del diagrama del ciclo anual para su revisión y realizará los cambios necesarios. Usted podrá revisar estos cambios. Otras figuras no se actualizarán a menos que usted proporcione instrucciones específicas.

Si desea que el personal de BOW genere alguna cifra para usted, póngase en contacto con Brooke Keeney ([bkk37\@cornell.edu](mailto:bkk37@cornell.edu)) para hablar de los detalles.

Tenga en cuenta que:

-   Siempre que sea posible, las figuras numeradas deben limitarse a mapas, gráficos, cuadros, ilustraciones, etc. Las fotografías se exponen mejor en las galerías fotográficas y se referencian en el texto por sus códigos de la Macaulay Library.

-   Las figuras deben ordenarse por su primera aparición en el texto.

-   Si ha añadido/suprimido alguna figura o desea reorganizar el orden de las figuras existentes, facilite una lista de **todos los** números y títulos de las figuras que desea incluir en su revisión (incluyendo tanto las figuras antiguas como las nuevas).

-   Proporcione un documento Word con todos los pies y títulos de figuras nuevos o revisados.

## Imágenes {#sec-intro-images}

La galería de imágenes principal y las imágenes de cada página de la ficha serán curadas y añadidas a la revisión por el personal de BOW. Podrá revisar todas las imágenes de la revisión antes de su publicación. Se aceptan sugerencias de los autores para las imágenes (véanse las instrucciones más abajo).

Tenga en cuenta que si **no** desea que el personal de BOW rellene las galerías multimedia de su ficha, deberá proporcionar usted mismo el contenido adecuado para la galería, de acuerdo con las normas y procedimientos de BOW. Le recomendamos encarecidamente que se comunique ampliamente con el personal de BOW acerca de sus selecciones, ya que cualquier medio que no cumpla con los estándares de medios de BOW de contenido, tamaño, calidad, organización de la ficha, etc., será omitido o reemplazado, sin excepción.

### Envíe sus propias imágenes {#sec-intro-images-own}

Si tiene imágenes específicas que le gustaría aportar a su ficha BOW, **debe cargarlas en nuestro sistema de gestión de contenidos a través de eBird/Macaulay Library**. tenga en cuenta que sólo debe contribuir con imágenes de las que **usted** sea el fotógrafo. Si desea añadir imágenes de otras personas a su revisión de BOW, cada fotógrafo individual tendrá que subir su propio trabajo (incluso si tiene el permiso del fotógrafo para utilizar la imagen en una ficha BOW).

Aunque le animamos absolutamente a que profundice en eBird tanto como desee, para muchos colaboradores de BOW, eBird será simplemente un mecanismo de entrada que le permitirá cargar imágenes en un repositorio estable que archiva y muestra la mejor calidad/tamaño más grande de una imagen, junto con metadatos organizados y con capacidad de búsqueda.

Para enviar imágenes a eBird/Macaulay Library, deberá determinar cuál es el mejor protocolo eBird que puede utilizar.

Sin embargo, los autores de BOW que sólo estén interesados en añadir imágenes específicamente para una revisión de BOW no tienen ninguna obligación de introducir listas de eBird "completas". En la jerga de eBird, una checklist completa incluye datos de observación de **todas las** especies que haya podido identificar en un lugar y fecha determinados. Las checklists completas se consideran científicamente válidas y, por tanto, deben ajustarse a una serie de normas reproducibles. Existe bastante más flexibilidad a la hora de añadir medios a una checklist "incompleta".

La forma más sencilla de subir material destinado a una checklist incompleta es utilizar su nombre de usuario/contraseña BOW para iniciar sesión en eBird. Seleccione la pestaña "Enviar" e indique una ubicación. En la siguiente pantalla, introduzca la fecha en que se tomó la imagen y, a continuación, seleccione un protocolo "**Histórico**" o **"Incidental**".

-   Si elige **Histórico**, sólo necesita conocer la ubicación y la fecha de su(s) imagen(es). Se le dará la opción de introducir otros metadatos sobre sus observaciones, pero no es necesario que rellene esos campos. Una vez en la pantalla de la checklist, puede introducir la cantidad de especies (o una "X" si no las conoce) y hacer clic en el botón "Añadir detalles" que aparece. A continuación, puede arrastrar y soltar su(s) imagen(es) en el campo "Medios". Asegúrese de indicar que **no** está enviando una checklist completa (hay una pregunta antes de poder enviarla). Puede encontrar más información sobre este protocolo [aquí](https://support.ebird.org/en/support/solutions/articles/48001074151-uploading-historic-media).

-   Si eliges **"Incidental"**, necesitarás saber el lugar, la fecha, la hora y el tamaño del grupo. Introduzca la cantidad de especies (o una "X" si no las conoce), haga clic en el botón "Añadir detalles" y arrastre y suelte las imágenes en el campo "Medios". Verás que ya se ha seleccionado "Lista incompleta".

Utilizando estos dos protocolos, no hay problema en introducir multimedia antigua y mantener la checklist lo más simple posible.

Del mismo modo, está bien (¡y se anima a ello!) que los autores de BOW envíen imágenes de hábitats u otros tipos de medios que sean atípicos para eBird. Ahora puede enviar estas fotos a nivel [de lista](https://support.ebird.org/en/support/solutions/articles/48001269559-upload-checklist-media), incluyendo fotos de hábitat que no incluyan aves, a una lista de eBird. Las fotos de hábitat deben etiquetarse con las aves observadas en ese hábitat, lo que permite a los usuarios buscar dichas fotos en la Macaulay Library pulsando el botón "Hábitat/Paisaje sonoro" situado encima de la barra de búsqueda. También puede buscar fotos de hábitats por ubicación. Si tiene una imagen que incluya el ave pero que muestre principalmente el hábitat en lugar del ave en sí, cárguela en su checklist de eBird bajo la especie de ave correspondiente y utilice la etiqueta "Hábitat". Las fotos de aves en la mano también se pueden subir a una checklist de eBird bajo la especie correspondiente; por favor, utilice la etiqueta "En la mano" para que estas imágenes sean más fáciles de encontrar.

**Nota:** Si desea utilizar fotos de especímenes de museo en una ficha BOW, éstas **no** deben subirse a eBird. Póngase en contacto con Maria Smith ([mgs248\@cornell.edu](mailto:mgs248@cornell.edu)) para obtener información sobre cómo añadir estas imágenes a la ficha como figuras.

Sube tus fotos en su resolución original, siempre que sea posible. eBird acepta imágenes de hasta 10 MB de tamaño, y cada especie de una lista puede aceptar 10 imágenes. **Por favor, no incluyas marcas de agua en tus imágenes.**

Una vez que haya subido sus imágenes, por favor proporcione la checklist de eBird y/o los números de activos de la Macaulay Library (por ejemplo, ML36340541), así como un documento de Word con títulos y pies de foto para cada imagen que se incluirá (el material debe ser recibido a más tardar un mes antes de la publicación de la ficha). Puede cargar esta información en el Formulario de finalización del primer borrador de ficha BOW ([inglés](https://forms.gle/e6uTR5E8Z5aXXc9n6), [español](https://forms.gle/4e3PifYqvKrbQ1tV8)) o enviarla a Maria Smith ([mgs248\@cornell.edu](mailto:mgs248@cornell.edu)). Consulte las fichas publicados recientemente para ver ejemplos del formato y contenido de los títulos y pies de imagen.

Si desea enviar sus propias imágenes, estamos especialmente interesados en:

-   Imágenes que pueden utilizarse para la identificación de sexos, clases de edad y subespecies

-   Imágenes que muestren aspectos importantes del comportamiento (por ejemplo, exhibiciones, interacciones o búsqueda de alimento) y de la historia natural (por ejemplo, nidos o huevos).

-   Imágenes que muestren detalles anatómicos (por ejemplo, ala desplegada, muda, partes desnudas o retrato)

-   Imágenes que muestran las características del hábitat a gran y pequeña escala

-   Imágenes que muestren problemas de conservación y/o interacciones humanas con la especie

### Selección de imágenes que ya están en la Macaulay Library {#sec-intro-images-ML}

También le invitamos a examinar la Macaulay Library (http://macaulaylibrary.org) en busca de imágenes para incluir en su ficha. Algunas imágenes de la Macaulay Library pueden ser demasiado pequeñas/de baja calidad para su inclusión en BOW, por lo que es útil comprobar el tamaño antes de sugerir una imagen. Si encuentra imágenes que le gustaría incluir en su ficha, por favor proporcione la lista dde eBird y/o los números de activo de la Macaulay Library (por ejemplo, ML36340541), así como un documento Word con títulos y pies de foto para cada imagen a incluir (el material debe recibirse a más tardar un mes antes de la publicación de la ficha). Puede cargar esta información en el Formulario de finalización del primer borrador de ficha BOW ([inglés](https://forms.gle/e6uTR5E8Z5aXXc9n6), [español](https://forms.gle/4e3PifYqvKrbQ1tV8)) o enviarla a Maria Smith ([mgs248\@cornell.edu](mailto:mgs248@cornell.edu)).

## Audio {#sec-intro-audio}

### Envíe su propio audio {#sec-intro-audio-own}

El audio debe añadirse siguiendo las mismas directrices que las imágenes.

### Seleccionar audio que ya está en la Macaulay Library {#sec-intro-audio-ML}

Le invitamos a examinar la Macaulay Library (http://macaulaylibrary.org) en busca de selecciones de audio para incluir en su ficha. Si encuentra pistas de audio que le gustaría incluir en su ficha, proporcione un documento de Word con los números de activo de la Macaulay Library (por ejemplo, ML36340541), así como los títulos y subtítulos de cada pista y el tiempo específico de la selección de interés (por ejemplo, 0:30-1:10 s), si procede. Puede cargar esta información en el Formulario de finalización del primer borrador de ficha BOW ([inglés](https://forms.gle/e6uTR5E8Z5aXXc9n6), [español](https://forms.gle/4e3PifYqvKrbQ1tV8)) o enviarla a Maria Smith ([mgs248\@cornell.edu](mailto:mgs248@cornell.edu)).

## Vídeo {#sec-intro-video}

### Envíe su propio vídeo {#sec-intro-video-own}

Para enviar vídeos, póngase en contacto con Brooke Keeney ([bkk37\@cornell.edu](mailto:bkk37@cornell.edu)) o Maria Smith ([mgs248\@cornell.edu](mailto:mgs248@cornell.edu)).

### Selección de vídeos que ya están en la Macaulay Library {#sec-intro-video-ML}

Le invitamos a buscar en la Macaulay Library (http://macaulaylibrary.org) selecciones de vídeo para incluirlas en su ficha. Si encuentra un vídeo que se corresponda con un texto específico de la ficha, facilítenos una lista de los números de activo de la Macaulay Library (por ejemplo, ML36340541), así como los títulos, subtítulos y las ubicaciones en las que desea que se incluyan los vídeos dentro de la ficha. Puede cargar esta información en el Formulario de finalización del primer borrador de ficha BOW ([inglés](https://forms.gle/e6uTR5E8Z5aXXc9n6), [español](https://forms.gle/4e3PifYqvKrbQ1tV8)) o enviarla a Maria Smith ([mgs248\@cornell.edu](mailto:mgs248@cornell.edu)).

## Tablas {#sec-intro-tables}

Le sugerimos que revise todas las tablas y apéndices existentes en la ficha antes de enviar su revisión para el examen editorial. Si desea **corregir** un cuadro/apéndice existente, puede enumerar sus correcciones en un documento Word o preparar un archivo Excel con una nueva versión del cuadro/apéndice.

Si desea **añadir** una tabla a la ficha, **no utilice la función de tabla del editor en línea de BOW.** En su lugar, prepare un archivo Excel con su tabla. Cuando elabore su **tabla, tenga en cuenta que normalmente no podemos mostrar tablas de más de siete columnas de ancho** en el sitio web de BOW. Por lo tanto, intente construir sus tablas en formato "alto" en lugar de "ancho". En el archivo, añada un título para la tabla y las notas a pie de página correspondientes. Asegúrese de que todas las referencias utilizadas se citan en la ficha BOW o se enumeran con sus citas completas en el archivo Excel para que puedan incluirse en la lista de referencias BOW. Indique las unidades de medida. Escriba los nombres de las columnas en mayúsculas como si fueran títulos (véase "Encabezamientos" en [el Apéndice 4](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#heading=h.8ixbimxb8azj)). Por último, indique en el texto de la ficha BOW dónde desea que se incluya la tabla (puede añadir simplemente el texto "(Tabla X)" donde sea necesario).

Si ha añadido o eliminado tablas/apéndices o desea reorganizar el orden existente, facilite una lista de **todos los** números de tablas/apéndices (antiguos y nuevos) y los títulos que se incluirán con su revisión. tenga en cuenta que el personal de BOW renombrará todos los apéndices como tablas cuando prepare su ficha para la publicación, ya que los apéndices no se admiten en las fichas recién publicadas.

Puede cargar los archivos de sus tablas en el Formulario de finalización del primer borrador de ficha BOW ([inglés](https://forms.gle/e6uTR5E8Z5aXXc9n6), [español](https://forms.gle/4e3PifYqvKrbQ1tV8)) o enviarlos a Maria Smith ([mgs248\@cornell.edu](mailto:mgs248@cornell.edu)).

## Derechos de autor y autorizaciones {#sec-intro-copyright}

La Macaulay Library es principalmente un depósito de datos con fines de investigación. No es un repositorio abierto de medios enriquecidos a disposición del público en general para cualquier uso. Los activos de la colección son propiedad del autor original (por ejemplo, grabador o fotógrafo), y los derechos de autor corresponden a cada autor, a menos que se indique lo contrario.

Al enviar material multimedia a BOW y/o eBird/Macaulay Library, da su consentimiento para que utilicemos el contenido que ha compartido en el sitio web de BOW y/o en otros proyectos del Laboratorio de Ornitología de Cornell (consulte las condiciones de uso completas para el material multimedia enviado a eBird/Macaulay Library: http://macaulaylibrary.org/terms-of-use).

Cualquier material (mapas, figuras, etc.) generado por el personal de BOW para su uso en una ficha BOW se considera un componente de la versión específica de su ficha BOW. Estos materiales son propiedad conjunta suya, de cualquier otra parte implicada en su creación y de BOW. Usted no puede utilizar estos materiales en otras situaciones sin citar la ficha de BOW, especialmente en casos de una empresa con fines de lucro sin el consentimiento expreso de BOW.