---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Información general {#sec-background .unnumbered}

**Por favor, revise [el Apéndice 1](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.qsh70q)para conocer todas las políticas relativas a la autoría, conducta y contenido. Se supone que los colaboradores han leído y respetarán estas normas y que han firmado el [Acuerdo de Colaboración de BOW](https://drive.google.com/file/d/1Arz8mqAamqQFlIfV2zNJFQbbB5Y0D4Ug/view?usp=sharing) antes de comenzar su revisión.**

Los colaboradores de BOW no reciben compensación económica, aunque sí recibirán acceso gratuito a BOW de por vida. 

Para una revisión inicial de BOW, se le dará acceso a un borrador de ficha que contiene texto derivado de la ficha de especies más reciente de BOW, Birds of North America (BNA), Neotropical Birds (NB), y/o Handbook of the Birds of the World (HBW) (dependiendo de la distribución geográfica de su especie). Puede esperar el siguiente tipo de cobertura de cada fuente original:

-   BNA: Cobertura exhaustiva y en profundidad de (casi) todas las especies que se reproducen en Norteamérica. las fichas se escribieron con énfasis en Norteamérica, y puede haber o no cobertura de publicaciones/biología más allá de esta área geográfica. 

-   NB: La profundidad de las fichas varía desde fichas totalmente realizados a la par con la cobertura de BNA hasta fichas breves con sólo texto introductorio. las fichas se escribieron haciendo hincapié en la biología neotropical.

-   HBW: Amplia cobertura de todas las especies de aves del mundo, centrada en los principales aspectos de la historia natural, incluida la biología de la reproducción, la alimentación y los desplazamientos locales y regionales. Las descripciones se escribieron para captar la variación de una especie en su distribución mundial a gran escala y pueden carecer del nivel de detalle de las descripciones BNA (y algunas) NB.

Puede editar, combinar o eliminar todo o parte del texto existente como considere oportuno a medida que vaya introduciendo nuevo texto y referencias en la ficha en el transcurso de su revisión. 

Si su ficha corresponde a una especie que nunca estuvo cubierta por BNA o NB, el texto original de HBW se habrá importado a la estructura más completa de BNA/NB. Cuando exista texto HBW, se habrá importado a la primera sección de la página a la que corresponda. Es probable que parte de este texto sea más apropiado en otras secciones o subsecciones, por lo que le pedimos que distribuya lo que decida utilizar en las secciones y subsecciones más pertinentes de todo el informe (véase [el Apéndice 2](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.3as4poj)). El texto de HBW también puede incluir hipervínculos a imágenes u otros medios procedentes de la Internet Bird Collection (o de otros lugares). Si estos enlaces siguen siendo funcionales, puede dejarlos o eliminarlos según considere oportuno. Por favor, elimine cualquier enlace roto.

Tenga en cuenta que **siempre se prefieren las fuentes primarias (es decir, las fuentes de información publicadas originalmente, a menudo artículos de revistas académicas)** y que los colaboradores deben revisar la bibliografía original sobre la especie para ampliar o sustituir el texto de las fuentes secundarias mencionadas (es decir, las fuentes que contienen información publicada originalmente en otro lugar) para alcanzar el nivel de detalle adecuado en el borrador. El texto derivado originalmente del proyecto de fuentes de HBW a menudo no contenía referencias dentro del texto. Parte de las tareas, es revisar las referencias (incluidas las Referencias adicionales, que contendrán citas de HBW no referenciadas en el texto) en la página de Referencias y, cuando sea posible y útil, asegurarse de que esas referencias se citan a lo largo del texto de la ficha. Para más detalles sobre las fuentes, véase [Contenido de la ficha](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#heading=h.2s8eyo1).

## Revisiones completas y parciales {#sec-background-full}

Una **revisión completa** implicará la evaluación de toda la ficha con actualizaciones en tantas secciones como sea necesario, en consonancia con las publicaciones disponibles sobre la biología de la especie.

-   Los colaboradores deben procurar realizar una búsqueda bibliográfica exhaustiva e incluir texto y referencias en el mayor número posible de páginas, secciones y subsecciones.

Una **revisión parcial** implicará un cambio en parte del contenido citable de una ficha sin una actualización exhaustiva de tantas secciones como sea posible. Algunos ejemplos de revisiones parciales incluyen una actualización de la sistemática/taxonomía, la adición de información de una o unas pocas publicaciones, y/o una revisión de una o más secciones por parte de un especialista o editor de BOW.

-   Los colaboradores pueden optar por realizar múltiples revisiones parciales y llegar así a una revisión completa a través de varias revisiones parciales intermedias. Cuando se adopte este enfoque, la primera revisión parcial deberá dar prioridad al contenido más obsoleto y/o al área de especialización del autor.

Las erratas, las correcciones o aclaraciones menores y los cambios en los soportes, mapas o productos eBird no constituyen una revisión parcial. Véase también [el Apéndice 1: Historial de versiones y revisiones](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.qsh70q).

## Calendario de una revisión {#sec-background-timeline}

Las revisiones pasan por cuatro etapas antes de ser publicadas:

-   [**Borrador:**]{style="color:red;"} Los colaboradores revisan y añaden contenido.
-   [**Revisión del editor:**]{style="color:orange;"} Los editores BOW revisan el borrador completo y añaden media.
-   [**Revisión del autor:**]{style="color:lightskyblue;"} Los colaboradores responden a comentarios de los editores BOW y revisan la ficha completa con la media incorporada.
-   [**Final:**]{style="color:blue;"} El staff de BOW revisa los cambios finales y publica la ficha.

Normalmente, BOW insta a los colaboradores a completar la fase de borrador de su revisión en un mes (para las revisiones parciales) o en tres meses (para las revisiones completas); sin embargo, el calendario de revisión también reflejará las limitaciones a las que se enfrentan los colaboradores y el personal de BOW, así como la naturaleza de la revisión. En algunos casos, completar una revisión completa para una especie bien estudiada puede llevar seis meses o más.

Si una revisión va a exceder el plazo sugerido, los colaboradores deberán comunicarlo al personal de BOW con antelación y frecuencia. Sin embargo, en algunos casos (por ejemplo, actualizaciones taxonómicas urgentes, si el progreso de una revisión es demasiado lento, y/o si el personal de BOW no puede comunicarse con los colaboradores pertinentes), la revisión puede ser completada por el personal de BOW o por otros.

## Autoría y contribuciones a una revisión {#sec-background-authorship}

Para más detalles sobre la autoría y las contribuciones, véase [el Apéndice 1](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.qsh70q).

Antes de iniciar la revisión de una ficha de especies BOW, todos los colaboradores pertinentes deben llegar a un acuerdo previo sobre lo siguiente (si procede):

1\) qué colaborador se encargará de coordinar la revisión, 

2\) qué aportará cada colaborador a la revisión, y

3\) el orden de autoría.

Normalmente, la secuencia de autores debe reflejar la contribución acumulativa relativa de cada autor a esa versión de la ficha, aunque los autores pueden sugerir una secuencia diferente si están de acuerdo entre ellos. 

Dado que cada ficha BOW se deriva de una o varias publicaciones fuente, los autores originales asociados a cada ficha fuente se mantendrán en la cita BOW en la medida en que el contenido de su autoría siga incluido en esa versión de la ficha BOW y justifique la coautoría.

BOW contrata a varios expertos en la materia para complementar y normalizar algunas de las secciones más técnicas de una ficha (por ejemplo, Plumajes, Mudas, Sistemática y Sonidos y comportamiento vocal). Se preguntará a los autores en el formulario de cumplimentación del borrador ([inglés](https://forms.gle/e6uTR5E8Z5aXXc9n6), [español](https://forms.gle/4e3PifYqvKrbQ1tV8)) si desean utilizar los servicios de estos expertos en su ficha. El trabajo de estos expertos en la materia puede merecer la autoría, según las políticas típicas de autoría, salvo acuerdo previo.

El personal de BOW y los colaboradores participarán en la preparación de varios elementos de una ficha, que los colaboradores tendrán la oportunidad de revisar. Algunos de los elementos que el personal de BOW cubre con frecuencia incluyen: 

-   Galerías de fotos y pies de foto 

-   Galerías de vídeos y subtítulos (si procede) 

-   Plumajes y mudas

Se espera que los colaboradores revisen todas las contribuciones a la ficha antes de su publicación. En caso de desacuerdo o conflicto, los colaboradores deberán comunicarse con el personal de BOW para intentar llegar a una solución satisfactoria para ambas partes. Si no se puede llegar a una resolución, los colaboradores pueden optar por diferir al personal de BOW o poner fin a su participación en el proyecto.