---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Contenido de la ficha {#sec-content .unnumbered}

## Visión general {#sec-content-overview}

Las fichas BOW pretenden ofrecer resúmenes completos y actualizados de la biología conocida de todas las aves. La taxonomía de BOW sigue la de eBird/Clements, e intenta ajustarse lo más posible a la de los Comités de Clasificación y Nomenclatura de Norteamérica y Sudamérica.

Las fichas BOW deben redactarse de forma que estimulen nuevos estudios, indicando los vacíos en nuestro conocimiento actual de las especies. En otras palabras, las descripciones de BOW deben ser una "ventanilla única" para las personas que buscan un resumen de lo que sabemos -y no sabemos- sobre la biología de una especie y sugerencias sobre dónde ir para obtener más detalles (es decir, a través de las referencias citadas). Las fichas están dirigidas a ornitólogos y a personas con intereses avanzados en la biología de las aves. Por ello, también deberían ser útiles para biólogos de vida silvestre, científicos de otras disciplinas que estudian las aves, aficionados interesados en la ecología y el comportamiento de las aves, profesores y estudiantes de biología, gestores del territorio e investigadores que evalúan el impacto ambiental, entre otros.

El objetivo de los y las autores debe ser ofrecer un resumen crítico, preciso y conciso de los conocimientos biológicos actuales (y nuestro no-conocimiento) sobre una especie. Las secciones actualizadas de las fichas deben basarse en datos publicados sólidos y contrastados y en interpretaciones de esos datos, complementados con nuevos datos inéditos cuando se disponga de ellos. Los autores deben resumir las principales observaciones, hallazgos y conclusiones de los estudios nuevos (y de los recién encontrados). Aunque es posible que los hallazgos menos importantes de las publicaciones no se traten en detalle, los colaboradores pueden alertar a los lectores de la existencia de estos hallazgos ("Smith (2014) también proporcionó información sobre...") para que los lectores puedan buscar dicho material por su cuenta si lo desean.

En algunos casos, los y las colaboradores encontrarán resúmenes o reseñas publicados sobre algún aspecto de la biología de su especie, por ejemplo, la dieta o las vocalizaciones. Siempre que sea posible, se deberán resumir los aspectos y detalles clave de estas reseñas y no limitarse a remitir al lector a otra fuente. En la mayoría de los casos, las y los autores deberán realizar su propia revisión independiente de los estudios resumidos y citar los estudios originales en su informe. Tenga en cuenta que todo el texto debe ser original; se debe tener especial cuidado de evitar el plagio (ya sea del trabajo de otros o de su propio trabajo publicado previamente).

Los contenidos de BOW deben presentarse de forma objetiva, objetiva y sin prejuicios, y los autores deben evitar transmitir sus opiniones o interpretaciones personales. Por el contrario, los autores deben presentar información basada en pruebas de tal manera que los lectores dispongan de la información necesaria para sacar sus propias conclusiones. No son apropiadas las críticas a individuos, grupos, grupos de personas o estudios específicos (o similares). Por lo general, las fichas sobre especies de BOW no son un lugar para proponer nuevas ideas; tales ideas deberían aparecer y ser juzgadas primero en la literatura primaria. Sin embargo, como ya se ha indicado, los autores deben señalar los vacíos en nuestros conocimientos. Esto incluye no sólo señalar los datos que faltan, sino también plantear cuestiones aún sin respuesta, como estructuras o hábitos inexplicados o comparaciones deficientes con especies afines. Para los temas sobre los que se sabe poco con certeza, los autores pueden indicar una probabilidad, pero ésta debe basarse en pruebas; hay que evitar las conjeturas. Cuando se carezca de información, los autores pueden incluir información pertinente de especies estrechamente emparentadas. Haga un esfuerzo especial por informar (o indicar su desconocimiento) de los hábitos y hábitats utilizados durante el periodo no reproductivo, sobre todo en el caso de las especies que migran a regiones menos conocidas. Intentar relacionar entre sí los distintos aspectos del ciclo biológico de la especie, caracterizando así sus cualidades distintivas. Proporcionar información actual y exhaustiva, referencias y preguntas de investigación debería ser un poderoso estímulo para nuevos estudios.

Una revisión debe esforzarse por ser legible y útil. Las descripciones de especies se leerán mucho y se traducirán a otros idiomas, por lo que su contenido debe ser claro y evitar el lenguaje específico de cada región y las referencias que puedan no ser comprendidas por un público global. Dado que las revisiones de BOW ya no son documentos impresos, no es necesario utilizar el lenguaje telegráfico y conciso (ni las abreviaturas) necesario en las descripciones originales de las especies. Aunque hay excepciones, los colaboradores deben utilizar frases completas y pensar en la fluidez, la legibilidad y la mejor manera de transmitir la información. BOW seguirá utilizando el lenguaje científico/técnico necesario para tratar la información ornitológica, pero le rogamos que evite el exceso de palabras y transmita la información de forma sucinta. Si es necesario resumir información muy detallada, el texto puede abreviarse y utilizar frases incompletas para ser más eficiente (por ejemplo, párrafos con detalles extensos o estadísticas resumidas, como las descripciones de plumajes, mudas y biometría en la página Plumajes, mudas y estructura).

Animamos a los colaboradores a que piensen en formas de animar el texto de sus fichas, especialmente en la Introducción. Por ejemplo, incorporando citas históricas o influyentes, hablando de la importancia cultural de la especie o incluyendo breves anécdotas divertidas.

## Fuentes de información {#sec-content-sources}

Planifique una amplia búsqueda de información para completar la revisión. Esto incluye la revisión no sólo de estudios publicados recientemente, sino también de publicaciones más antiguas, incluidas las de principios del siglo XX e incluso anteriores. La bibliografía más antigua que puede haber sido difícil de identificar o de acceder cuando se escribieron las fichas originales puede estar ahora más ampliamente disponible. Las publicaciones antiguas suelen contener información sobre la historia natural de una especie que rara vez se publica hoy en día. Esa información puede ser muy valiosa en la actualidad para diseñar estudios e interpretar resultados. Google Scholar [(https://scholar.google.com/)](https://scholar.google.com/), ResearchGate [(https://www.researchgate.net/)](https://www.researchgate.net/), BioOne [(https://bioone.org/)](https://bioone.org/), Biodiversity Heritage Library [(](https://www.biodiversitylibrary.org/)https://www.biodiversitylibrary.org/) y SORA [(https://sora.unm.edu/](https://sora.unm.edu/)) son lugares excelentes para encontrar citas y archivos PDF de publicaciones antiguas. Internet Archive [(](https://archive.org/)https://archive.org/) puede ser útil para acceder a libros antiguos. Zoological Record [(](https://clarivate.com/academia-government/scientific-and-academic-research/research-discovery-and-referencing/web-of-science/zoological-record/)https://clarivate.com/academia-government/scientific-and-academic-research/research-discovery-and-referencing/web-of-science/zoological-record/) también puede ser un recurso útil si su institución está suscrita.

Asegúrese de realizar búsquedas utilizando versiones anteriores de los nombres comunes y científicos de la especie y/o nombres en otros idiomas pertinentes. Cada vez más, las búsquedas en línea permiten acceder a copias de publicaciones antiguas, por ejemplo, en sitios como Biodiversity Heritage Library: https://www.biodiversitylibrary.org/. Las publicaciones más recientes pueden encontrarse en bases de datos como Scopus [(](https://www.scopus.com/)https://www.scopus.com/) y Web of Science [(](https://www.webofscience.com/)https://www.webofscience.com/). Si los colaboradores no pueden encontrar un recurso en línea, el personal de BOW o los especialistas en préstamos interbibliotecarios de la institución de origen del autor pueden localizarlo. Estos bibliotecarios pueden ser de gran ayuda y, por supuesto, deben incluirse en los agradecimientos.

Las fuentes de información deben incluir toda la bibliografía publicada, incluidas no sólo las publicaciones revisadas por pares en revistas científicas, sino también libros, capítulos de libros, tesis y disertaciones no publicadas (cada vez más disponibles en línea) e informes gubernamentales estatales, provinciales y federales. Tenga especial cuidado en minimizar los sesgos regionales, en particular para las especies que se incluyeron originalmente en las fichas BNA, ya que la literatura internacional más antigua puede estar ausente de estas fichas debido al enfoque geográfico de sus series originales.

Para ciertas secciones del informe, los colaboradores también querrán incluir información del North American Breeding Bird Survey, eBird y Christmas Bird Count. Los colaboradores también deberían examinar las guías de campo y otros libros del tipo "Aves de..." específicos de los estados, provincias y regiones y, especialmente, las ediciones más recientes de los atlas de aves nidificantes estatales y provinciales, muchos de los cuales están disponibles en línea. Las bases de datos de fichas de registro de nidos también pueden ser una fuente de información. En algunas situaciones, el examen de especímenes de museo puede ser útil para completar ciertas partes de la ficha.

En algunos casos, puede deducirse información novedosa sobre una especie (por ejemplo, la estructura de los nidos o las asociaciones alimentarias) a partir de los medios de la [Macaulay Library](https://www.macaulaylibrary.org/)o de otros archivos (por ejemplo, [xeno-canto](https://xeno-canto.org/), [Wikiaves](https://www.wikiaves.com.br/)o [iNaturalist](https://www.inaturalist.org/)). Siempre que sea posible, BOW anima a los colaboradores a enviar estos datos a revistas revisadas por pares. Los colaboradores también pueden incluir esta información en las descripciones de especies de BOW; sin embargo, los medios y el archivo fuente deben atribuirse y citarse adecuadamente (véase [Gramática y formato: Referencias/Citaciones](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#heading=h.35nkun2)). tenga en cuenta también que hay que ser prudente cuando se intente deducir el contexto a partir de un medio de comunicación.

Del mismo modo, los colaboradores pueden incluir sus propios datos inéditos en la ficha, aunque BOW anima a los colaboradores a considerar también la publicación de estos datos en revistas revisadas por pares. Si se van a incluir datos inéditos en BOW, los colaboradores deben proporcionar a los lectores alguna información sobre cómo se recogieron los datos. Incluya los resultados de los análisis estadísticos de estos datos cuando proceda. 

Los colaboradores también pueden buscar datos adicionales no publicados de otros, pero deben tener cuidado de acreditarlos adecuadamente. La inclusión de estos datos en una ficha de especies de BOW no impide que el propietario los publique posteriormente en otro lugar. No obstante, una vez publicados estos datos, deberá actualizarse la cita en BOW.

## Estructura y organización de la ficha {#sec-content-structure}

Cuando se publiquen, las fichas BOW aparecerán en uno de dos diseños: un diseño apilado verticalmente más similar al diseño original de las fichas HBW, o un diseño ampliado más similar al diseño original de las fichas BNA. Durante una revisión, dispondrá de todas las secciones (según la presentación ampliada), tanto si decide rellenarlas como si no. Las secciones que no tengan contenido no serán visibles cuando se publique la revisión. Cuando una revisión esté lista para publicarse, el personal de BOW decidirá si la ficha contiene suficiente información para mostrarse en el formato ampliado. El objetivo final es que todas las especies de BOW se conviertan al formato ampliado a medida que se vaya completando la información.

Las fichas ampliadas de BOW están divididas en **páginas** por temas. El orden de estas páginas es el mismo para todas las especies (véase más abajo): después de la página de Introducción hay una página sobre Identificación, luego Plumajes, Mudas y Estructura; Sistemática; Distribución; Hábitat; etc. 

Dentro de cada página, hay una serie **de secciones potenciales**. Por ejemplo, dentro de la página sobre Sistemática, hay secciones sobre Variación geográfica, Subespecies y Especies afines. 

Dentro de las secciones, puede haber una serie de **subsecciones** designadas, cada una con su propio encabezamiento. Por ejemplo, dentro de la sección Huevos de la página Cría, dos subsecciones comunes que suelen tratarse por separado son Forma y Tamaño.

El orden de las páginas, secciones y subsecciones de la ficha estándar figura en [el Apéndice 2](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.3as4poj). 

En [el Apéndice 3](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.hjoo9cq14meu)se dan orientaciones sobre el contenido adecuado de cada página y sección.

BOW se esfuerza por mantener, en la medida de lo posible, la coherencia entre fichas en cuanto a contenido y organización. Muchos investigadores utilizan estas fichas para realizar estudios comparativos entre especies (por ejemplo, patrones de muda, tipos de alimentos ingeridos, estructura de los nidos, tamaño de los huevos o filopatría natal); por ello, buscan información específica en el mismo lugar dentro de una serie de fichas. Por ello, los autores de las contribuciones deben seguir al pie de la letra las directrices de [los](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.3as4poj)[Apéndices 2 y 3](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.hjoo9cq14meu). 

Reconocemos, sin embargo, que la biología de las aves varía mucho de una especie a otra. Por ello, es necesario que haya flexibilidad en el contenido de las fichas. Se prevé la exclusión de determinadas subsecciones para algunas especies (por ejemplo, no habría subsección de Calendario y Rutas de Migración para una especie no migratoria).

El personal de BOW considerará la adición de nuevas secciones o subsecciones; no obstante, deberá mantenerse el orden de las secciones y subsecciones estándar, tal y como se muestra en [el Apéndice 2](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.3as4poj), incluso si se intercalan secciones o subsecciones creadas por el autor. Cualquier nueva sección o subsección deberá proponerse al personal de BOW a través del formulario de cumplimentación de borradores ([inglés](https://forms.gle/e6uTR5E8Z5aXXc9n6), [español](https://forms.gle/4e3PifYqvKrbQ1tV8)) o por correo electrónico. Si se aprueban, los cambios se promulgarán según los plazos del personal técnico de BOW.

\
Tenga en cuenta que cualquier contenido importado de HBW se añade automáticamente a la sección introductoria de cada página (etiquetada con "(introducción)" en [el Apéndice 2](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.3as4poj)). Este contenido debe desglosarse en otras secciones y subsecciones, según proceda.

## Gramática y formato {#sec-content-grammar}

### Gramática, puntuación y estilo {#sec-content-grammar-grammar}

[En el Apéndice 4](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.39kk8xu)encontrará información detallada sobre gramática, puntuación, estilo y convenciones de formato.

Las fichas antiguas se escribían en estilo telegráfico, y algunas secciones (como Plumajes, Mudas, Partes desnudas y Medidas) siguen exigiendo una presentación “telegráfica”. Con la transición a la publicación en línea, no hay límites específicos de palabras ni del número de referencias utilizadas. Los colaboradores deben esforzarse por ser claros y concisos y utilizar frases completas siempre que sea posible.

Las fichas de especies de BOW se traducen y seguirán traduciéndose del inglés a varios idiomas. BOW y DeepL, el servicio de traducción utilizado por BOW, mantienen un glosario para facilitar estas traducciones. No obstante, los colaboradores deben procurar deletrear las palabras y abreviar menos (por ejemplo, deletrear los meses, los estados y las provincias) y evitar palabras o frases que puedan resultar ambiguas o incorrectas al traducirlas. Los nombres de las aves se introducen mediante una "etiqueta de especie" (véase [el Paso 3: Entender la barra de menús del editor](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#heading=h.1y810tw)) y, por tanto, cambiarán automáticamente en función de las preferencias lingüísticas del usuario; sin embargo, las etiquetas no pueden traducirse automáticamente en DeepL, por lo que los colaboradores deben procurar escribir sobre una especie en singular y evitar los posesivos siempre que sea posible.

Tenga en cuenta, no obstante, que el uso repetido de palabras o términos más largos (por ejemplo, Área de Aves Endémicas \[AAB\] o Isla Farallón del Sureste \[SEFI\]) puede resultar engorroso para el lector. En tales casos, los términos pueden definirse en su primer uso en cada sección y pueden abreviarse a partir de entonces en esa sección (para páginas cortas, la abreviatura puede definirse una sola vez por página). La misma convención se aplica a los nombres científicos. Las principales excepciones son las medidas y estadísticas (m, km, min, yr, SD, p, CI, etc.), para las que se utilizan abreviaturas estándar que no están definidas.

Por favor, corrija la ortografía del manuscrito en la medida de lo posible. La eBird/Clements Checklist se publica en inglés americano; por lo tanto, pedimos que las fichas de BOW se escriban en inglés americano para mayor coherencia (por ejemplo, "gray", no "grey", y "molt", no "moult"). En el futuro (esperamos, cercano), los autores podrán escribir en su idioma preferido.

### Referencias/Citas {#sec-content-grammar-references}

Las fichas BOW publicadas utilizan un sistema de referencias numeradas en el que las citas se representan mediante números entre paréntesis en el lugar apropiado del texto. Los colaboradores deben revisar y añadir las citas vinculadas al texto (véase [Paso 5: Vinculación y adición de referencias](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#heading=h.1ci93xb)). Una vez vinculada una cita dentro de una sección de una ficha, nuestro sistema le asignará automáticamente un número, y la referencia aparecerá automáticamente en la página Referencias en el orden en que se cite en el texto (o alfabéticamente, según se prefiera). De este modo, no es necesario cotejar las citas en el texto con la página de Referencias.

Cuando cite en el texto de la ficha, inserte las citas entre paréntesis y **en orden cronológico** con una coma y un espacio insertado entre las referencias, por ejemplo, (Pyle 2017) o (Anderson et al. 2009, Smith y Anderson 2014, Pyle 2017). Las citas de un mismo año deben ordenarse alfabéticamente. Por lo general, se prefiere citar al final de la frase, a menos que el objetivo sea destacar el trabajo de un autor o autores en particular. Otras convenciones relativas a las citas son las siguientes:

-   Cuando cite observaciones/datos de autores de fichas BOW, hágalo como: 

    -   (J. Smith, observación personal) o (J. Smith, datos inéditos)

-   Para citas inéditas de personas que no sean autores de fichas BOW, indique sus nombres completos en los Agradecimientos y cítelos en el texto principal como: 

    -   (J. Smith, comunicación personal) o (J. Smith, datos inéditos) 

-   Cuando cite observaciones/datos de una versión anterior de una ficha BOW de una persona que ya no es autora de la ficha, cite la versión anterior de la ficha y acredite claramente a la persona:

    -   R. E. Anderson encontró... (Jones et al. 1997)

-   Se acepta citar artículos como "en prensa", que deben añadirse como nuevas referencias en la base de datos. Una vez publicado el artículo, envíenos un correo electrónico con todos los detalles de la cita para que podamos actualizar la referencia vinculada en la ficha.

    -   (Smith, en prensa) o (Smith et al., en prensa)

-   **Nota:** Los manuscritos "en preparación", "en revisión" o "presentados" deben citarse en el texto de la ficha como "datos no publicados" y no deben añadirse a la base de datos de referencias. 

-   Cuando cite un registro de espécimen, una lista de comprobación de eBird o un registro de xeno-canto, utilice el siguiente formato (tenga en cuenta los hipervínculos):

    -   Una hembra recogida el 9 de junio tenía la bursa de 4 × 2 mm y el cráneo osificado al 50% (Instituto de Biodiversidad de la Universidad de Kansas [KU 131737](http://portal.vertnet.org/o/ku/birds?id=429a80fd-5e77-4057-89fe-fe834d081699)).

    -   En Halmahera, también emite más chirridos de zumbido hacia abajo, cada uno de unos 0,4-0,5 s, tono ca. 6,0-7,2 kHz (M. Anderson, xeno-canto: [XC497728](http://www.xeno-canto.org/497728)).

    -   Hay dos registros extralimitales. El primero fue un avistamiento no documentado en Gili Trawangan (F. Dijkstra, eBird: [S68127960](https://ebird.org/checklist/S68127960?__hstc=65717809.0274d9e08ce2df9359e606762fab2b07.1652279465096.1659012084903.1659014944969.260&__hssc=65717809.34.1659014944969&__hsfp=868227580)).

    -   Se ha observado a *Patagioenas araucana* bañándose en aguas poco profundas (D. Ghigliotto, iNaturalist: 149930529).

Para más detalles sobre estilo, formato y citas, véanse los [apéndices 4](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.39kk8xu)y [5](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.1opuj5n).