*Versión 15: Actualizada en mayo de 2025*

# Panorama general {.unnumbered}

Gracias por ofrecerse como voluntaria/o para trabajar en una ficha de especies de Birds of the World (BOW). Nuestro objetivo es hacer de BOW una fuente de información esencial sobre la biología de todas las aves del mundo. Esta dinámica plataforma es posible gracias a la fusión de dos de las publicaciones del Cornell Lab, *Birds of North America* (BNA) y *Neotropical Birds* (NB), con contenidos del *Handbook of the Birds of the World* (HBW Alive) y *Bird Families of the World*, publicados originalmente por Lynx Edicions. BOW cuenta con el apoyo de datos en tiempo real de [eBird](https://ebird.org/home)y multimedia de la [Macaulay Library](https://www.macaulaylibrary.org/)(que ahora ha incorporado considerable material originalmente archivado en la Internet Bird Collection).

Nuestro objetivo final es generar descripciones de especies exhaustivas para cada una de las aproximadamente 11.145 especies de aves del mundo. Esta guía repasará los aspectos básicos de la revisión de una ficha de especie, con orientaciones sobre el contenido, el estilo y el formato. Se espera que todas las revisiones de las fichas sigan estrictamente estas directrices en aras de la coherencia, la claridad y la eficacia.

**Para participar en el proyecto BOW, deberá revisar y cumplir las normas de autoría, conducta y contenido que se detallan en [el Apéndice 1](https://docs.google.com/document/d/1Y06setGmeXlI9Kho0BFB73_tqh6QVMra/edit#bookmark=id.qsh70q). También deberá rellenar un formulario de información para colaboradores (en [inglés](https://forms.gle/C3MySs5DtQZ1NR6b8)y [español](https://forms.gle/EZes93EWtmtrvtXi7)). Deberá volver a enviar este formulario cada dos años para mantener su condición de colaborador activo.**

En una revisión típica, el personal de BOW le concederá "acceso de autor" a un borrador de ficha que podrá revisar en la web de BOW sin que sus cambios sean visibles públicamente. Este borrador contendrá todo lo que estaba presente en la versión más reciente de la ficha. Usted y/o su equipo deberán combinar, editar o eliminar estos contenidos a medida que vayan añadiendo nuevos contenidos a la ficha.

Cuando haya completado su revisión, rellene el Formulario de finalización del borrador ([inglés](https://forms.gle/e6uTR5E8Z5aXXc9n6), [español](https://forms.gle/4e3PifYqvKrbQ1tV8)). A continuación, el personal de BOW revisará el borrador y podrá solicitar aclaraciones, formato, adiciones u otros cambios. El personal de BOW también añadirá medios (imágenes, sonidos y figuras y los pies de foto asociados) y editará y formateará completamente la ficha según sea necesario. Una vez hecho esto, dispondrá de un periodo definido de Revisión por el Autor para realizar los cambios finales en la ficha antes de que se considere lista para su publicación. Una vez transcurrido este plazo, el borrador podrá publicarse independientemente de que el personal de BOW reciba o no su confirmación final.

En este documento se incluye información detallada sobre cada paso del proceso. Gracias por sus esfuerzos para hacer de BOW un recurso autorizado y dinámico.

**Equipo editorial principal:** Shawn Billerman ([smb223\@cornell.edu](mailto:smb223@cornell.edu)), Brooke Keeney ([bkk37\@cornell.edu](mailto:bkk37@cornell.edu)), Fernando Medrano ([fm458\@cornell.edu](mailto:fm458@cornell.edu)), Nicholas Sly ([nds22\@cornell.edu](mailto:nds22@cornell.edu)), Maria Smith ([mgs248\@cornell.edu](mailto:mgs248@cornell.edu))

\
El Cornell Lab of Ornithology (http://www.birds.cornell.edu/) patrocina la serie BOW y posee los derechos de autor.