---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Guía de inicio rápido para la edición y revisión de BOW {.unnumbered}

Para editar o revisar una ficha, trabajará con un borrador de ficha no es visible para el público en general. Los pasos siguientes son una guía rápida para ayudarle a acceder y editar (si procede) el borrador de su ficha:

-   <div>

    Vaya a <https://birdsoftheworld.org/bow/home>e inicie sesión en su ficha de Cornell Lab (si se le solicita). Puede comprobar que ha iniciado sesión si ve una silueta negra de una persona en la parte superior derecha de la página seguida de su nombre y nombre de usuario entre paréntesis.

    **Tenga en cuenta que éste debe ser su nombre de usuario individual, NO un nombre/login institucional o de grupo.**

    </div>

-   <div>

    Una vez iniciada la sesión, utilice el campo de búsqueda de especies o la lista taxonómica para navegar hasta la ficha de especies en la que va a trabajar. La página inicial de "Introducción" que verá cuando busque su ficha es la versión "en vivo" de la ficha. La versión en vivo no es editable. Deberá acceder a la versión "borrador" de la ficha para ver o realizar cambios.

    </div>

-   <div>

    **Para abrir el borrador de la ficha** para revisarlo o editarlo, haga clic en el botón naranja que dice "Version: Live - X.Y" en la parte superior de la pantalla (el número de versión depende de cuántas veces se haya actualizado el contenido citable de la ficha). Seleccione la opción **"Draft**" en el menú desplegable.

    </div>

-   <div>

    Debería ver una barra naranja en la parte superior de la pantalla que dice "REVISION". Eso indica que está viendo el borrador.

    </div>

-   <div>

    **Para revisar una ficha:** Puede navegar entre las páginas en modo borrador utilizando el índice de artículos de la parte izquierda de la página o los botones de navegación de la parte inferior de cada página. Normalmente, sólo el autor o autores principales de una revisión pueden editar el texto durante la revisión; a los demás revisores se les pide que envíen sus comentarios en un documento de Word o por correo electrónico al miembro del personal de BOW que coordina la revisión.

    </div>

-   <div>

    **Para editar una ficha:** Haga clic en el botón naranja "Edit revision" que aparece en la parte superior derecha del texto que desea editar. Se abrirá una ventana del editor en línea. Una vez que abra el editor en línea, las herramientas de edición se mostrarán en una barra de menú cerca de la parte superior de la pantalla de su navegador. Puede pasar el ratón por encima de cualquiera de los botones para obtener una breve descripción de su funcionalidad.

    </div>

-   <div>

    El cuadro de texto blanco situado debajo de la barra de menú del editor mostrará la versión preliminar del texto. Puede modificar este texto según sea necesario sin afectar a lo que la gente ve en la versión en línea en vivo de la ficha en BOW. Puede verificar que está editando el borrador de la ficha comprobando que hay un óvalo naranja bajo el nombre de la especie en la esquina superior izquierda de la ventana del editor que dice "REVISION". **Asegúrese de guardar su trabajo utilizando los botones de la parte superior derecha de la pantalla.**

    </div>

-   <div>

    Una vez que empieces a editar y guardar los cambios, el sitio activo (lo que ve el público) seguirá mostrando la versión antigua de la ficha y sus medios asociados, pero las páginas de borrador mostrarán tu texto actualizado.

    </div>

Consulte las instrucciones completas para autores para obtener más detalles sobre el acceso al sistema, el formato, el estilo y cualquier otro aspecto relevante para la revisión o corrección de una ficha. Si necesita más ayuda o tiene alguna pregunta, póngase en contacto con Brooke Keeney ([bkk37\@cornell.edu](mailto:bkk37@cornell.edu) ) o Maria Smith ([mgs248\@cornell.edu](mailto:mgs248@cornell.edu) ).